// This file is auto-generated by @hey-api/openapi-ts

export const CreateOwnerDtoSchema = {
  type: "object",
  properties: {
    name: {
      type: "string",
      example: "Jane Doe",
    },
    email: {
      type: "string",
      example: "owner@example.com",
    },
    password: {
      type: "string",
      example: "strongPassword1",
      minLength: 8,
    },
  },
  required: ["name", "email", "password"],
} as const;

export const UpsertSettingDtoSchema = {
  type: "object",
  properties: {
    valueType: {
      type: "string",
      enum: ["string", "json"],
      default: "string",
    },
    value: {
      type: "object",
      description: "String for valueType=string; any JSON for valueType=json",
    },
  },
  required: ["valueType", "value"],
} as const;

export const CreateLlmCredentialDtoSchema = {
  type: "object",
  properties: {
    provider: {
      type: "string",
      example: "anthropic",
    },
    model: {
      type: "string",
      example: "claude-sonnet-4-6",
    },
    apiKey: {
      type: "string",
    },
    fallbackModel: {
      type: "string",
      example: "claude-haiku-4-5",
    },
    label: {
      type: "string",
    },
    status: {
      type: "string",
      enum: ["active", "disabled"],
    },
    supportsChat: {
      type: "boolean",
      default: true,
    },
    supportsEmbedding: {
      type: "boolean",
      default: false,
    },
  },
  required: ["provider", "model", "apiKey"],
} as const;

export const UpdateLlmCredentialDtoSchema = {
  type: "object",
  properties: {
    provider: {
      type: "string",
      example: "anthropic",
    },
    model: {
      type: "string",
      example: "claude-sonnet-4-6",
    },
    apiKey: {
      type: "string",
    },
    fallbackModel: {
      type: "string",
      example: "claude-haiku-4-5",
    },
    label: {
      type: "string",
    },
    status: {
      type: "string",
      enum: ["active", "disabled"],
    },
    supportsChat: {
      type: "boolean",
      default: true,
    },
    supportsEmbedding: {
      type: "boolean",
      default: false,
    },
  },
} as const;

export const LlmHealthCheckResultDtoSchema = {
  type: "object",
  properties: {
    ok: {
      type: "boolean",
      example: true,
    },
    latencyMs: {
      type: "number",
      example: 482,
    },
    provider: {
      type: "string",
      example: "anthropic",
    },
    model: {
      type: "string",
      example: "claude-sonnet-4-6",
    },
    error: {
      type: "string",
      example: "Anthropic 401: invalid x-api-key",
    },
  },
  required: ["ok", "latencyMs", "provider", "model"],
} as const;

export const CreateTemplateDtoSchema = {
  type: "object",
  properties: {
    name: {
      type: "string",
    },
    description: {
      type: "string",
    },
    image: {
      type: "string",
      example: "ghcr.io/org/agent:latest",
    },
    defaultConfig: {
      type: "object",
    },
    defaultResources: {
      type: "object",
    },
    paddockConfig: {
      type: "object",
    },
    defaultKnowledgeIds: {
      type: "array",
      items: {
        type: "string",
      },
    },
  },
  required: ["name", "description", "image"],
} as const;

export const UpdateTemplateDtoSchema = {
  type: "object",
  properties: {
    name: {
      type: "string",
    },
    description: {
      type: "string",
    },
    image: {
      type: "string",
      example: "ghcr.io/org/agent:latest",
    },
    defaultConfig: {
      type: "object",
    },
    defaultResources: {
      type: "object",
    },
    paddockConfig: {
      type: "object",
    },
    defaultKnowledgeIds: {
      type: "array",
      items: {
        type: "string",
      },
    },
  },
} as const;

export const SetTemplateSkillsDtoSchema = {
  type: "object",
  properties: {
    skillIds: {
      description: "Full list of skill IDs to attach. Replaces any prior set.",
      type: "array",
      items: {
        type: "string",
      },
    },
  },
  required: ["skillIds"],
} as const;

export const SetTemplateMcpsDtoSchema = {
  type: "object",
  properties: {
    mcpServerIds: {
      description:
        "Full list of MCP server IDs to attach. Replaces any prior set.",
      type: "array",
      items: {
        type: "string",
      },
    },
  },
  required: ["mcpServerIds"],
} as const;

export const CreateMcpServerDtoSchema = {
  type: "object",
  properties: {
    name: {
      type: "string",
    },
    description: {
      type: "object",
    },
    url: {
      type: "string",
    },
    transport: {
      type: "string",
      enum: ["streamableHttp", "sse"],
    },
    authType: {
      type: "string",
      enum: ["none", "bearer", "header"],
    },
    authValue: {
      type: "object",
    },
    enabled: {
      type: "boolean",
    },
  },
  required: ["name", "url"],
} as const;

export const UpdateMcpServerDtoSchema = {
  type: "object",
  properties: {
    name: {
      type: "string",
    },
    description: {
      type: "object",
    },
    url: {
      type: "string",
    },
    transport: {
      type: "string",
      enum: ["streamableHttp", "sse"],
    },
    authType: {
      type: "string",
      enum: ["none", "bearer", "header"],
    },
    authValue: {
      type: "object",
    },
    enabled: {
      type: "boolean",
    },
  },
} as const;

export const LoginDtoSchema = {
  type: "object",
  properties: {
    email: {
      type: "string",
      example: "jane@example.com",
    },
    password: {
      type: "string",
      example: "strongPassword1",
      minLength: 8,
    },
  },
  required: ["email", "password"],
} as const;

export const RegisterDtoSchema = {
  type: "object",
  properties: {
    name: {
      type: "string",
      example: "Jane Doe",
    },
    email: {
      type: "string",
      example: "jane@example.com",
    },
    password: {
      type: "string",
      example: "strongPassword1",
      minLength: 8,
    },
  },
  required: ["name", "email", "password"],
} as const;

export const UserRoleTypesSchema = {
  type: "string",
  enum: ["Owner", "Admin", "User", "Agent"],
  description:
    "Server filters Owner/Admin out unless the presenting API key carries the embed:mint-admin scope; plain embed keys cannot grant platform-admin to a visitor.",
} as const;

export const EmbedTokenDtoSchema = {
  type: "object",
  properties: {
    sub: {
      type: "string",
      description:
        "Subject — used as clientId for routing inside the bridle hub.",
      example: "user-123",
    },
    email: {
      type: "string",
      example: "alice@example.com",
    },
    roles: {
      type: "array",
      description:
        "Server filters Owner/Admin out unless the presenting API key carries the embed:mint-admin scope; plain embed keys cannot grant platform-admin to a visitor.",
      items: {
        $ref: "#/components/schemas/UserRoleTypes",
      },
    },
    expiresIn: {
      type: "string",
      description: "Duration string (s/m/h/d). Defaults to 15m.",
      example: "15m",
    },
  },
  required: ["sub"],
} as const;

export const ApiKeyScopeTypesSchema = {
  type: "string",
  enum: ["embed:mint", "embed:mint-admin", "admin"],
} as const;

export const CreateApiKeyDtoSchema = {
  type: "object",
  properties: {
    name: {
      type: "string",
      example: "Marketing site embed",
    },
    scopes: {
      type: "array",
      example: ["embed:mint"],
      items: {
        $ref: "#/components/schemas/ApiKeyScopeTypes",
      },
    },
    expiresAt: {
      type: "string",
      description: "ISO date string. Omit for a non-expiring key.",
      example: "2027-01-01T00:00:00.000Z",
    },
  },
  required: ["name", "scopes"],
} as const;

export const GraphNodeDtoSchema = {
  type: "object",
  properties: {
    id: {
      type: "string",
    },
    label: {
      type: "string",
    },
    entityType: {
      type: "string",
    },
    description: {
      type: "string",
    },
  },
  required: ["id", "label", "entityType", "description"],
} as const;

export const GraphEdgeDtoSchema = {
  type: "object",
  properties: {
    id: {
      type: "string",
    },
    source: {
      type: "string",
    },
    target: {
      type: "string",
    },
    weight: {
      type: "number",
    },
    keywords: {
      type: "string",
    },
    description: {
      type: "string",
    },
  },
  required: ["id", "source", "target", "weight", "keywords", "description"],
} as const;

export const GraphDtoSchema = {
  type: "object",
  properties: {
    nodes: {
      type: "array",
      items: {
        $ref: "#/components/schemas/GraphNodeDto",
      },
    },
    edges: {
      type: "array",
      items: {
        $ref: "#/components/schemas/GraphEdgeDto",
      },
    },
    isTruncated: {
      type: "boolean",
    },
  },
  required: ["nodes", "edges", "isTruncated"],
} as const;

export const CreateKnowledgeDtoSchema = {
  type: "object",
  properties: {
    name: {
      type: "string",
    },
    description: {
      type: "string",
    },
    entityTypes: {
      type: "array",
      items: {
        type: "string",
      },
    },
    relationshipTypes: {
      type: "array",
      items: {
        type: "string",
      },
    },
  },
  required: ["name"],
} as const;

export const UpdateKnowledgeDtoSchema = {
  type: "object",
  properties: {
    name: {
      type: "string",
    },
    description: {
      type: "string",
      nullable: true,
    },
    entityTypes: {
      type: "array",
      items: {
        type: "string",
      },
    },
    relationshipTypes: {
      type: "array",
      items: {
        type: "string",
      },
    },
  },
} as const;

export const QueryKnowledgeDtoSchema = {
  type: "object",
  properties: {
    query: {
      type: "string",
    },
    mode: {
      type: "string",
      enum: ["hybrid", "local", "global", "naive"],
      default: "hybrid",
    },
    topK: {
      type: "number",
      default: 25,
    },
  },
  required: ["query"],
} as const;

export const KnowledgeQueryReferenceDtoSchema = {
  type: "object",
  properties: {
    referenceId: {
      type: "string",
    },
    filePath: {
      type: "string",
    },
  },
  required: ["referenceId", "filePath"],
} as const;

export const KnowledgeQueryResultDtoSchema = {
  type: "object",
  properties: {
    answer: {
      type: "string",
    },
    references: {
      type: "array",
      items: {
        $ref: "#/components/schemas/KnowledgeQueryReferenceDto",
      },
    },
  },
  required: ["answer", "references"],
} as const;

export const CreateSourceDtoSchema = {
  type: "object",
  properties: {
    type: {
      type: "string",
      enum: ["file", "url", "text"],
    },
    name: {
      type: "string",
    },
    url: {
      type: "string",
    },
    content: {
      type: "string",
    },
  },
  required: ["type", "name"],
} as const;

export const AddFromSitemapDtoSchema = {
  type: "object",
  properties: {
    sitemapUrl: {
      type: "string",
      example: "https://developer.paypal.com/sitemap.xml",
    },
    urlPrefix: {
      type: "string",
      example: "https://developer.paypal.com/docs/checkout/",
    },
  },
  required: ["sitemapUrl"],
} as const;

export const AddFromSitemapResultDtoSchema = {
  type: "object",
  properties: {
    added: {
      type: "number",
      example: 47,
    },
    discovered: {
      type: "number",
      example: 51,
    },
  },
  required: ["added", "discovered"],
} as const;

export const AddFromArchiveResultDtoSchema = {
  type: "object",
  properties: {
    detected: {
      type: "number",
      example: 288,
      description:
        "Number of ingestable files detected in the archive. Import runs in the background; refresh the sources list to watch them appear.",
    },
    started: {
      type: "boolean",
      example: true,
    },
  },
  required: ["detected", "started"],
} as const;

export const AgentPodStatusDtoSchema = {
  type: "object",
  properties: {
    agentId: {
      type: "string",
      example: "agent-abc-123",
    },
    podName: {
      type: "string",
      example: "agent-agent-abc-123",
    },
    phase: {
      type: "string",
      enum: ["Pending", "Running", "Succeeded", "Failed", "Unknown"],
      example: "Running",
    },
    ready: {
      type: "boolean",
      example: true,
    },
    restartCount: {
      type: "number",
      example: 0,
    },
    startedAt: {
      type: "string",
      nullable: true,
      example: "2026-04-30T10:15:00Z",
    },
    lastTerminationReason: {
      type: "string",
      nullable: true,
      example: "OOMKilled",
    },
    containerWaitingReason: {
      type: "string",
      nullable: true,
      example: "CrashLoopBackOff",
    },
    message: {
      type: "string",
      nullable: true,
    },
    observedAt: {
      type: "string",
      example: "2026-04-30T10:30:00Z",
    },
  },
  required: [
    "agentId",
    "podName",
    "phase",
    "ready",
    "restartCount",
    "startedAt",
    "lastTerminationReason",
    "containerWaitingReason",
    "message",
    "observedAt",
  ],
} as const;

export const AgentStatusDtoSchema = {
  type: "object",
  properties: {
    agent: {
      type: "object",
      description: "Agent DB record (id, name, status, etc.)",
    },
    pod: {
      nullable: true,
      description:
        "Live pod status; null if no pod is currently running for this agent.",
      allOf: [
        {
          $ref: "#/components/schemas/AgentPodStatusDto",
        },
      ],
    },
  },
  required: ["agent", "pod"],
} as const;

export const AgentPodMetricsDtoSchema = {
  type: "object",
  properties: {
    cpuMilli: {
      type: "number",
      example: 234,
      description: "Current CPU usage in millicores",
    },
    memBytes: {
      type: "number",
      example: 471859200,
      description: "Current memory usage in bytes",
    },
    cpuLimitMilli: {
      type: "number",
      example: 2000,
      description: "CPU limit in millicores",
    },
    memLimitBytes: {
      type: "number",
      example: 2147483648,
      description: "Memory limit in bytes",
    },
  },
  required: ["cpuMilli", "memBytes", "cpuLimitMilli", "memLimitBytes"],
} as const;

export const AgentNodeMetricsDtoSchema = {
  type: "object",
  properties: {
    name: {
      type: "string",
      example: "k3s-agent-gnk",
    },
    diskAvailBytes: {
      type: "number",
      example: 157109764096,
    },
    diskCapacityBytes: {
      type: "number",
      example: 163817959424,
    },
  },
  required: ["name", "diskAvailBytes", "diskCapacityBytes"],
} as const;

export const AgentMetricsDtoSchema = {
  type: "object",
  properties: {
    pod: {
      $ref: "#/components/schemas/AgentPodMetricsDto",
    },
    node: {
      $ref: "#/components/schemas/AgentNodeMetricsDto",
    },
  },
  required: ["pod", "node"],
} as const;

export const AgentEnvVarDtoSchema = {
  type: "object",
  properties: {
    name: {
      type: "string",
      example: "LOG_LEVEL",
    },
    value: {
      type: "string",
      example: "debug",
    },
  },
  required: ["name", "value"],
} as const;

export const AgentMcpDtoSchema = {
  type: "object",
  properties: {
    name: {
      type: "string",
      description: "Unique MCP server name (key in the runtime registry).",
    },
    transport: {
      type: "string",
      enum: ["streamableHttp", "sse"],
      description: "Transport protocol the runtime should use to connect.",
    },
    url: {
      type: "string",
      description: "MCP server endpoint URL.",
    },
    authType: {
      type: "string",
      enum: ["none", "bearer", "header"],
      description: "Auth scheme for the connection.",
    },
    authValue: {
      type: "string",
      nullable: true,
      description:
        "Auth credential. For `bearer`: raw token (runtime adds the `Bearer ` prefix). For `header`: literal `Header-Name: value` line. `null` when authType is `none`.",
    },
    enabled: {
      type: "boolean",
      description:
        "Always `true` in this list — disabled servers are filtered server-side. Kept for forward compatibility.",
    },
  },
  required: ["name", "transport", "url", "authType", "authValue", "enabled"],
} as const;

export const AgentResourcesDtoSchema = {
  type: "object",
  properties: {
    cpu: {
      type: "string",
      example: "500m",
    },
    memory: {
      type: "string",
      example: "512Mi",
    },
  },
  required: ["cpu", "memory"],
} as const;

export const CreateAgentDtoSchema = {
  type: "object",
  properties: {
    name: {
      type: "string",
    },
    templateId: {
      type: "string",
    },
    llmCredentialId: {
      type: "string",
    },
    config: {
      type: "object",
    },
    resources: {
      $ref: "#/components/schemas/AgentResourcesDto",
    },
    isPublic: {
      type: "boolean",
      description:
        "When true, the agent is visible on the public landing page to unauthenticated visitors.",
    },
    allowedOrigins: {
      description:
        "Origins (scheme + host + port) authorized to open browser WebSockets to this bot without a JWT. Only consulted when isPublic=true.",
      example: ["https://bridle.cleanslice.org", "http://localhost:5173"],
      type: "array",
      items: {
        type: "string",
      },
    },
    knowledgeIds: {
      type: "array",
      items: {
        type: "string",
      },
    },
    isAdmin: {
      type: "boolean",
      description:
        "When true, the agent is created as the Ranch admin on first deploy: any existing admin is demoted (and redeployed without RANCH_ADMIN), and this agent boots with RANCH_ADMIN=true + a service token. Single-admin invariant is enforced.",
    },
  },
  required: ["name", "templateId"],
} as const;

export const UpdateAgentDtoSchema = {
  type: "object",
  properties: {
    name: {
      type: "string",
    },
    templateId: {
      type: "string",
    },
    llmCredentialId: {
      type: "string",
    },
    config: {
      type: "object",
    },
    resources: {
      $ref: "#/components/schemas/AgentResourcesDto",
    },
    isPublic: {
      type: "boolean",
      description:
        "When true, the agent is visible on the public landing page to unauthenticated visitors.",
    },
    allowedOrigins: {
      description:
        "Origins (scheme + host + port) authorized to open browser WebSockets to this bot without a JWT. Only consulted when isPublic=true.",
      example: ["https://bridle.cleanslice.org", "http://localhost:5173"],
      type: "array",
      items: {
        type: "string",
      },
    },
    knowledgeIds: {
      type: "array",
      items: {
        type: "string",
      },
    },
    isAdmin: {
      type: "boolean",
      description:
        "When true, the agent is created as the Ranch admin on first deploy: any existing admin is demoted (and redeployed without RANCH_ADMIN), and this agent boots with RANCH_ADMIN=true + a service token. Single-admin invariant is enforced.",
    },
    debugEnabled: {
      type: "boolean",
      description:
        "Enable debug mode — emits the prompt-debug event stream and verbose pod logs (LOG_LEVEL=debug). The verbose-log half applies on the next agent restart; the prompt-debug stream flips live.",
    },
  },
} as const;

export const FileChunkDtoSchema = {
  type: "object",
  properties: {
    path: {
      type: "string",
      example: "data/sessions/bridle:admin.jsonl",
    },
    content: {
      type: "string",
      description: "UTF-8 slice of the file from `offset`.",
    },
    size: {
      type: "number",
      example: 262144,
      description: "Byte length of `content`.",
    },
    totalSize: {
      type: "number",
      example: 393216,
      description: "Full byte length of the file.",
    },
    offset: {
      type: "number",
      example: 0,
      description: "Byte offset of the first byte of `content`.",
    },
    nextOffset: {
      type: "number",
      nullable: true,
      example: 262144,
      description:
        "Pass as `offset` on the next request. `null` when there is no more data.",
    },
    hasMore: {
      type: "boolean",
      example: true,
    },
    updatedAt: {
      type: "string",
      format: "date-time",
    },
  },
  required: [
    "path",
    "content",
    "size",
    "totalSize",
    "offset",
    "nextOffset",
    "hasMore",
    "updatedAt",
  ],
} as const;

export const SaveFileDtoSchema = {
  type: "object",
  properties: {
    content: {
      type: "string",
      description: "Full file content as text",
    },
  },
  required: ["content"],
} as const;

export const DeleteFilesDtoSchema = {
  type: "object",
  properties: {
    deleted: {
      type: "number",
      example: 3,
      description: "Number of S3 objects deleted by this request.",
    },
  },
  required: ["deleted"],
} as const;

export const BridleTextPartDtoSchema = {
  type: "object",
  properties: {
    type: {
      type: "string",
      enum: ["text", "image", "file"],
      example: "text",
    },
    text: {
      type: "string",
    },
  },
  required: ["type", "text"],
} as const;

export const BridleImagePartDtoSchema = {
  type: "object",
  properties: {
    type: {
      type: "string",
      enum: ["text", "image", "file"],
      example: "image",
    },
    base64: {
      type: "string",
      description: "Base64-encoded image data",
    },
    mediaType: {
      type: "string",
      description: "MIME type",
      example: "image/jpeg",
    },
  },
  required: ["type", "base64", "mediaType"],
} as const;

export const SendMessageDtoSchema = {
  type: "object",
  properties: {
    text: {
      type: "string",
      description: "Message text (plain-text shorthand)",
    },
    parts: {
      description: "Rich content parts. If omitted, built from text + images.",
      type: "array",
      items: {
        $ref: "#/components/schemas/BridleTextPartDto",
      },
    },
    images: {
      description: "Attached images (legacy — prefer parts)",
      type: "array",
      items: {
        $ref: "#/components/schemas/BridleImagePartDto",
      },
    },
  },
  required: ["text"],
} as const;

export const BridleHealthDtoSchema = {
  type: "object",
  properties: {
    ok: {
      type: "boolean",
      example: true,
    },
    agentConnected: {
      type: "boolean",
      description: "Whether any agent runtime is connected via WebSocket",
    },
    browserClients: {
      type: "number",
      description: "Number of browser clients connected",
    },
  },
  required: ["ok", "agentConnected", "browserClients"],
} as const;

export const BridleAgentHealthDtoSchema = {
  type: "object",
  properties: {
    ok: {
      type: "boolean",
      example: true,
    },
    agentConnected: {
      type: "boolean",
      description: "Whether this agent is connected via WebSocket",
    },
    browserClients: {
      type: "number",
      description: "Number of browser clients connected to this agent",
    },
    agentId: {
      type: "string",
      description: "Bot identifier",
    },
  },
  required: ["ok", "agentConnected", "browserClients", "agentId"],
} as const;

export const TranscriptMessageDtoSchema = {
  type: "object",
  properties: {
    id: {
      type: "string",
      example: "c94dbcf2-64f1-4e84-9723-c94e2d815f61",
    },
    role: {
      type: "string",
      enum: ["user", "assistant"],
      example: "assistant",
    },
    text: {
      type: "string",
      example: "Hello, how can I help?",
    },
    ts: {
      type: "number",
      example: 1777562539964,
      description: "Unix epoch milliseconds.",
    },
  },
  required: ["id", "role", "text", "ts"],
} as const;

export const TranscriptResponseDtoSchema = {
  type: "object",
  properties: {
    messages: {
      type: "array",
      items: {
        $ref: "#/components/schemas/TranscriptMessageDto",
      },
    },
    channel: {
      type: "string",
      example: "admin",
      description: "Channel the transcript was loaded from.",
    },
    nextCursor: {
      type: "string",
      nullable: true,
      description:
        "Pass back as `cursor` to fetch the previous page. `null` when no older messages.",
    },
    hasMore: {
      type: "boolean",
      example: false,
    },
  },
  required: ["messages", "channel", "nextCursor", "hasMore"],
} as const;

export const ImportSkillUrlDtoSchema = {
  type: "object",
  properties: {
    url: {
      type: "string",
      description:
        "GitHub URL — folder (tree/<sha>/<path>) or file (blob/<sha>/<path>). The folder must contain a SKILL.md or README.md.",
      example:
        "https://github.com/supabase/agent-skills/tree/main/skills/supabase-postgres-best-practices",
    },
    name: {
      type: "string",
    },
    overwrite: {
      type: "boolean",
      description:
        "If true and a skill with the same slug already exists, fully replace it instead of returning 409.",
    },
  },
  required: ["url"],
} as const;

export const ImportSkillDtoSchema = {
  type: "object",
  properties: {
    repo: {
      type: "string",
      example: "anthropics/skills",
      description: "GitHub owner/repo as returned by /skills/search",
    },
    path: {
      type: "string",
      example: "pdf-skill/SKILL.md",
      description: "Path to the SKILL.md file inside the repo",
    },
    name: {
      type: "string",
      description:
        "Override the auto-derived slug. Lowercase letters, digits and dashes.",
    },
    overwrite: {
      type: "boolean",
      description:
        "If true and a skill with the same slug already exists, fully replace it instead of returning 409.",
    },
  },
  required: ["repo", "path"],
} as const;

export const CreateSkillDtoSchema = {
  type: "object",
  properties: {
    name: {
      type: "string",
      example: "devops",
      description: "Unique slug — lowercase letters, digits, dashes",
    },
    title: {
      type: "string",
      example: "DevOps engineer",
    },
    body: {
      type: "string",
      description: "Markdown body of the skill",
    },
    description: {
      type: "string",
    },
  },
  required: ["name", "title", "body"],
} as const;

export const UpdateSkillDtoSchema = {
  type: "object",
  properties: {
    name: {
      type: "string",
      example: "devops",
      description: "Unique slug — lowercase letters, digits, dashes",
    },
    title: {
      type: "string",
      example: "DevOps engineer",
    },
    body: {
      type: "string",
      description: "Markdown body of the skill",
    },
    description: {
      type: "string",
    },
  },
} as const;

export const ChatSessionDtoSchema = {
  type: "object",
  properties: {
    id: {
      type: "string",
      example: "chat-9f2c…",
    },
    agentId: {
      type: "string",
    },
    channel: {
      type: "string",
      enum: ["bridle", "telegram", "slack", "internal"],
      example: "bridle",
    },
    externalUserId: {
      type: "string",
      example: "admin",
    },
    sessionKey: {
      type: "string",
      example: "bridle:admin",
    },
    title: {
      type: "object",
      nullable: true,
    },
    preview: {
      type: "object",
      nullable: true,
      description: "Last message text, truncated",
    },
    lastRole: {
      type: "string",
      enum: ["user", "assistant"],
      nullable: true,
    },
    lastMessageAt: {
      format: "date-time",
      type: "string",
      description: "Unix ms via ISO",
      example: "2026-07-15T09:12:00.000Z",
    },
    messageCount: {
      type: "number",
      description: "Monotonic lifetime total",
    },
    userMessageCount: {
      type: "number",
    },
    summary: {
      type: "object",
      nullable: true,
    },
    summaryAt: {
      type: "object",
      nullable: true,
    },
    insights: {
      type: "object",
      nullable: true,
      description: "topics/sentiment/resolved/language",
    },
    archived: {
      type: "boolean",
    },
    createdAt: {
      format: "date-time",
      type: "string",
    },
    updatedAt: {
      format: "date-time",
      type: "string",
    },
  },
  required: [
    "id",
    "agentId",
    "channel",
    "externalUserId",
    "sessionKey",
    "lastMessageAt",
    "messageCount",
    "userMessageCount",
    "archived",
    "createdAt",
    "updatedAt",
  ],
} as const;

export const ChatListResponseDtoSchema = {
  type: "object",
  properties: {
    items: {
      type: "array",
      items: {
        $ref: "#/components/schemas/ChatSessionDto",
      },
    },
    total: {
      type: "number",
      example: 128,
    },
    page: {
      type: "number",
      example: 1,
    },
    perPage: {
      type: "number",
      example: 50,
    },
  },
  required: ["items", "total", "page", "perPage"],
} as const;

export const ChatMessageDtoSchema = {
  type: "object",
  properties: {
    id: {
      type: "string",
      example: "c94dbcf2-…",
    },
    role: {
      type: "string",
      enum: [
        "user",
        "assistant",
        "summary",
        "tool_call",
        "tool_result",
        "system",
      ],
      example: "assistant",
    },
    text: {
      type: "string",
      example: "Hello, how can I help?",
    },
    ts: {
      type: "number",
      example: 1777562539964,
      description: "Unix epoch ms",
    },
  },
  required: ["id", "role", "text", "ts"],
} as const;

export const ChatMessagesResponseDtoSchema = {
  type: "object",
  properties: {
    messages: {
      type: "array",
      items: {
        $ref: "#/components/schemas/ChatMessageDto",
      },
    },
    nextCursor: {
      type: "object",
      nullable: true,
      description: "Pass to fetch the previous (older) page",
    },
    hasMore: {
      type: "boolean",
    },
  },
  required: ["messages", "hasMore"],
} as const;

export const SyncChatsDtoSchema = {
  type: "object",
  properties: {
    agentId: {
      type: "string",
      description: "Reconcile only this agent; omit for all agents",
    },
  },
} as const;

export const SyncChatsResponseDtoSchema = {
  type: "object",
  properties: {
    scannedAgents: {
      type: "number",
    },
    scannedFiles: {
      type: "number",
    },
    upserted: {
      type: "number",
    },
    skipped: {
      type: "number",
    },
  },
  required: ["scannedAgents", "scannedFiles", "upserted", "skipped"],
} as const;

export const CreateChatFeedbackDtoSchema = {
  type: "object",
  properties: {
    messageId: {
      type: "string",
      description: "Event.id of the rated assistant message",
    },
    rating: {
      type: "number",
      enum: [1, -1],
      description: "1 = 👍, -1 = 👎",
    },
    comment: {
      type: "string",
    },
  },
  required: ["messageId", "rating"],
} as const;

export const ChatFeedbackDtoSchema = {
  type: "object",
  properties: {
    id: {
      type: "string",
    },
    messageId: {
      type: "string",
    },
    rating: {
      type: "number",
      enum: [1, -1],
    },
    comment: {
      type: "object",
      nullable: true,
    },
    source: {
      type: "string",
      example: "admin",
    },
    authorId: {
      type: "object",
      nullable: true,
    },
    createdAt: {
      format: "date-time",
      type: "string",
    },
  },
  required: ["id", "messageId", "rating", "source", "createdAt"],
} as const;

export const TelegramChannelConfigDtoSchema = {
  type: "object",
  properties: {
    botToken: {
      type: "string",
      description: "Telegram bot HTTP API token (issued by @BotFather).",
    },
    botName: {
      type: "string",
      description: "Public bot username without @ — shown on landing pages.",
    },
    adminIds: {
      type: "string",
      description:
        "Comma-separated Telegram chat IDs treated as bot admins by the runtime.",
    },
  },
  required: ["botToken"],
} as const;

export const AgentChannelDtoSchema = {
  type: "object",
  properties: {
    type: {
      type: "string",
      enum: ["telegram"],
      description:
        "Channel type. Discriminator — config shape depends on this. v1 only telegram.",
    },
    config: {
      $ref: "#/components/schemas/TelegramChannelConfigDto",
    },
  },
  required: ["type", "config"],
} as const;

export const SetAgentChannelsDtoSchema = {
  type: "object",
  properties: {
    channels: {
      description:
        "Replace the full set of channels. Pass [] to clear all channels.",
      type: "array",
      items: {
        $ref: "#/components/schemas/AgentChannelDto",
      },
    },
  },
  required: ["channels"],
} as const;

export const AssignableUserRoleTypesSchema = {
  type: "string",
  enum: ["Admin", "User"],
} as const;

export const CreateUserDtoSchema = {
  type: "object",
  properties: {
    name: {
      type: "string",
      example: "Jane Doe",
    },
    email: {
      type: "string",
      example: "jane@example.com",
    },
    password: {
      type: "string",
      example: "strongPassword1",
      minLength: 8,
    },
    role: {
      example: "User",
      allOf: [
        {
          $ref: "#/components/schemas/AssignableUserRoleTypes",
        },
      ],
    },
  },
  required: ["name", "email", "password"],
} as const;

export const UpdateUserDtoSchema = {
  type: "object",
  properties: {
    name: {
      type: "string",
      example: "Jane Doe",
    },
    email: {
      type: "string",
      example: "jane@example.com",
    },
    password: {
      type: "string",
      example: "strongPassword1",
      minLength: 8,
    },
    status: {
      type: "string",
      enum: ["active", "invited", "disabled"],
    },
  },
} as const;

export const UpdateUserRoleDtoSchema = {
  type: "object",
  properties: {
    role: {
      example: "User",
      allOf: [
        {
          $ref: "#/components/schemas/AssignableUserRoleTypes",
        },
      ],
    },
  },
  required: ["role"],
} as const;

export const SaveTemplateFileDtoSchema = {
  type: "object",
  properties: {
    content: {
      type: "string",
      description: "Full file content as text",
    },
  },
  required: ["content"],
} as const;

export const InstallDeclaredSkillDtoSchema = {
  type: "object",
  properties: {
    id: {
      type: "string",
    },
    resolved: {
      type: "boolean",
    },
  },
  required: ["id", "resolved"],
} as const;

export const InstallDeclaredMcpDtoSchema = {
  type: "object",
  properties: {
    id: {
      type: "string",
    },
    resolved: {
      type: "boolean",
    },
  },
  required: ["id", "resolved"],
} as const;

export const InstallDeclaredSecretDtoSchema = {
  type: "object",
  properties: {
    name: {
      type: "string",
    },
    required: {
      type: "boolean",
    },
  },
  required: ["name", "required"],
} as const;

export const InstallDeclaredDtoSchema = {
  type: "object",
  properties: {
    skills: {
      type: "array",
      items: {
        $ref: "#/components/schemas/InstallDeclaredSkillDto",
      },
    },
    mcp: {
      type: "array",
      items: {
        $ref: "#/components/schemas/InstallDeclaredMcpDto",
      },
    },
    secrets: {
      type: "array",
      items: {
        $ref: "#/components/schemas/InstallDeclaredSecretDto",
      },
    },
  },
  required: ["skills", "mcp", "secrets"],
} as const;

export const InstallFileCountsDtoSchema = {
  type: "object",
  properties: {
    agentFiles: {
      type: "number",
    },
    scenarioFiles: {
      type: "number",
    },
  },
  required: ["agentFiles", "scenarioFiles"],
} as const;

export const InstallPreviewDtoSchema = {
  type: "object",
  properties: {
    manifest: {
      type: "object",
      description:
        "The parsed manifest. Returned as raw JSON so the UI can render any field without typed coupling.",
      additionalProperties: true,
    },
    willCreate: {
      type: "boolean",
    },
    willUpgrade: {
      type: "boolean",
    },
    existingTemplateId: {
      type: "string",
    },
    declared: {
      $ref: "#/components/schemas/InstallDeclaredDto",
    },
    files: {
      $ref: "#/components/schemas/InstallFileCountsDto",
    },
    warnings: {
      type: "array",
      items: {
        type: "string",
      },
    },
  },
  required: [
    "manifest",
    "willCreate",
    "willUpgrade",
    "declared",
    "files",
    "warnings",
  ],
} as const;

export const InstallResultDtoSchema = {
  type: "object",
  properties: {
    templateId: {
      type: "string",
    },
    templateName: {
      type: "string",
    },
    filesUploaded: {
      type: "number",
    },
    scenariosSeeded: {
      type: "number",
    },
    mcpAttached: {
      type: "array",
      items: {
        type: "string",
      },
    },
    skillsAttached: {
      type: "array",
      items: {
        type: "string",
      },
    },
    unresolvedMcp: {
      type: "array",
      items: {
        type: "string",
      },
    },
    unresolvedSkills: {
      type: "array",
      items: {
        type: "string",
      },
    },
    warnings: {
      type: "array",
      items: {
        type: "string",
      },
    },
  },
  required: [
    "templateId",
    "templateName",
    "filesUploaded",
    "scenariosSeeded",
    "mcpAttached",
    "skillsAttached",
    "unresolvedMcp",
    "unresolvedSkills",
    "warnings",
  ],
} as const;

export const InstallFromGitDtoSchema = {
  type: "object",
  properties: {
    gitUrl: {
      type: "string",
      description:
        "Git URL — https://, http://, git@host:..., or ssh://host/.../repo.git",
      example: "https://github.com/CleanSlice/agent-templates.git",
    },
    gitRef: {
      type: "string",
      description:
        "Optional ref — branch, tag, or short SHA. Defaults to the remote default branch.",
      example: "main",
    },
    params: {
      type: "object",
      description:
        'Operator-supplied params (e.g. {"language":"ru"}). Validated against the manifest at install time.',
      additionalProperties: true,
    },
    secrets: {
      type: "object",
      description:
        'Operator-supplied secrets (e.g. {"MCP_RANCH_AUTH":"sk-..."}). Used to resolve $secret:NAME references in the manifest at install time (currently for mcp[].authValue). Never echoed back.',
      additionalProperties: true,
    },
  },
  required: ["gitUrl"],
} as const;

export const CreatePaddockScenarioMessageDtoSchema = {
  type: "object",
  properties: {
    text: {
      type: "string",
    },
    from: {
      type: "string",
    },
    delayMs: {
      type: "number",
    },
  },
  required: ["text", "from"],
} as const;

export const CreatePaddockSuccessCriterionDtoSchema = {
  type: "object",
  properties: {
    dimension: {
      type: "string",
      enum: [
        "correctness",
        "tool_usage",
        "soul_compliance",
        "response_quality",
        "error_handling",
      ],
    },
    description: {
      type: "string",
    },
    weight: {
      type: "number",
    },
  },
  required: ["dimension", "description", "weight"],
} as const;

export const CreatePaddockScenarioSetupDtoSchema = {
  type: "object",
  properties: {
    files: {
      type: "object",
      additionalProperties: {
        type: "string",
      },
    },
    env: {
      type: "object",
      additionalProperties: {
        type: "string",
      },
    },
    tools: {
      type: "array",
      items: {
        type: "string",
      },
    },
  },
} as const;

export const CreatePaddockScenarioDtoSchema = {
  type: "object",
  properties: {
    templateId: {
      type: "string",
      nullable: true,
    },
    agentId: {
      type: "string",
      nullable: true,
    },
    category: {
      type: "string",
      enum: [
        "tool_use",
        "memory",
        "conversation",
        "patching_workflow",
        "edge_case",
        "multi_turn",
        "error_recovery",
      ],
    },
    difficulty: {
      type: "string",
      enum: ["easy", "medium", "hard", "adversarial"],
    },
    name: {
      type: "string",
    },
    description: {
      type: "string",
    },
    expectedBehavior: {
      type: "string",
    },
    messages: {
      type: "array",
      items: {
        $ref: "#/components/schemas/CreatePaddockScenarioMessageDto",
      },
    },
    successCriteria: {
      type: "array",
      items: {
        $ref: "#/components/schemas/CreatePaddockSuccessCriterionDto",
      },
    },
    setup: {
      nullable: true,
      allOf: [
        {
          $ref: "#/components/schemas/CreatePaddockScenarioSetupDto",
        },
      ],
    },
  },
  required: [
    "category",
    "difficulty",
    "name",
    "description",
    "expectedBehavior",
    "messages",
    "successCriteria",
  ],
} as const;

export const GeneratePaddockScenarioDtoSchema = {
  type: "object",
  properties: {
    description: {
      type: "string",
      description:
        "Free-form description of the problem / behavior the user wants to test.",
    },
    templateId: {
      type: "string",
      nullable: true,
    },
    agentId: {
      type: "string",
      nullable: true,
    },
    category: {
      type: "string",
      enum: [
        "tool_use",
        "memory",
        "conversation",
        "patching_workflow",
        "edge_case",
        "multi_turn",
        "error_recovery",
      ],
    },
    difficulty: {
      type: "string",
      enum: ["easy", "medium", "hard", "adversarial"],
    },
    credentialId: {
      type: "string",
      description:
        "Optional LlmCredential id; if omitted, the first active Anthropic credential is used.",
    },
  },
  required: ["description"],
} as const;

export const UpdatePaddockScenarioDtoSchema = {
  type: "object",
  properties: {
    category: {
      type: "string",
      enum: [
        "tool_use",
        "memory",
        "conversation",
        "patching_workflow",
        "edge_case",
        "multi_turn",
        "error_recovery",
      ],
    },
    difficulty: {
      type: "string",
      enum: ["easy", "medium", "hard", "adversarial"],
    },
    name: {
      type: "string",
    },
    description: {
      type: "string",
    },
    expectedBehavior: {
      type: "string",
    },
    messages: {
      type: "array",
      items: {
        $ref: "#/components/schemas/CreatePaddockScenarioMessageDto",
      },
    },
    successCriteria: {
      type: "array",
      items: {
        $ref: "#/components/schemas/CreatePaddockSuccessCriterionDto",
      },
    },
    setup: {
      nullable: true,
      allOf: [
        {
          $ref: "#/components/schemas/CreatePaddockScenarioSetupDto",
        },
      ],
    },
  },
} as const;

export const SecretEntryDtoSchema = {
  type: "object",
  properties: {
    name: {
      type: "string",
      example: "user-abc/openai_api_key",
    },
    value: {
      type: "string",
      example: "sk-...",
    },
    updatedAt: {
      type: "string",
      format: "date-time",
      nullable: true,
    },
  },
  required: ["name", "value", "updatedAt"],
} as const;

export const SecretListDtoSchema = {
  type: "object",
  properties: {
    provider: {
      type: "string",
      enum: ["aws", "file"],
      example: "file",
    },
    secrets: {
      type: "array",
      items: {
        $ref: "#/components/schemas/SecretEntryDto",
      },
    },
  },
  required: ["provider", "secrets"],
} as const;

export const SetSecretDtoSchema = {
  type: "object",
  properties: {
    key: {
      type: "string",
      example: "instagram:password",
      description:
        "Secret key. Upsert: an existing key is overwritten, a new key is created.",
    },
    value: {
      type: "string",
      example: "sk-...",
      description: "Secret value to store.",
    },
  },
  required: ["key", "value"],
} as const;

export const DeleteSecretDtoSchema = {
  type: "object",
  properties: {
    key: {
      type: "string",
      example: "instagram:password",
      description: "Secret key to delete. No-op if the key does not exist.",
    },
  },
  required: ["key"],
} as const;

export const ReplaceSecretsDtoSchema = {
  type: "object",
  properties: {
    store: {
      type: "object",
      additionalProperties: {
        type: "string",
      },
      example: {
        "instagram:password": "p@ss",
        "paypal:api_token": "sk-...",
      },
      description:
        "Full secret store for the agent — replaces everything. Pass {} to clear. Mirrors AWS Secrets Manager's plaintext-edit semantics.",
    },
  },
  required: ["store"],
} as const;

export const ReportUsageDtoSchema = {
  type: "object",
  properties: {
    date: {
      type: "string",
      example: "2026-04-22",
    },
    byModel: {
      type: "object",
      description:
        "Per-model usage. Key is the canonical model name (e.g. claude-sonnet-4-6).",
      example: {
        "claude-sonnet-4-6": {
          inputTokens: 12345,
          outputTokens: 6789,
          callCount: 42,
        },
      },
    },
  },
  required: ["date", "byModel"],
} as const;

export const RunPaddockJudgeOverrideDtoSchema = {
  type: "object",
  properties: {
    credentialIds: {
      type: "array",
      items: {
        type: "string",
      },
    },
    threshold: {
      type: "number",
    },
    maxLlmCalls: {
      type: "number",
    },
    maxTimeMs: {
      type: "number",
    },
  },
} as const;

export const RunPaddockEvaluationDtoSchema = {
  type: "object",
  properties: {
    agentId: {
      type: "string",
    },
    scenarioIds: {
      description:
        "Optional subset of scenario IDs. If omitted, runs the agent’s template scenarios merged with agent overrides.",
      type: "array",
      items: {
        type: "string",
      },
    },
    judgeOverride: {
      $ref: "#/components/schemas/RunPaddockJudgeOverrideDto",
    },
  },
  required: ["agentId"],
} as const;

export const BrowserSessionDtoSchema = {
  type: "object",
  properties: {
    id: {
      type: "string",
      example: "browser-7b8c2e22-...",
    },
    userId: {
      type: "string",
    },
    accountKey: {
      type: "string",
      example: "instagram:miybot",
    },
    status: {
      type: "string",
      enum: ["idle", "active", "needs_login", "expired", "stuck"],
    },
    lastUsedAt: {
      format: "date-time",
      type: "string",
    },
    createdAt: {
      format: "date-time",
      type: "string",
    },
    updatedAt: {
      format: "date-time",
      type: "string",
    },
  },
  required: [
    "id",
    "userId",
    "accountKey",
    "status",
    "lastUsedAt",
    "createdAt",
    "updatedAt",
  ],
} as const;

export const OpenSessionDtoSchema = {
  type: "object",
  properties: {
    accountKey: {
      type: "string",
      description:
        'Account identifier scoped to the calling user, e.g. "instagram:miybot" or "paypal:main". Must match /^[a-zA-Z0-9_:\\-]+$/ — anything else is rejected before it can touch the profile filesystem path.',
      example: "instagram:miybot",
    },
    loginUrl: {
      type: "string",
      description: `Page to navigate to in the pre-warmed Chrome. Drives what the VNC viewer renders when the user opens the returned vncUrl — set this to the service's login page (e.g. "https://www.instagram.com/accounts/login/"). Defaults to about:blank if omitted; the user can still type a URL in the address bar.`,
      example: "https://www.instagram.com/accounts/login/",
    },
  },
  required: ["accountKey"],
} as const;

export const BrowserSessionConnectionDtoSchema = {
  type: "object",
  properties: {
    session: {
      $ref: "#/components/schemas/BrowserSessionDto",
    },
    cdpUrl: {
      type: "string",
      description:
        "CDP WebSocket URL. Carries a single-use launch payload and the pool token — never expose to UI, only to authenticated runtime calls.",
    },
    vncUrl: {
      type: "object",
      description:
        "Live VNC URL (signed JWT, 15 min TTL). Send to the end user when they need to finish a 2FA/CAPTCHA flow manually.",
      nullable: true,
    },
  },
  required: ["session", "cdpUrl"],
} as const;

export const SetStatusDtoSchema = {
  type: "object",
  properties: {
    status: {
      type: "string",
      enum: ["idle", "active", "needs_login", "expired", "stuck"],
    },
  },
  required: ["status"],
} as const;

export const OpenInternalSessionDtoSchema = {
  type: "object",
  properties: {
    accountKey: {
      type: "string",
      description:
        'Account identifier scoped to the calling user, e.g. "instagram:miybot" or "paypal:main". Must match /^[a-zA-Z0-9_:\\-]+$/ — anything else is rejected before it can touch the profile filesystem path.',
      example: "instagram:miybot",
    },
    loginUrl: {
      type: "string",
      description: `Page to navigate to in the pre-warmed Chrome. Drives what the VNC viewer renders when the user opens the returned vncUrl — set this to the service's login page (e.g. "https://www.instagram.com/accounts/login/"). Defaults to about:blank if omitted; the user can still type a URL in the address bar.`,
      example: "https://www.instagram.com/accounts/login/",
    },
    userId: {
      type: "string",
      description:
        "Owning user. Trusted only because the bridle key gates this endpoint — the runtime forwards ctx.from from the authenticated chat session.",
    },
  },
  required: ["accountKey", "userId"],
} as const;

export const InternalSetStatusDtoSchema = {
  type: "object",
  properties: {
    status: {
      type: "string",
      enum: ["idle", "active", "needs_login", "expired", "stuck"],
    },
    userId: {
      type: "string",
    },
  },
  required: ["status", "userId"],
} as const;

export const InternalSessionRefDtoSchema = {
  type: "object",
  properties: {
    userId: {
      type: "string",
    },
  },
  required: ["userId"],
} as const;

export const IssueExtensionTokenDtoSchema = {
  type: "object",
  properties: {
    agentId: {
      type: "string",
      description:
        "Agent the extension token will be scoped to. The token only allows writing state files under this agent's S3 prefix.",
    },
    userId: {
      type: "string",
      description:
        'User ID (within the agent context — typically the Telegram user ID for chat-driven agents, or "admin" for the admin agent). Used as the filename prefix so multiple humans can keep separate cookies inside one agent.',
    },
    ttlDays: {
      type: "number",
      description: "Token lifetime in days. Defaults to 30; max 365.",
      minimum: 1,
      maximum: 365,
    },
  },
  required: ["agentId", "userId"],
} as const;

export const IssueExtensionTokenResponseDtoSchema = {
  type: "object",
  properties: {
    token: {
      type: "string",
    },
    exp: {
      type: "number",
      description: "Unix seconds",
    },
  },
  required: ["token", "exp"],
} as const;

export const StorageStateCookieDtoSchema = {
  type: "object",
  properties: {
    name: {
      type: "string",
    },
    value: {
      type: "string",
    },
    domain: {
      type: "string",
      example: ".instagram.com",
    },
    path: {
      type: "string",
      example: "/",
    },
    expires: {
      type: "number",
      description: "Unix seconds, or -1 for session cookie",
    },
    httpOnly: {
      type: "boolean",
    },
    secure: {
      type: "boolean",
    },
    sameSite: {
      type: "string",
      enum: ["Strict", "Lax", "None"],
    },
  },
  required: [
    "name",
    "value",
    "domain",
    "path",
    "expires",
    "httpOnly",
    "secure",
    "sameSite",
  ],
} as const;

export const ImportStateDtoSchema = {
  type: "object",
  properties: {
    profile: {
      type: "string",
      description:
        "Profile name. Must match the value the agent will pass as `profile` to browser_play. Sanitized server-side before being used as a filename.",
      example: "instagram:miybot",
    },
    cookies: {
      description:
        "Cookies in Playwright storageState shape. Re-used 1:1 by the agent runtime when launching Chromium with { storageState: <file> }.",
      type: "array",
      items: {
        $ref: "#/components/schemas/StorageStateCookieDto",
      },
    },
    origins: {
      description:
        "Per-origin localStorage entries. The extension does not collect these today (would need a per-origin content script), but we accept them so future versions can fill them in without an API bump.",
      type: "array",
      items: {
        type: "string",
      },
    },
    userAgent: {
      type: "string",
      description:
        "User-Agent string of the browser the cookies were exported from. The agent runtime applies this to its Playwright context so Instagram/Facebook/banks see the SAME browser fingerprint as the one that issued the session — a mismatch (Mac Chrome → Linux HeadlessChrome) is the main reason replayed cookies still hit the login page.",
      maxLength: 512,
    },
  },
  required: ["profile", "cookies"],
} as const;

export const ImportStateResponseDtoSchema = {
  type: "object",
  properties: {
    ok: {
      type: "boolean",
    },
    path: {
      type: "string",
      description:
        "Relative path under the agent S3 prefix where the storageState was saved. The runtime sees this as `<agentDir>/<path>` after the next S3 sync tick.",
      example: "browser-state/55212224-instagram_miybot.json",
    },
    cookies: {
      type: "number",
    },
  },
  required: ["ok", "path", "cookies"],
} as const;

export const CatalogueItemDtoSchema = {
  type: "object",
  properties: {
    service: {
      type: "string",
      example: "instagram",
      description:
        "Stable service key. Use this in POST /integrations/accounts.",
    },
    title: {
      type: "string",
      example: "Instagram",
    },
    description: {
      type: "string",
    },
    iconUrl: {
      type: "string",
      example: "/icons/integrations/instagram.svg",
    },
    mechanism: {
      type: "string",
      enum: ["browser", "secret"],
    },
    loginUrl: {
      type: "string",
      description:
        "Browser-mechanism: URL the pool Chrome navigates to before the user opens the VNC view.",
    },
    accountKeyHint: {
      type: "string",
      description:
        "Browser-mechanism: hint text the UI shows under the accountKey input.",
    },
    domains: {
      description:
        "Browser-mechanism: domains the Chrome extension auto-matches the current tab against (suffix match).",
      type: "array",
      items: {
        type: "string",
      },
    },
    secretEnvKey: {
      type: "string",
      description:
        "Secret-mechanism: env var name the runtime exposes to agents.",
    },
    secretHelp: {
      type: "string",
      description:
        "Secret-mechanism: short help string the UI shows under the secret input.",
    },
  },
  required: ["service", "title", "description", "iconUrl", "mechanism"],
} as const;

export const IntegrationAccountDtoSchema = {
  type: "object",
  properties: {
    id: {
      type: "string",
    },
    userId: {
      type: "string",
    },
    service: {
      type: "string",
      example: "instagram",
    },
    accountKey: {
      type: "string",
      example: "miybot",
      description:
        "Account label scoped to (userId, service). For browser-mechanism this is also the BrowserSession.accountKey suffix.",
    },
    mechanism: {
      type: "string",
      enum: ["browser", "secret"],
    },
    label: {
      type: "object",
    },
    status: {
      type: "string",
      enum: ["pending", "connected", "needs_login", "revoked"],
      description:
        "pending: row exists but underlying credential not yet stored. connected: credential ready. needs_login: cookies expired or session lost. revoked: user disconnected.",
    },
    createdAt: {
      format: "date-time",
      type: "string",
    },
    updatedAt: {
      format: "date-time",
      type: "string",
    },
  },
  required: [
    "id",
    "userId",
    "service",
    "accountKey",
    "mechanism",
    "status",
    "createdAt",
    "updatedAt",
  ],
} as const;

export const ConnectIntegrationDtoSchema = {
  type: "object",
  properties: {
    service: {
      type: "string",
      example: "instagram",
      description: "Catalogue key (see GET /integrations/catalogue).",
    },
    accountKey: {
      type: "string",
      example: "miybot",
      description:
        "User-chosen label for this account. Becomes part of BrowserSession.accountKey for browser-mechanism services. Same charset rules as browser sessions.",
    },
    label: {
      type: "string",
      description: "Human-friendly label shown in the admin UI list.",
      maxLength: 120,
    },
  },
  required: ["service", "accountKey"],
} as const;

export const LoginInstructionDtoSchema = {
  type: "object",
  properties: {
    accountId: {
      type: "string",
      description: "IntegrationAccount.id these instructions are for.",
    },
    siteUrl: {
      type: "string",
      description:
        "Direct link to the service login page (catalogue.loginUrl) — the user opens this in their normal browser.",
    },
    helpUrl: {
      type: "string",
      description:
        "Admin-UI route that walks the user through the connect flow (install extension if needed, log in on siteUrl, send cookies).",
    },
    instructions: {
      type: "string",
      description:
        "Plain-text instructions the agent can paraphrase for chat channels where helpUrl is not directly clickable. Three short lines.",
    },
  },
  required: ["accountId", "siteUrl", "helpUrl", "instructions"],
} as const;

export const ImportCookiesCookieDtoSchema = {
  type: "object",
  properties: {
    name: {
      type: "string",
    },
    value: {
      type: "string",
    },
    domain: {
      type: "string",
      example: ".instagram.com",
    },
    path: {
      type: "string",
      example: "/",
    },
    expires: {
      type: "number",
      description: "Unix seconds, or -1 for session cookie",
    },
    httpOnly: {
      type: "boolean",
    },
    secure: {
      type: "boolean",
    },
    sameSite: {
      type: "string",
      enum: ["Strict", "Lax", "None"],
    },
  },
  required: [
    "name",
    "value",
    "domain",
    "path",
    "expires",
    "httpOnly",
    "secure",
    "sameSite",
  ],
} as const;

export const ImportCookiesDtoSchema = {
  type: "object",
  properties: {
    cookies: {
      description:
        "Cookies in Playwright storageState shape. Either harvested by the Ranch extension or pasted from any third-party cookie-exporter (Cookie-Editor, EditThisCookie, etc.).",
      type: "array",
      items: {
        $ref: "#/components/schemas/ImportCookiesCookieDto",
      },
    },
    origins: {
      description:
        "Per-origin localStorage entries. Most extensions do not collect these — accepted optionally for future-proofing.",
      type: "array",
      items: {
        type: "string",
      },
    },
    userAgent: {
      type: "string",
      description:
        "User-Agent of the browser that issued the cookies. CRITICAL — Instagram/Meta invalidate sessions whose UA shifts between captures and replays. The runtime applies this verbatim to its Playwright context.",
      maxLength: 512,
    },
  },
  required: ["cookies"],
} as const;

export const SaveSecretDtoSchema = {
  type: "object",
  properties: {
    value: {
      type: "string",
      description:
        "Raw credential value (API key, token, etc.). Stored in the per-user secret store under a key derived from (service, accountKey). Never echoed back through the API once written.",
      maxLength: 4096,
    },
  },
  required: ["value"],
} as const;

export const ResolvedSecretsDtoSchema = {
  type: "object",
  properties: {
    env: {
      type: "object",
      description:
        "Map of env-var name → secret value, ready for the runtime to merge into an agent process env. Empty object if the user has no matching secret-mechanism integrations.",
      additionalProperties: {
        type: "string",
      },
      example: {
        OPENAI_API_KEY: "sk-…",
        GITHUB_TOKEN: "ghp_…",
      },
    },
  },
  required: ["env"],
} as const;

export const RuntimeAccountDtoSchema = {
  type: "object",
  properties: {
    service: {
      type: "string",
      example: "x",
    },
    accountKey: {
      type: "string",
      example: "dimzhuk",
    },
    profile: {
      type: "string",
      example: "x:dimzhuk",
      description:
        "Exact value to pass as `profile` to browser_play (browser-mechanism only).",
    },
    mechanism: {
      type: "string",
      enum: ["browser", "secret"],
    },
    status: {
      type: "string",
      enum: ["pending", "connected", "needs_login", "revoked"],
    },
  },
  required: ["service", "accountKey", "profile", "mechanism", "status"],
} as const;

export const ListAccountsResponseDtoSchema = {
  type: "object",
  properties: {
    accounts: {
      type: "array",
      items: {
        $ref: "#/components/schemas/RuntimeAccountDto",
      },
    },
  },
  required: ["accounts"],
} as const;

export const RequestLoginBodyDtoSchema = {
  type: "object",
  properties: {
    service: {
      type: "string",
      description:
        "Catalogue service key the agent wants login instructions for.",
    },
    accountKey: {
      type: "string",
      description:
        "AccountKey on this integration. Runtime derives it from the `<service>:<accountKey>` profile string the tool was called with.",
    },
  },
  required: ["service", "accountKey"],
} as const;

export const IssueIntegrationExtensionTokenDtoSchema = {
  type: "object",
  properties: {
    ttlDays: {
      type: "number",
      description: "Token lifetime in days. Defaults to 30; max 365.",
      minimum: 1,
      maximum: 365,
    },
  },
} as const;

export const IssueIntegrationExtensionTokenResponseDtoSchema = {
  type: "object",
  properties: {
    token: {
      type: "string",
    },
    exp: {
      type: "number",
      description: "Unix seconds",
    },
  },
  required: ["token", "exp"],
} as const;

export const ExtensionImportStateDtoSchema = {
  type: "object",
  properties: {
    cookies: {
      description:
        "Cookies in Playwright storageState shape. Either harvested by the Ranch extension or pasted from any third-party cookie-exporter (Cookie-Editor, EditThisCookie, etc.).",
      type: "array",
      items: {
        $ref: "#/components/schemas/ImportCookiesCookieDto",
      },
    },
    origins: {
      description:
        "Per-origin localStorage entries. Most extensions do not collect these — accepted optionally for future-proofing.",
      type: "array",
      items: {
        type: "string",
      },
    },
    userAgent: {
      type: "string",
      description:
        "User-Agent of the browser that issued the cookies. CRITICAL — Instagram/Meta invalidate sessions whose UA shifts between captures and replays. The runtime applies this verbatim to its Playwright context.",
      maxLength: 512,
    },
    service: {
      type: "string",
      example: "instagram",
      description:
        "Catalogue service key (auto-detected by the extension from the current tab URL via catalogue.domains).",
    },
    accountKey: {
      type: "string",
      example: "miybot",
      description:
        "User-chosen accountKey for this integration. Same charset as POST /integrations/accounts.",
    },
  },
  required: ["cookies", "service", "accountKey"],
} as const;

export const ExtensionImportStateResponseDtoSchema = {
  type: "object",
  properties: {
    ok: {
      type: "boolean",
    },
    accountId: {
      type: "string",
      description: "IntegrationAccount id (created or reused).",
    },
    service: {
      type: "string",
    },
    accountKey: {
      type: "string",
    },
    cookies: {
      type: "number",
    },
  },
  required: ["ok", "accountId", "service", "accountKey", "cookies"],
} as const;
