// This file is auto-generated by @hey-api/openapi-ts

import {
  type Options as ClientOptions,
  type TDataShape,
  type Client,
  formDataBodySerializer,
} from "@hey-api/client-axios";
import type {
  HealthControllerCheckData,
  InitControllerStatusData,
  InitControllerInitData,
  SettingControllerFindAllData,
  SettingControllerFindByGroupData,
  SettingControllerRemoveData,
  SettingControllerFindByKeyData,
  SettingControllerUpsertData,
  LlmControllerFindAllData,
  LlmControllerCreateData,
  LlmControllerRemoveData,
  LlmControllerFindByIdData,
  LlmControllerUpdateData,
  HealthCheckLlmCredentialData,
  HealthCheckLlmCredentialResponse,
  TemplateControllerFindAllData,
  TemplateControllerCreateData,
  TemplateControllerRemoveData,
  TemplateControllerFindByIdData,
  TemplateControllerUpdateData,
  TemplateControllerSetSkillsData,
  TemplateControllerSetMcpsData,
  McpServerControllerFindAllData,
  McpServerControllerCreateData,
  McpServerControllerRemoveData,
  McpServerControllerFindByIdData,
  McpServerControllerUpdateData,
  AuthControllerLoginData,
  AuthControllerRegisterData,
  AuthControllerMeData,
  AuthControllerEmbedTokenData,
  ApiKeyControllerFindAllData,
  ApiKeyControllerCreateData,
  ApiKeyControllerRemoveData,
  ApiKeyControllerRemoveResponse,
  GetKnowledgesData,
  CreateKnowledgeData,
  GetKnowledgeStatusData,
  GetGraphLabelsData,
  GetGraphData,
  GetGraphResponse,
  DeleteKnowledgeData,
  DeleteKnowledgeResponse,
  GetKnowledgeData,
  UpdateKnowledgeData,
  IndexKnowledgeData,
  QueryKnowledgeData,
  QueryKnowledgeResponse,
  GetKnowledgeSourcesData,
  AddKnowledgeSourceData,
  AddKnowledgeSourcesFromSitemapData,
  AddKnowledgeSourcesFromSitemapResponse,
  AddKnowledgeSourcesFromArchiveData,
  AddKnowledgeSourcesFromArchiveResponse,
  DeleteKnowledgeSourceData,
  DeleteKnowledgeSourceResponse,
  AgentControllerFindAllData,
  AgentControllerCreateData,
  AgentControllerFindPublicData,
  AgentControllerStatusData,
  AgentControllerStatusResponse,
  AgentControllerStatusStreamData,
  AgentControllerRemoveData,
  AgentControllerFindByIdData,
  AgentControllerUpdateData,
  GetAgentMetricsData,
  GetAgentMetricsResponse,
  GetAgentEnvData,
  GetAgentEnvResponse,
  GetAgentMcpsData,
  GetAgentMcpsResponse,
  AgentControllerFindAdminData,
  AgentControllerDemoteAdminData,
  AgentControllerPromoteAdminData,
  AgentControllerRestartData,
  AgentControllerStopData,
  AgentControllerStartData,
  RestartByTemplateData,
  FileControllerListData,
  FileControllerDeleteData,
  FileControllerDeleteResponse,
  FileControllerReadData,
  FileControllerReadResponse,
  FileControllerSaveData,
  FileControllerSyncData,
  ExportAgentFilesData,
  SendBridleMessageData,
  SendBridleMessageSyncData,
  BridleHealthData,
  BridleHealthResponse,
  BridleAgentHealthData,
  BridleAgentHealthResponse,
  ListAgentsData,
  ResetBridleTranscriptData,
  ResetBridleTranscriptResponse,
  GetBridleTranscriptData,
  GetBridleTranscriptResponse,
  ArchiveBridleTranscriptData,
  SkillControllerFindAllData,
  SkillControllerCreateData,
  SkillControllerListSourcesData,
  SkillControllerSearchData,
  SkillControllerImportFromUrlData,
  SkillControllerImportFromGithubData,
  SkillControllerRemoveData,
  SkillControllerFindByIdData,
  SkillControllerUpdateData,
  FindDependentAgentsData,
  GetChatsData,
  GetChatsResponse,
  GetChatData,
  GetChatResponse,
  GetChatMessagesData,
  GetChatMessagesResponse,
  SyncChatsData,
  SyncChatsResponse,
  SummarizeChatData,
  SummarizeChatResponse,
  GetMyChatFeedbackData,
  GetMyChatFeedbackResponse,
  CreateChatFeedbackData,
  CreateChatFeedbackResponse,
  DeleteChatFeedbackData,
  DeleteChatFeedbackResponse,
  ExportChatData,
  GetMyChatsData,
  GetMyChatsResponse,
  GetMyChatData,
  GetMyChatResponse,
  GetMyChatMessagesData,
  GetMyChatMessagesResponse,
  SyncMyChatsData,
  SyncMyChatsResponse,
  ListMyChatFeedbackData,
  ListMyChatFeedbackResponse,
  CreateMyChatFeedbackData,
  CreateMyChatFeedbackResponse,
  DeleteMyChatFeedbackData,
  DeleteMyChatFeedbackResponse,
  ExportMyChatData,
  GetAgentChannelsData,
  GetAgentChannelsResponse,
  SetAgentChannelsData,
  SetAgentChannelsResponse,
  UserControllerFindAllData,
  UserControllerCreateData,
  UserControllerRemoveData,
  UserControllerFindByIdData,
  UserControllerUpdateData,
  UserControllerUpdateRoleData,
  TemplateFileControllerListData,
  TemplateFileControllerReadData,
  TemplateFileControllerSaveData,
  TemplateFileControllerUploadData,
  PreviewTemplateInstallData,
  PreviewTemplateInstallResponse,
  InstallTemplateData,
  InstallTemplateResponse,
  PreviewTemplateInstallFromGitData,
  PreviewTemplateInstallFromGitResponse,
  InstallTemplateFromGitData,
  InstallTemplateFromGitResponse,
  DownloadTemplateData,
  PaddockScenarioControllerFindAllData,
  PaddockScenarioControllerCreateData,
  PaddockScenarioControllerRemoveData,
  PaddockScenarioControllerFindByIdData,
  PaddockScenarioControllerUpdateData,
  PaddockScenarioControllerGenerateData,
  SecretControllerDeleteData,
  SecretControllerDeleteResponse,
  SecretControllerListData,
  SecretControllerListResponse,
  SecretControllerSetData,
  SecretControllerSetResponse,
  SecretControllerReplaceData,
  SecretControllerReplaceResponse,
  LogControllerGetLogsData,
  UsageControllerFindForAgentData,
  UsageControllerReportData,
  UsageControllerReportResponse,
  UsageControllerFindForCredentialData,
  RancherControllerStatusData,
  RancherControllerEnsureTemplateData,
  UpgradeControllerStatusData,
  UpgradeControllerRunData,
  PaddockEvaluationControllerListData,
  PaddockEvaluationControllerStartData,
  PaddockEvaluationControllerGetData,
  PaddockEvaluationControllerReportData,
  PaddockEvaluationControllerLogsData,
  PaddockEvaluationControllerScenarioData,
  PaddockEvaluationControllerTraceData,
  PaddockEvaluationControllerAbortData,
  PaddockEvaluationControllerRerunData,
  ListBrowserSessionsData,
  ListBrowserSessionsResponse,
  OpenBrowserSessionData,
  OpenBrowserSessionResponse,
  DeleteBrowserSessionData,
  DeleteBrowserSessionResponse,
  GetBrowserSessionData,
  GetBrowserSessionResponse,
  ResetBrowserSessionData,
  ResetBrowserSessionResponse,
  SetBrowserSessionStatusData,
  SetBrowserSessionStatusResponse,
  MintBrowserSessionVncUrlData,
  OpenBrowserSessionInternalData,
  SetBrowserSessionStatusInternalData,
  ResetBrowserSessionInternalData,
  HarvestBrowserSessionInternalData,
  CleanupBrowserSessionsInternalData,
  IssueBrowserExtensionTokenData,
  IssueBrowserExtensionTokenResponse,
  ImportBrowserStorageStateData,
  ImportBrowserStorageStateResponse,
  ListIntegrationCatalogueData,
  ListIntegrationCatalogueResponse,
  ListIntegrationAccountsData,
  ListIntegrationAccountsResponse,
  ConnectIntegrationData,
  ConnectIntegrationResponse,
  DisconnectIntegrationData,
  DisconnectIntegrationResponse,
  GetIntegrationAccountData,
  GetIntegrationAccountResponse,
  OpenIntegrationLoginData,
  OpenIntegrationLoginResponse,
  ImportIntegrationCookiesData,
  ImportIntegrationCookiesResponse,
  SaveIntegrationSecretData,
  SaveIntegrationSecretResponse,
  ResolveIntegrationSecretsData,
  ResolveIntegrationSecretsResponse,
  ListIntegrationAccountsForRuntimeData,
  ListIntegrationAccountsForRuntimeResponse,
  RequestIntegrationLoginData,
  RequestIntegrationLoginResponse,
  ResolveIntegrationBrowserStateData,
  IssueIntegrationExtensionTokenData,
  IssueIntegrationExtensionTokenResponse,
  ImportIntegrationExtensionStateData,
  ImportIntegrationExtensionStateResponse,
  DownloadIntegrationExtensionData,
  SseControllerSseData,
  SseControllerMessagesData,
  SseControllerDebugSessionsData,
  StreamableHttpControllerHandleDeleteRequestData,
  StreamableHttpControllerHandleGetRequestData,
  StreamableHttpControllerHandlePostRequestData,
} from "./types.gen";
import { client as _heyApiClient } from "./client.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export class HealthService {
  public static healthControllerCheck<ThrowOnError extends boolean = false>(
    options?: Options<HealthControllerCheckData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/health",
      ...options,
    });
  }
}

export class SetupService {
  /**
   * Check whether the system needs initial owner setup
   */
  public static initControllerStatus<ThrowOnError extends boolean = false>(
    options?: Options<InitControllerStatusData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/setup/status",
      ...options,
    });
  }

  /**
   * Create the first owner. Fails if one already exists.
   */
  public static initControllerInit<ThrowOnError extends boolean = false>(
    options: Options<InitControllerInitData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/setup/init",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }
}

export class SettingsService {
  /**
   * List all settings
   */
  public static settingControllerFindAll<ThrowOnError extends boolean = false>(
    options?: Options<SettingControllerFindAllData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/settings",
      ...options,
    });
  }

  /**
   * List settings in a group
   */
  public static settingControllerFindByGroup<
    ThrowOnError extends boolean = false,
  >(options: Options<SettingControllerFindByGroupData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/settings/{group}",
      ...options,
    });
  }

  /**
   * Delete a setting
   */
  public static settingControllerRemove<ThrowOnError extends boolean = false>(
    options: Options<SettingControllerRemoveData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).delete<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/settings/{group}/{name}",
      ...options,
    });
  }

  /**
   * Get a single setting by group/name
   */
  public static settingControllerFindByKey<
    ThrowOnError extends boolean = false,
  >(options: Options<SettingControllerFindByKeyData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/settings/{group}/{name}",
      ...options,
    });
  }

  /**
   * Create or replace a setting
   */
  public static settingControllerUpsert<ThrowOnError extends boolean = false>(
    options: Options<SettingControllerUpsertData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).put<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/settings/{group}/{name}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }
}

export class LlmsService {
  /**
   * List all LLM credentials
   */
  public static llmControllerFindAll<ThrowOnError extends boolean = false>(
    options?: Options<LlmControllerFindAllData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/llms",
      ...options,
    });
  }

  /**
   * Create a new LLM credential
   */
  public static llmControllerCreate<ThrowOnError extends boolean = false>(
    options: Options<LlmControllerCreateData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/llms",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Delete an LLM credential
   */
  public static llmControllerRemove<ThrowOnError extends boolean = false>(
    options: Options<LlmControllerRemoveData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).delete<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/llms/{id}",
      ...options,
    });
  }

  /**
   * Get LLM credential by ID
   */
  public static llmControllerFindById<ThrowOnError extends boolean = false>(
    options: Options<LlmControllerFindByIdData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/llms/{id}",
      ...options,
    });
  }

  /**
   * Update an LLM credential
   */
  public static llmControllerUpdate<ThrowOnError extends boolean = false>(
    options: Options<LlmControllerUpdateData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).put<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/llms/{id}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Health-check an LLM credential
   */
  public static healthCheckLlmCredential<ThrowOnError extends boolean = false>(
    options: Options<HealthCheckLlmCredentialData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      HealthCheckLlmCredentialResponse,
      unknown,
      ThrowOnError
    >({
      url: "/llms/{id}/health-check",
      ...options,
    });
  }
}

export class TemplatesService {
  /**
   * List all agent templates
   */
  public static templateControllerFindAll<ThrowOnError extends boolean = false>(
    options?: Options<TemplateControllerFindAllData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/templates",
      ...options,
    });
  }

  /**
   * Create a new agent template
   */
  public static templateControllerCreate<ThrowOnError extends boolean = false>(
    options: Options<TemplateControllerCreateData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/templates",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Delete a template
   */
  public static templateControllerRemove<ThrowOnError extends boolean = false>(
    options: Options<TemplateControllerRemoveData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).delete<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/templates/{id}",
      ...options,
    });
  }

  /**
   * Get template by ID
   */
  public static templateControllerFindById<
    ThrowOnError extends boolean = false,
  >(options: Options<TemplateControllerFindByIdData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/templates/{id}",
      ...options,
    });
  }

  /**
   * Update a template
   */
  public static templateControllerUpdate<ThrowOnError extends boolean = false>(
    options: Options<TemplateControllerUpdateData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).put<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/templates/{id}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Replace the skill set attached to a template. Body lists the full desired set; omitted IDs are detached.
   */
  public static templateControllerSetSkills<
    ThrowOnError extends boolean = false,
  >(options: Options<TemplateControllerSetSkillsData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).put<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/templates/{id}/skills",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Replace the MCP servers attached to a template. Body lists the full desired set; omitted IDs are detached. Agents created from this template inherit these MCPs at deploy time.
   */
  public static templateControllerSetMcps<ThrowOnError extends boolean = false>(
    options: Options<TemplateControllerSetMcpsData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).put<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/templates/{id}/mcps",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Preview template install — parse manifest and report what would happen, no DB or S3 writes.
   */
  public static previewTemplateInstall<ThrowOnError extends boolean = false>(
    options: Options<PreviewTemplateInstallData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      PreviewTemplateInstallResponse,
      unknown,
      ThrowOnError
    >({
      ...formDataBodySerializer,
      url: "/templates/install/preview",
      ...options,
      headers: {
        "Content-Type": null,
        ...options?.headers,
      },
    });
  }

  /**
   * Install a template from a zip archive.
   */
  public static installTemplate<ThrowOnError extends boolean = false>(
    options: Options<InstallTemplateData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      InstallTemplateResponse,
      unknown,
      ThrowOnError
    >({
      ...formDataBodySerializer,
      url: "/templates/install",
      ...options,
      headers: {
        "Content-Type": null,
        ...options?.headers,
      },
    });
  }

  /**
   * Preview template install from a git repository — clones into /tmp, parses manifest, reports what would happen, no DB or S3 writes.
   */
  public static previewTemplateInstallFromGit<
    ThrowOnError extends boolean = false,
  >(options: Options<PreviewTemplateInstallFromGitData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).post<
      PreviewTemplateInstallFromGitResponse,
      unknown,
      ThrowOnError
    >({
      url: "/templates/install/from-git/preview",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Install a template from a git repository.
   */
  public static installTemplateFromGit<ThrowOnError extends boolean = false>(
    options: Options<InstallTemplateFromGitData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      InstallTemplateFromGitResponse,
      unknown,
      ThrowOnError
    >({
      url: "/templates/install/from-git",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Download a template as a zip — round-trips template.yaml, .agent*, .paddock/config.json, and .paddock/scenarios* back into an installable bundle.
   */
  public static downloadTemplate<ThrowOnError extends boolean = false>(
    options: Options<DownloadTemplateData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/templates/{id}/download",
      ...options,
    });
  }
}

export class McpServersService {
  /**
   * List all MCP servers registered in this Ranch.
   */
  public static mcpServerControllerFindAll<
    ThrowOnError extends boolean = false,
  >(options?: Options<McpServerControllerFindAllData, ThrowOnError>) {
    return (options?.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/mcp-servers",
      ...options,
    });
  }

  /**
   * Register a new MCP server.
   */
  public static mcpServerControllerCreate<ThrowOnError extends boolean = false>(
    options: Options<McpServerControllerCreateData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/mcp-servers",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Delete an MCP server. Built-in entries (e.g. the Ranch MCP itself) cannot be deleted — only disabled.
   */
  public static mcpServerControllerRemove<ThrowOnError extends boolean = false>(
    options: Options<McpServerControllerRemoveData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).delete<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/mcp-servers/{id}",
      ...options,
    });
  }

  /**
   * Get an MCP server by id.
   */
  public static mcpServerControllerFindById<
    ThrowOnError extends boolean = false,
  >(options: Options<McpServerControllerFindByIdData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/mcp-servers/{id}",
      ...options,
    });
  }

  /**
   * Update an MCP server.
   */
  public static mcpServerControllerUpdate<ThrowOnError extends boolean = false>(
    options: Options<McpServerControllerUpdateData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).patch<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/mcp-servers/{id}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }
}

export class AuthService {
  /**
   * Authenticate and receive an access token
   */
  public static authControllerLogin<ThrowOnError extends boolean = false>(
    options: Options<AuthControllerLoginData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/auth/login",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Self-service signup. Requires the 'auth.registration_enabled' setting to be true; otherwise 403.
   */
  public static authControllerRegister<ThrowOnError extends boolean = false>(
    options: Options<AuthControllerRegisterData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/auth/register",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Get the current authenticated user
   */
  public static authControllerMe<ThrowOnError extends boolean = false>(
    options?: Options<AuthControllerMeData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/auth/me",
      ...options,
    });
  }

  /**
   * Mint a short-lived browser embed JWT for the bridle widget. Auth: API key with embed:mint scope. Owner/Admin roles are stripped from the result unless the key also carries embed:mint-admin — then they are kept and the TTL is capped at 7d.
   */
  public static authControllerEmbedToken<ThrowOnError extends boolean = false>(
    options: Options<AuthControllerEmbedTokenData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/auth/embed/token",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }
}

export class ApiKeysService {
  /**
   * List all API keys
   */
  public static apiKeyControllerFindAll<ThrowOnError extends boolean = false>(
    options?: Options<ApiKeyControllerFindAllData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/api-keys",
      ...options,
    });
  }

  /**
   * Create a new API key. The plaintext key is returned exactly once — only its hash is persisted.
   */
  public static apiKeyControllerCreate<ThrowOnError extends boolean = false>(
    options: Options<ApiKeyControllerCreateData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/api-keys",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Revoke (delete) an API key.
   */
  public static apiKeyControllerRemove<ThrowOnError extends boolean = false>(
    options: Options<ApiKeyControllerRemoveData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).delete<
      ApiKeyControllerRemoveResponse,
      unknown,
      ThrowOnError
    >({
      url: "/api-keys/{id}",
      ...options,
    });
  }
}

export class KnowledgesService {
  /**
   * List knowledges
   */
  public static getKnowledges<ThrowOnError extends boolean = false>(
    options?: Options<GetKnowledgesData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/knowledges",
      ...options,
    });
  }

  /**
   * Create knowledge
   */
  public static createKnowledge<ThrowOnError extends boolean = false>(
    options: Options<CreateKnowledgeData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/knowledges",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Knowledge service availability and setup readiness
   */
  public static getKnowledgeStatus<ThrowOnError extends boolean = false>(
    options?: Options<GetKnowledgeStatusData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/knowledges/status",
      ...options,
    });
  }

  /**
   * List graph entity labels
   */
  public static getGraphLabels<ThrowOnError extends boolean = false>(
    options?: Options<GetGraphLabelsData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/knowledges/graph/labels",
      ...options,
    });
  }

  /**
   * Get knowledge graph
   */
  public static getGraph<ThrowOnError extends boolean = false>(
    options: Options<GetGraphData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      GetGraphResponse,
      unknown,
      ThrowOnError
    >({
      url: "/knowledges/graph",
      ...options,
    });
  }

  /**
   * Delete knowledge
   */
  public static deleteKnowledge<ThrowOnError extends boolean = false>(
    options: Options<DeleteKnowledgeData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).delete<
      DeleteKnowledgeResponse,
      unknown,
      ThrowOnError
    >({
      url: "/knowledges/{id}",
      ...options,
    });
  }

  /**
   * Get one knowledge
   */
  public static getKnowledge<ThrowOnError extends boolean = false>(
    options: Options<GetKnowledgeData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/knowledges/{id}",
      ...options,
    });
  }

  /**
   * Update knowledge
   */
  public static updateKnowledge<ThrowOnError extends boolean = false>(
    options: Options<UpdateKnowledgeData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).put<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/knowledges/{id}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Start indexing
   */
  public static indexKnowledge<ThrowOnError extends boolean = false>(
    options: Options<IndexKnowledgeData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/knowledges/{id}/index",
      ...options,
    });
  }

  /**
   * Query knowledge (LLM-generated answer)
   */
  public static queryKnowledge<ThrowOnError extends boolean = false>(
    options: Options<QueryKnowledgeData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      QueryKnowledgeResponse,
      unknown,
      ThrowOnError
    >({
      url: "/knowledges/{id}/query",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }
}

export class KnowledgeSourcesService {
  /**
   * List sources
   */
  public static getKnowledgeSources<ThrowOnError extends boolean = false>(
    options: Options<GetKnowledgeSourcesData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/knowledges/{knowledgeId}/sources",
      ...options,
    });
  }

  /**
   * Add source (file|url|text)
   */
  public static addKnowledgeSource<ThrowOnError extends boolean = false>(
    options: Options<AddKnowledgeSourceData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      unknown,
      unknown,
      ThrowOnError
    >({
      ...formDataBodySerializer,
      url: "/knowledges/{knowledgeId}/sources",
      ...options,
      headers: {
        "Content-Type": null,
        ...options?.headers,
      },
    });
  }

  /**
   * Add url sources from a sitemap
   * Fetches a sitemap.xml (or sitemap-index), filters by optional URL prefix, then creates one url-type source per discovered page. Indexing into LightRAG happens through the normal reindex flow.
   */
  public static addKnowledgeSourcesFromSitemap<
    ThrowOnError extends boolean = false,
  >(options: Options<AddKnowledgeSourcesFromSitemapData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).post<
      AddKnowledgeSourcesFromSitemapResponse,
      unknown,
      ThrowOnError
    >({
      url: "/knowledges/{knowledgeId}/sources/from-sitemap",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Bulk-import sources from a zip archive
   * Accepts a .zip, extracts every ingestable file (pdf, docx, xlsx, txt, html, ...), and creates one file-type source per entry. Upload runs in the background and streams each entry to S3; the response returns immediately with the detected file count. Indexing into LightRAG happens through the normal reindex flow.
   */
  public static addKnowledgeSourcesFromArchive<
    ThrowOnError extends boolean = false,
  >(options: Options<AddKnowledgeSourcesFromArchiveData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).post<
      AddKnowledgeSourcesFromArchiveResponse,
      unknown,
      ThrowOnError
    >({
      url: "/knowledges/{knowledgeId}/sources/from-archive",
      ...options,
    });
  }

  /**
   * Delete source
   */
  public static deleteKnowledgeSource<ThrowOnError extends boolean = false>(
    options: Options<DeleteKnowledgeSourceData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).delete<
      DeleteKnowledgeSourceResponse,
      unknown,
      ThrowOnError
    >({
      url: "/knowledges/{knowledgeId}/sources/{sourceId}",
      ...options,
    });
  }
}

export class AgentsService {
  /**
   * List all agents. Public — landing/chat pages render without auth. Mutations and details still require login.
   */
  public static agentControllerFindAll<ThrowOnError extends boolean = false>(
    options?: Options<AgentControllerFindAllData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/agents",
      ...options,
    });
  }

  /**
   * Create and deploy a new agent. Admin or Owner.
   */
  public static agentControllerCreate<ThrowOnError extends boolean = false>(
    options: Options<AgentControllerCreateData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/agents",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * List agents flagged as public. Used by the marketing landing page so private agents stay hidden from unauthenticated visitors.
   */
  public static agentControllerFindPublic<ThrowOnError extends boolean = false>(
    options?: Options<AgentControllerFindPublicData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/agents/public",
      ...options,
    });
  }

  /**
   * Snapshot of all agents joined with live pod status. Public.
   */
  public static agentControllerStatus<ThrowOnError extends boolean = false>(
    options?: Options<AgentControllerStatusData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      AgentControllerStatusResponse,
      unknown,
      ThrowOnError
    >({
      url: "/agents/status",
      ...options,
    });
  }

  /**
   * Live SSE stream of agent pod state changes. Public — EventSource cannot send Authorization headers.
   */
  public static agentControllerStatusStream<
    ThrowOnError extends boolean = false,
  >(options?: Options<AgentControllerStatusStreamData, ThrowOnError>) {
    return (options?.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/agents/status/stream",
      ...options,
    });
  }

  /**
   * Stop and delete an agent. Pass `?wipeS3=true` to also drop every object under `agents/{id}/` — opt-in so accidental deletes don’t nuke files. Admin or Owner.
   */
  public static agentControllerRemove<ThrowOnError extends boolean = false>(
    options: Options<AgentControllerRemoveData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).delete<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/agents/{id}",
      ...options,
    });
  }

  /**
   * Get agent by ID. Public — chat needs agent metadata (name, status) to render.
   */
  public static agentControllerFindById<ThrowOnError extends boolean = false>(
    options: Options<AgentControllerFindByIdData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/agents/{id}",
      ...options,
    });
  }

  /**
   * Update agent configuration. Admin or Owner.
   */
  public static agentControllerUpdate<ThrowOnError extends boolean = false>(
    options: Options<AgentControllerUpdateData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).put<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/agents/{id}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Live resource usage for the agent: pod CPU/memory (from metrics-server) and free disk space on the K8s node hosting the pod (from kubelet stats/summary). Returns null while no pod exists yet.
   */
  public static getAgentMetrics<ThrowOnError extends boolean = false>(
    options: Options<GetAgentMetricsData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      GetAgentMetricsResponse,
      unknown,
      ThrowOnError
    >({
      url: "/agents/{id}/metrics",
      ...options,
    });
  }

  /**
   * Env vars the agent pod receives on its next deploy. Built from the same code as the real pod manifest — the source of truth, never a hand-maintained copy. The UI masks secret values for display.
   */
  public static getAgentEnv<ThrowOnError extends boolean = false>(
    options: Options<GetAgentEnvData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      GetAgentEnvResponse,
      unknown,
      ThrowOnError
    >({
      url: "/agents/{id}/env",
      ...options,
    });
  }

  /**
   * List of MCP servers this agent should connect to at runtime. Resolves the agent's template and returns its enabled MCP attachments. Called by the runtime on boot to populate its tool registry. Tokens with role=Agent (issued to runtimes) can only read their OWN agent — `sub` must match `agent:<id>`.
   */
  public static getAgentMcps<ThrowOnError extends boolean = false>(
    options: Options<GetAgentMcpsData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      GetAgentMcpsResponse,
      unknown,
      ThrowOnError
    >({
      url: "/agents/{id}/mcps",
      ...options,
    });
  }

  /**
   * Get the agent currently flagged as Ranch admin (or null).
   */
  public static agentControllerFindAdmin<ThrowOnError extends boolean = false>(
    options?: Options<AgentControllerFindAdminData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/agents/admin/current",
      ...options,
    });
  }

  /**
   * Demote this agent from Ranch admin. Redeploys without RANCH_ADMIN.
   */
  public static agentControllerDemoteAdmin<
    ThrowOnError extends boolean = false,
  >(options: Options<AgentControllerDemoteAdminData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).delete<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/agents/{id}/promote-admin",
      ...options,
    });
  }

  /**
   * Mark this agent as the Ranch admin. Clears the flag from any other agent (single-admin invariant) and redeploys with RANCH_ADMIN=true + a service token. Any previous admin is redeployed without the flag.
   */
  public static agentControllerPromoteAdmin<
    ThrowOnError extends boolean = false,
  >(options: Options<AgentControllerPromoteAdminData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).post<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/agents/{id}/promote-admin",
      ...options,
    });
  }

  /**
   * Restart an agent. Admin or Owner.
   */
  public static agentControllerRestart<ThrowOnError extends boolean = false>(
    options: Options<AgentControllerRestartData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/agents/{id}/restart",
      ...options,
    });
  }

  /**
   * Stop an agent without deleting it: cancels its workflow and deletes its pod to free cluster CPU/memory, then marks it `stopped`. Use this to free a slot so another agent can start. Bring it back with POST :id/start. Admin or Owner.
   */
  public static agentControllerStop<ThrowOnError extends boolean = false>(
    options: Options<AgentControllerStopData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/agents/{id}/stop",
      ...options,
    });
  }

  /**
   * Start a stopped agent: deploys a fresh pod and reattaches the runtime. Inverse of POST :id/stop. Admin or Owner.
   */
  public static agentControllerStart<ThrowOnError extends boolean = false>(
    options: Options<AgentControllerStartData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/agents/{id}/start",
      ...options,
    });
  }

  /**
   * Restart every agent that uses this template. Pulls latest template-owned files into each agent and redeploys, preserving runtime state. Concurrency capped at 5 to avoid overwhelming the cluster. Admin or Owner.
   */
  public static restartByTemplate<ThrowOnError extends boolean = false>(
    options: Options<RestartByTemplateData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/agents/restart-by-template/{templateId}",
      ...options,
    });
  }

  /**
   * List the agent's configured channels. Reads agents/{id}/data/channels.json from S3 — the single source of truth (the runtime mutates the same file via its channel_* tools). Returns [] when the file is absent. Always fresh, no caching.
   */
  public static getAgentChannels<ThrowOnError extends boolean = false>(
    options: Options<GetAgentChannelsData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      GetAgentChannelsResponse,
      unknown,
      ThrowOnError
    >({
      url: "/agents/{id}/channels",
      ...options,
    });
  }

  /**
   * Replace the agent's channels. Writes agents/{id}/data/channels.json — restart the agent to pick up new env vars (TELEGRAM_BOT_TOKEN etc.) injected at pod submit time. Body is the exhaustive list — anything omitted is removed. Pass [] to clear.
   */
  public static setAgentChannels<ThrowOnError extends boolean = false>(
    options: Options<SetAgentChannelsData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).put<
      SetAgentChannelsResponse,
      unknown,
      ThrowOnError
    >({
      url: "/agents/{id}/channels",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }
}

export class FilesService {
  /**
   * List files for an agent
   */
  public static fileControllerList<ThrowOnError extends boolean = false>(
    options: Options<FileControllerListData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/agents/{agentId}/files",
      ...options,
    });
  }

  /**
   * Delete a file, or a whole folder (e.g. a skill dir) when `recursive=true`. Template-managed skills are recreated on the next restart unless detached from the template first.
   */
  public static fileControllerDelete<ThrowOnError extends boolean = false>(
    options: Options<FileControllerDeleteData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).delete<
      FileControllerDeleteResponse,
      unknown,
      ThrowOnError
    >({
      url: "/agents/{agentId}/files/content",
      ...options,
    });
  }

  /**
   * Read a chunk of a file. Omit `offset`/`limit` to read the first 256 KB. Use the returned `nextOffset` to continue.
   */
  public static fileControllerRead<ThrowOnError extends boolean = false>(
    options: Options<FileControllerReadData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      FileControllerReadResponse,
      unknown,
      ThrowOnError
    >({
      url: "/agents/{agentId}/files/content",
      ...options,
    });
  }

  /**
   * Save a file (.md / .json only)
   */
  public static fileControllerSave<ThrowOnError extends boolean = false>(
    options: Options<FileControllerSaveData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).put<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/agents/{agentId}/files/content",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Ask the agent runtime to push its local files to S3, then return the latest S3 state to the admin UI
   */
  public static fileControllerSync<ThrowOnError extends boolean = false>(
    options: Options<FileControllerSyncData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/agents/{agentId}/files/sync",
      ...options,
    });
  }

  /**
   * Download a ZIP archive of the agent’s entire S3 prefix (files, skills, runtime state). Used as a safety net before destructive actions.
   */
  public static exportAgentFiles<ThrowOnError extends boolean = false>(
    options: Options<ExportAgentFilesData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/agents/{agentId}/files/export",
      ...options,
    });
  }
}

export class BridleService {
  /**
   * Send a message to a agent (HTTP fallback — fire & forget)
   */
  public static sendBridleMessage<ThrowOnError extends boolean = false>(
    options: Options<SendBridleMessageData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/api/agent/{agentId}/message",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Send a message and wait for the agent response (synchronous)
   */
  public static sendBridleMessageSync<ThrowOnError extends boolean = false>(
    options: Options<SendBridleMessageSyncData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/api/agent/{agentId}/message/sync",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Check overall hub status
   */
  public static bridleHealth<ThrowOnError extends boolean = false>(
    options?: Options<BridleHealthData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      BridleHealthResponse,
      unknown,
      ThrowOnError
    >({
      url: "/api/agent/health",
      ...options,
    });
  }

  /**
   * Check agent connection status
   */
  public static bridleAgentHealth<ThrowOnError extends boolean = false>(
    options: Options<BridleAgentHealthData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      BridleAgentHealthResponse,
      unknown,
      ThrowOnError
    >({
      url: "/api/agent/{agentId}/health",
      ...options,
    });
  }

  /**
   * List all connected agents
   */
  public static listAgents<ThrowOnError extends boolean = false>(
    options?: Options<ListAgentsData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/api/agent/list",
      ...options,
    });
  }

  /**
   * Delete the persisted chat transcript for an agent/channel. Used to start a fresh chat — UI clears, refresh shows empty. Note: the agent runtime's in-memory session may still hold context until the next pod restart.
   */
  public static resetBridleTranscript<ThrowOnError extends boolean = false>(
    options: Options<ResetBridleTranscriptData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).delete<
      ResetBridleTranscriptResponse,
      unknown,
      ThrowOnError
    >({
      url: "/api/agent/{agentId}/transcript",
      ...options,
    });
  }

  /**
   * Replay the persisted chat transcript for an agent (read from the agent runtime's data/sessions/bridle:<channel>.jsonl). Paginated tail-first: omit `cursor` for the latest `limit` messages; pass the returned `nextCursor` to fetch older pages. Live updates still arrive via /ws/client.
   */
  public static getBridleTranscript<ThrowOnError extends boolean = false>(
    options: Options<GetBridleTranscriptData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      GetBridleTranscriptResponse,
      unknown,
      ThrowOnError
    >({
      url: "/api/agent/{agentId}/transcript",
      ...options,
    });
  }

  /**
   * Archive the persisted chat transcript for an agent/channel — the live JSONL is moved to a timestamped sibling (`bridle:<channel>.<iso-ts>.archived.jsonl`) and the live slot starts empty. Used by the embed's "New chat" action when the visitor wants a clean slate but we still want the prior conversation for admin/audit. No-op (returns `{}`) when there's nothing to archive.
   */
  public static archiveBridleTranscript<ThrowOnError extends boolean = false>(
    options: Options<ArchiveBridleTranscriptData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/api/agent/{agentId}/transcript/archive",
      ...options,
    });
  }
}

export class SkillsService {
  /**
   * List all skills
   */
  public static skillControllerFindAll<ThrowOnError extends boolean = false>(
    options?: Options<SkillControllerFindAllData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/skills",
      ...options,
    });
  }

  /**
   * Create a new skill
   */
  public static skillControllerCreate<ThrowOnError extends boolean = false>(
    options: Options<SkillControllerCreateData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/skills",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Curated GitHub repos searched for skills
   */
  public static skillControllerListSources<
    ThrowOnError extends boolean = false,
  >(options?: Options<SkillControllerListSourcesData, ThrowOnError>) {
    return (options?.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/skills/sources",
      ...options,
    });
  }

  /**
   * Search skills across curated GitHub repos
   */
  public static skillControllerSearch<ThrowOnError extends boolean = false>(
    options: Options<SkillControllerSearchData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/skills/search",
      ...options,
    });
  }

  /**
   * Import a skill from any GitHub URL (folder or SKILL.md)
   */
  public static skillControllerImportFromUrl<
    ThrowOnError extends boolean = false,
  >(options: Options<SkillControllerImportFromUrlData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).post<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/skills/import-url",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Import a skill from GitHub into the local DB
   */
  public static skillControllerImportFromGithub<
    ThrowOnError extends boolean = false,
  >(options: Options<SkillControllerImportFromGithubData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).post<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/skills/import",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Delete a skill
   */
  public static skillControllerRemove<ThrowOnError extends boolean = false>(
    options: Options<SkillControllerRemoveData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).delete<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/skills/{id}",
      ...options,
    });
  }

  /**
   * Get skill by ID
   */
  public static skillControllerFindById<ThrowOnError extends boolean = false>(
    options: Options<SkillControllerFindByIdData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/skills/{id}",
      ...options,
    });
  }

  /**
   * Update a skill
   */
  public static skillControllerUpdate<ThrowOnError extends boolean = false>(
    options: Options<SkillControllerUpdateData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).put<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/skills/{id}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * List agents that use this skill via their template. Drives the post-edit "Redeploy N agents" flow — skills are baked into agent pods at deploy time, so a skill update has no effect until those agents restart.
   */
  public static findDependentAgents<ThrowOnError extends boolean = false>(
    options: Options<FindDependentAgentsData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/skills/{id}/agents",
      ...options,
    });
  }
}

export class ChatsService {
  /**
   * List chat sessions (index). Filter by agent, channel, search; paginated.
   */
  public static getChats<ThrowOnError extends boolean = false>(
    options?: Options<GetChatsData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      GetChatsResponse,
      unknown,
      ThrowOnError
    >({
      url: "/chats",
      ...options,
    });
  }

  /**
   * Get one chat session (index metadata).
   */
  public static getChat<ThrowOnError extends boolean = false>(
    options: Options<GetChatData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      GetChatResponse,
      unknown,
      ThrowOnError
    >({
      url: "/chats/{id}",
      ...options,
    });
  }

  /**
   * Replay a chat session's transcript from S3, tail-first. `summary` markers are shown inline (compaction folds old turns into them); synthetic loop-control events are filtered. Admins may add tool_call,tool_result via `types`.
   */
  public static getChatMessages<ThrowOnError extends boolean = false>(
    options: Options<GetChatMessagesData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      GetChatMessagesResponse,
      unknown,
      ThrowOnError
    >({
      url: "/chats/{id}/messages",
      ...options,
    });
  }

  /**
   * Reconcile the chat index against S3 session files (all agents, or one).
   */
  public static syncChats<ThrowOnError extends boolean = false>(
    options: Options<SyncChatsData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      SyncChatsResponse,
      unknown,
      ThrowOnError
    >({
      url: "/chats/sync",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Generate (or refresh) an LLM summary + insights for one chat, on demand.
   */
  public static summarizeChat<ThrowOnError extends boolean = false>(
    options: Options<SummarizeChatData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      SummarizeChatResponse,
      unknown,
      ThrowOnError
    >({
      url: "/chats/{id}/summarize",
      ...options,
    });
  }

  /**
   * List the current user’s feedback for a chat session.
   */
  public static getMyChatFeedback<ThrowOnError extends boolean = false>(
    options: Options<GetMyChatFeedbackData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      GetMyChatFeedbackResponse,
      unknown,
      ThrowOnError
    >({
      url: "/chats/{id}/feedback",
      ...options,
    });
  }

  /**
   * Set the current user’s 👍/👎 on an assistant message.
   */
  public static createChatFeedback<ThrowOnError extends boolean = false>(
    options: Options<CreateChatFeedbackData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      CreateChatFeedbackResponse,
      unknown,
      ThrowOnError
    >({
      url: "/chats/{id}/feedback",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Clear the current user’s feedback on a message (toggle-off).
   */
  public static deleteChatFeedback<ThrowOnError extends boolean = false>(
    options: Options<DeleteChatFeedbackData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).delete<
      DeleteChatFeedbackResponse,
      unknown,
      ThrowOnError
    >({
      url: "/chats/{id}/feedback/{messageId}",
      ...options,
    });
  }

  /**
   * Download a chat transcript as json / markdown / csv.
   */
  public static exportChat<ThrowOnError extends boolean = false>(
    options: Options<ExportChatData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/chats/{id}/export",
      ...options,
    });
  }

  /**
   * List the current user's own chat sessions, newest first.
   */
  public static getMyChats<ThrowOnError extends boolean = false>(
    options?: Options<GetMyChatsData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      GetMyChatsResponse,
      unknown,
      ThrowOnError
    >({
      url: "/me/chats",
      ...options,
    });
  }

  /**
   * Get one of the current user's own chat sessions.
   */
  public static getMyChat<ThrowOnError extends boolean = false>(
    options: Options<GetMyChatData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      GetMyChatResponse,
      unknown,
      ThrowOnError
    >({
      url: "/me/chats/{id}",
      ...options,
    });
  }

  /**
   * Replay one of the current user's own chats, tail-first. `summary` markers are shown inline; tool events are never exposed to end users.
   */
  public static getMyChatMessages<ThrowOnError extends boolean = false>(
    options: Options<GetMyChatMessagesData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      GetMyChatMessagesResponse,
      unknown,
      ThrowOnError
    >({
      url: "/me/chats/{id}/messages",
      ...options,
    });
  }

  /**
   * Reconcile the current user's OWN chats from S3 into the index (self-service, non-admin). Only sessions belonging to the caller are touched. A manual fallback when realtime indexing has not caught up.
   */
  public static syncMyChats<ThrowOnError extends boolean = false>(
    options: Options<SyncMyChatsData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      SyncMyChatsResponse,
      unknown,
      ThrowOnError
    >({
      url: "/me/chats/sync",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * List the current user's own feedback for one of their chats.
   */
  public static listMyChatFeedback<ThrowOnError extends boolean = false>(
    options: Options<ListMyChatFeedbackData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      ListMyChatFeedbackResponse,
      unknown,
      ThrowOnError
    >({
      url: "/me/chats/{id}/feedback",
      ...options,
    });
  }

  /**
   * Set the current user's 👍/👎 on a message in their own chat.
   */
  public static createMyChatFeedback<ThrowOnError extends boolean = false>(
    options: Options<CreateMyChatFeedbackData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      CreateMyChatFeedbackResponse,
      unknown,
      ThrowOnError
    >({
      url: "/me/chats/{id}/feedback",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Clear the current user's feedback on a message (toggle-off).
   */
  public static deleteMyChatFeedback<ThrowOnError extends boolean = false>(
    options: Options<DeleteMyChatFeedbackData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).delete<
      DeleteMyChatFeedbackResponse,
      unknown,
      ThrowOnError
    >({
      url: "/me/chats/{id}/feedback/{messageId}",
      ...options,
    });
  }

  /**
   * Download the current user's own chat as json / markdown / csv.
   */
  public static exportMyChat<ThrowOnError extends boolean = false>(
    options: Options<ExportMyChatData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/me/chats/{id}/export",
      ...options,
    });
  }
}

export class UsersService {
  /**
   * List all users
   */
  public static userControllerFindAll<ThrowOnError extends boolean = false>(
    options?: Options<UserControllerFindAllData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/users",
      ...options,
    });
  }

  /**
   * Create a user (admin sets the password)
   */
  public static userControllerCreate<ThrowOnError extends boolean = false>(
    options: Options<UserControllerCreateData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/users",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Remove user. Owner only.
   */
  public static userControllerRemove<ThrowOnError extends boolean = false>(
    options: Options<UserControllerRemoveData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).delete<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/users/{id}",
      ...options,
    });
  }

  /**
   * Get user by ID
   */
  public static userControllerFindById<ThrowOnError extends boolean = false>(
    options: Options<UserControllerFindByIdData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/users/{id}",
      ...options,
    });
  }

  /**
   * Update user (name, email, password, status). Use /role to change the role.
   */
  public static userControllerUpdate<ThrowOnError extends boolean = false>(
    options: Options<UserControllerUpdateData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).put<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/users/{id}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Set the user's role. Owner only.
   */
  public static userControllerUpdateRole<ThrowOnError extends boolean = false>(
    options: Options<UserControllerUpdateRoleData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).put<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/users/{id}/role",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }
}

export class TemplateFilesService {
  /**
   * List files for a template
   */
  public static templateFileControllerList<
    ThrowOnError extends boolean = false,
  >(options: Options<TemplateFileControllerListData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/templates/{id}/files",
      ...options,
    });
  }

  /**
   * Read a template file
   */
  public static templateFileControllerRead<
    ThrowOnError extends boolean = false,
  >(options: Options<TemplateFileControllerReadData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/templates/{id}/files/content",
      ...options,
    });
  }

  /**
   * Save a template file (.md / .json only)
   */
  public static templateFileControllerSave<
    ThrowOnError extends boolean = false,
  >(options: Options<TemplateFileControllerSaveData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).put<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/templates/{id}/files/content",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Replace template files in S3 with the uploaded folder. The body is multipart/form-data; pass a parallel "paths[]" field with the relative path for each file.
   */
  public static templateFileControllerUpload<
    ThrowOnError extends boolean = false,
  >(options: Options<TemplateFileControllerUploadData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).post<
      unknown,
      unknown,
      ThrowOnError
    >({
      ...formDataBodySerializer,
      url: "/templates/{id}/files/upload",
      ...options,
      headers: {
        "Content-Type": null,
        ...options?.headers,
      },
    });
  }
}

export class PaddockScenariosService {
  /**
   * List paddock scenarios. Filter by templateId or agentId; without filters returns all.
   */
  public static paddockScenarioControllerFindAll<
    ThrowOnError extends boolean = false,
  >(options?: Options<PaddockScenarioControllerFindAllData, ThrowOnError>) {
    return (options?.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/paddock-scenarios",
      ...options,
    });
  }

  /**
   * Create a paddock scenario scoped to either a template or an agent (XOR — exactly one).
   */
  public static paddockScenarioControllerCreate<
    ThrowOnError extends boolean = false,
  >(options: Options<PaddockScenarioControllerCreateData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).post<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/paddock-scenarios",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Delete a paddock scenario
   */
  public static paddockScenarioControllerRemove<
    ThrowOnError extends boolean = false,
  >(options: Options<PaddockScenarioControllerRemoveData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).delete<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/paddock-scenarios/{id}",
      ...options,
    });
  }

  /**
   * Get a paddock scenario by id
   */
  public static paddockScenarioControllerFindById<
    ThrowOnError extends boolean = false,
  >(options: Options<PaddockScenarioControllerFindByIdData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/paddock-scenarios/{id}",
      ...options,
    });
  }

  /**
   * Update a paddock scenario. Scope (templateId/agentId) is immutable — create a new scenario to change scope.
   */
  public static paddockScenarioControllerUpdate<
    ThrowOnError extends boolean = false,
  >(options: Options<PaddockScenarioControllerUpdateData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).patch<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/paddock-scenarios/{id}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Generate a scenario draft from a natural-language description via LLM. Result is NOT persisted — review + POST / to save.
   */
  public static paddockScenarioControllerGenerate<
    ThrowOnError extends boolean = false,
  >(options: Options<PaddockScenarioControllerGenerateData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).post<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/paddock-scenarios/generate",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }
}

export class SecretsService {
  /**
   * Delete a secret for an agent. No-op if the key does not exist. Returns the full secret list.
   */
  public static secretControllerDelete<ThrowOnError extends boolean = false>(
    options: Options<SecretControllerDeleteData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).delete<
      SecretControllerDeleteResponse,
      unknown,
      ThrowOnError
    >({
      url: "/agents/{agentId}/secrets",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * List secrets stored for an agent. AWS source pulls from AWS Secrets Manager (aws_secret_prefix/<agentId>); file source lists S3 under agents/<agentId>/data/secrets/.
   */
  public static secretControllerList<ThrowOnError extends boolean = false>(
    options: Options<SecretControllerListData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      SecretControllerListResponse,
      unknown,
      ThrowOnError
    >({
      url: "/agents/{agentId}/secrets",
      ...options,
    });
  }

  /**
   * Create or update a secret for an agent (upsert). Returns the full secret list.
   */
  public static secretControllerSet<ThrowOnError extends boolean = false>(
    options: Options<SecretControllerSetData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).put<
      SecretControllerSetResponse,
      unknown,
      ThrowOnError
    >({
      url: "/agents/{agentId}/secrets",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Atomic full-store replace. Mirrors AWS Secrets Manager's plaintext-edit semantics — the whole agent secret store becomes the supplied object. Returns the full secret list.
   */
  public static secretControllerReplace<ThrowOnError extends boolean = false>(
    options: Options<SecretControllerReplaceData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      SecretControllerReplaceResponse,
      unknown,
      ThrowOnError
    >({
      url: "/agents/{agentId}/secrets/replace",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }
}

export class LogsService {
  /**
   * Get agent pod logs
   */
  public static logControllerGetLogs<ThrowOnError extends boolean = false>(
    options: Options<LogControllerGetLogsData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/agents/{agentId}/logs",
      ...options,
    });
  }
}

export class UsageService {
  /**
   * Get 30-day usage for an agent with cost
   */
  public static usageControllerFindForAgent<
    ThrowOnError extends boolean = false,
  >(options: Options<UsageControllerFindForAgentData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/agents/{agentId}/usage",
      ...options,
    });
  }

  /**
   * Agent reports its usage (mirrors runtime usage.json)
   */
  public static usageControllerReport<ThrowOnError extends boolean = false>(
    options: Options<UsageControllerReportData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      UsageControllerReportResponse,
      unknown,
      ThrowOnError
    >({
      url: "/agents/{agentId}/usage",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Get 30-day usage for a single LLM credential across all agents
   */
  public static usageControllerFindForCredential<
    ThrowOnError extends boolean = false,
  >(options: Options<UsageControllerFindForCredentialData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/llms/{id}/usage",
      ...options,
    });
  }
}

export class RancherService {
  /**
   * Stepper state for the Rancher setup wizard: do we have an LLM, the special template, and an admin agent?
   */
  public static rancherControllerStatus<ThrowOnError extends boolean = false>(
    options?: Options<RancherControllerStatusData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/rancher/status",
      ...options,
    });
  }

  /**
   * Create the special Rancher template (idempotent). Returns the existing one if already created.
   */
  public static rancherControllerEnsureTemplate<
    ThrowOnError extends boolean = false,
  >(options?: Options<RancherControllerEnsureTemplateData, ThrowOnError>) {
    return (options?.client ?? _heyApiClient).post<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/rancher/template",
      ...options,
    });
  }
}

export class UpgradeService {
  /**
   * Whether the local checkout can be upgraded in place (clean tree, on main, .git present, not in deployed mode).
   */
  public static upgradeControllerStatus<ThrowOnError extends boolean = false>(
    options?: Options<UpgradeControllerStatusData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/upgrade/status",
      ...options,
    });
  }

  /**
   * Pull latest Ranch from main, bun install, prisma migrate deploy. nest's --watch and Nuxt HMR pick up the new code automatically. Response may not return cleanly if the watcher restarts mid-call — the client should reload after a short delay.
   */
  public static upgradeControllerRun<ThrowOnError extends boolean = false>(
    options?: Options<UpgradeControllerRunData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).post<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/upgrade",
      ...options,
    });
  }
}

export class PaddockEvaluationsService {
  /**
   * List paddock evaluations. Filter by agentId / templateId.
   */
  public static paddockEvaluationControllerList<
    ThrowOnError extends boolean = false,
  >(options?: Options<PaddockEvaluationControllerListData, ThrowOnError>) {
    return (options?.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/paddock-evaluations",
      ...options,
    });
  }

  /**
   * Start a paddock evaluation for an agent. Returns the evaluation record immediately; the actual run is asynchronous (poll status).
   */
  public static paddockEvaluationControllerStart<
    ThrowOnError extends boolean = false,
  >(options: Options<PaddockEvaluationControllerStartData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).post<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/paddock-evaluations",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Get evaluation status + summary + per-scenario results
   */
  public static paddockEvaluationControllerGet<
    ThrowOnError extends boolean = false,
  >(options: Options<PaddockEvaluationControllerGetData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/paddock-evaluations/{id}",
      ...options,
    });
  }

  /**
   * Fetch the full evaluation report — both structured JSON and markdown.
   */
  public static paddockEvaluationControllerReport<
    ThrowOnError extends boolean = false,
  >(options: Options<PaddockEvaluationControllerReportData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/paddock-evaluations/{id}/report",
      ...options,
    });
  }

  /**
   * Live tail of paddock CLI stdout+stderr. In-memory ring buffer (~2000 lines), keyed by the evaluation's agent. Cleared on API restart or when a fresh run starts for the same agent.
   */
  public static paddockEvaluationControllerLogs<
    ThrowOnError extends boolean = false,
  >(options: Options<PaddockEvaluationControllerLogsData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/paddock-evaluations/{id}/logs",
      ...options,
    });
  }

  /**
   * Fetch one scenario as captured in this evaluation's snapshot (messages, expectedBehavior, successCriteria). Reliable across template re-seeds that change scenario UUIDs in the live `paddock_scenarios` table.
   */
  public static paddockEvaluationControllerScenario<
    ThrowOnError extends boolean = false,
  >(options: Options<PaddockEvaluationControllerScenarioData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/paddock-evaluations/{id}/scenarios/{scenarioId}",
      ...options,
    });
  }

  /**
   * Fetch the per-scenario execution trace (responses, tool calls, errors). Available after the run completes.
   */
  public static paddockEvaluationControllerTrace<
    ThrowOnError extends boolean = false,
  >(options: Options<PaddockEvaluationControllerTraceData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/paddock-evaluations/{id}/trace",
      ...options,
    });
  }

  /**
   * Mark a running evaluation as aborted. The current scenario will finish before the run halts.
   */
  public static paddockEvaluationControllerAbort<
    ThrowOnError extends boolean = false,
  >(options: Options<PaddockEvaluationControllerAbortData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).post<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/paddock-evaluations/{id}/abort",
      ...options,
    });
  }

  /**
   * Start a new evaluation re-using the exact scenarios + judge config from this one. Returns the new evaluation record immediately; the run is async.
   */
  public static paddockEvaluationControllerRerun<
    ThrowOnError extends boolean = false,
  >(options: Options<PaddockEvaluationControllerRerunData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).post<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/paddock-evaluations/{id}/rerun",
      ...options,
    });
  }
}

export class BrowserService {
  /**
   * List the calling user’s browser sessions.
   */
  public static listBrowserSessions<ThrowOnError extends boolean = false>(
    options?: Options<ListBrowserSessionsData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      ListBrowserSessionsResponse,
      unknown,
      ThrowOnError
    >({
      url: "/browser/sessions",
      ...options,
    });
  }

  /**
   * Open or reuse a browser session for the given accountKey. Returns a CDP URL the runtime uses to connect a Playwright/CDP client.
   */
  public static openBrowserSession<ThrowOnError extends boolean = false>(
    options: Options<OpenBrowserSessionData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      OpenBrowserSessionResponse,
      unknown,
      ThrowOnError
    >({
      url: "/browser/sessions",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Disconnect the account — drops the session row and schedules the profile directory for cleanup.
   */
  public static deleteBrowserSession<ThrowOnError extends boolean = false>(
    options: Options<DeleteBrowserSessionData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).delete<
      DeleteBrowserSessionResponse,
      unknown,
      ThrowOnError
    >({
      url: "/browser/sessions/{id}",
      ...options,
    });
  }

  /**
   * Get a single session (only sessions you own).
   */
  public static getBrowserSession<ThrowOnError extends boolean = false>(
    options: Options<GetBrowserSessionData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      GetBrowserSessionResponse,
      unknown,
      ThrowOnError
    >({
      url: "/browser/sessions/{id}",
      ...options,
    });
  }

  /**
   * Discard the current browser instance for this session and return a fresh CDP URL. Use when a browser_play call has been stuck on a 120s timeout.
   */
  public static resetBrowserSession<ThrowOnError extends boolean = false>(
    options: Options<ResetBrowserSessionData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      ResetBrowserSessionResponse,
      unknown,
      ThrowOnError
    >({
      url: "/browser/sessions/{id}/reset",
      ...options,
    });
  }

  /**
   * Update session status. Called by the runtime after each tool batch (idle / needs_login / stuck), or by the admin UI to mark a session for relogin.
   */
  public static setBrowserSessionStatus<ThrowOnError extends boolean = false>(
    options: Options<SetBrowserSessionStatusData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      SetBrowserSessionStatusResponse,
      unknown,
      ThrowOnError
    >({
      url: "/browser/sessions/{id}/status",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Mint a short-lived (15 min) VNC URL the end user can open to finish a 2FA/CAPTCHA flow manually.
   */
  public static mintBrowserSessionVncUrl<ThrowOnError extends boolean = false>(
    options: Options<MintBrowserSessionVncUrlData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/browser/sessions/{id}/vnc-url",
      ...options,
    });
  }

  /**
   * Open or reuse a session on behalf of a user. Used by the runtime before each browser_play call.
   */
  public static openBrowserSessionInternal<
    ThrowOnError extends boolean = false,
  >(options: Options<OpenBrowserSessionInternalData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).post<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/browser/internal/sessions",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Report session status back from the runtime — typically idle after success or needs_login when Instagram redirected to /login.
   */
  public static setBrowserSessionStatusInternal<
    ThrowOnError extends boolean = false,
  >(options: Options<SetBrowserSessionStatusInternalData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).post<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/browser/internal/sessions/{id}/status",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Hard-reset a stuck session and return a fresh CDP URL on the same profile.
   */
  public static resetBrowserSessionInternal<
    ThrowOnError extends boolean = false,
  >(options: Options<ResetBrowserSessionInternalData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).post<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/browser/internal/sessions/{id}/reset",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Pull cookies off the live Chrome attached to this session in Playwright storageState shape. The runtime calls this from browser_login_done after the user signs in via the VNC URL, then writes the result to .agent/browser-state/.
   */
  public static harvestBrowserSessionInternal<
    ThrowOnError extends boolean = false,
  >(options: Options<HarvestBrowserSessionInternalData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).post<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/browser/internal/sessions/{id}/harvest",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Mark sessions idle for longer than `idleMinutes` (default 30) as expired. Called by the browser-pool-cleanup CronJob.
   */
  public static cleanupBrowserSessionsInternal<
    ThrowOnError extends boolean = false,
  >(options?: Options<CleanupBrowserSessionsInternalData, ThrowOnError>) {
    return (options?.client ?? _heyApiClient).post<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/browser/internal/sessions/cleanup",
      ...options,
    });
  }

  /**
   * Mint a long-lived JWT that authorises the Chrome extension to import cookies into the given agent + userId scope. Admin UI calls this on behalf of the logged-in user.
   */
  public static issueBrowserExtensionToken<
    ThrowOnError extends boolean = false,
  >(options: Options<IssueBrowserExtensionTokenData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).post<
      IssueBrowserExtensionTokenResponse,
      unknown,
      ThrowOnError
    >({
      url: "/browser/extension/token",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Receive cookies harvested from the user's own Chrome and write them as a Playwright storageState file under the agent's S3 prefix. Authentication: Bearer <ext-token> minted via /browser/extension/token.
   */
  public static importBrowserStorageState<ThrowOnError extends boolean = false>(
    options: Options<ImportBrowserStorageStateData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      ImportBrowserStorageStateResponse,
      unknown,
      ThrowOnError
    >({
      url: "/browser/extension/import-state",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }
}

export class IntegrationsService {
  /**
   * List supported services. Static — defined in api/src/slices/integration/domain/catalogue.ts and shipped with each API release.
   */
  public static listIntegrationCatalogue<ThrowOnError extends boolean = false>(
    options?: Options<ListIntegrationCatalogueData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      ListIntegrationCatalogueResponse,
      unknown,
      ThrowOnError
    >({
      url: "/integrations/catalogue",
      ...options,
    });
  }

  /**
   * List the calling user’s connected integration accounts.
   */
  public static listIntegrationAccounts<ThrowOnError extends boolean = false>(
    options?: Options<ListIntegrationAccountsData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      ListIntegrationAccountsResponse,
      unknown,
      ThrowOnError
    >({
      url: "/integrations/accounts",
      ...options,
    });
  }

  /**
   * Start (or re-open) a connection. Idempotent on (userId, service, accountKey) — repeated calls return the existing row. Status stays "pending" until the underlying credential is stored (browser cookies harvested or secret value saved).
   */
  public static connectIntegration<ThrowOnError extends boolean = false>(
    options: Options<ConnectIntegrationData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      ConnectIntegrationResponse,
      unknown,
      ThrowOnError
    >({
      url: "/integrations/accounts",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Disconnect an integration. Browser-mechanism: also deletes the underlying BrowserSession (profile cleanup runs on its own CronJob). Secret-mechanism: also wipes the stored value from the per-user secret store.
   */
  public static disconnectIntegration<ThrowOnError extends boolean = false>(
    options: Options<DisconnectIntegrationData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).delete<
      DisconnectIntegrationResponse,
      unknown,
      ThrowOnError
    >({
      url: "/integrations/accounts/{id}",
      ...options,
    });
  }

  /**
   * Fetch one account. Refreshes status from the underlying BrowserSession before returning. 404 if not owned by the caller.
   */
  public static getIntegrationAccount<ThrowOnError extends boolean = false>(
    options: Options<GetIntegrationAccountData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      GetIntegrationAccountResponse,
      unknown,
      ThrowOnError
    >({
      url: "/integrations/accounts/{id}",
      ...options,
    });
  }

  /**
   * Return the help URL + login URL + textual instructions the agent forwards to the end user. Browser-mechanism only. No VNC — the user logs in inside their own Chrome and pushes cookies via the Ranch extension. Flips status to "needs_login" so the admin UI reflects the pending state.
   */
  public static openIntegrationLogin<ThrowOnError extends boolean = false>(
    options: Options<OpenIntegrationLoginData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      OpenIntegrationLoginResponse,
      unknown,
      ThrowOnError
    >({
      url: "/integrations/accounts/{id}/login",
      ...options,
    });
  }

  /**
   * Alternative to VNC login: accept a Playwright storageState dump that the user harvested from their own browser. The runtime falls back to this state when no per-agent state file exists, so one import covers every agent the user owns. Browser-mechanism only.
   */
  public static importIntegrationCookies<ThrowOnError extends boolean = false>(
    options: Options<ImportIntegrationCookiesData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      ImportIntegrationCookiesResponse,
      unknown,
      ThrowOnError
    >({
      url: "/integrations/accounts/{id}/import-cookies",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Write the credential value for a secret-mechanism account. Idempotent — repeated calls overwrite (rotation). The value is never echoed back through the API.
   */
  public static saveIntegrationSecret<ThrowOnError extends boolean = false>(
    options: Options<SaveIntegrationSecretData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      SaveIntegrationSecretResponse,
      unknown,
      ThrowOnError
    >({
      url: "/integrations/accounts/{id}/secret",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Mint a long-lived JWT that authorises the Chrome extension to push cookies into the caller’s integration store. Admin UI calls this on behalf of the logged-in user. Mirrors /browser/extension/token but with a narrower scope and no agentId.
   */
  public static issueIntegrationExtensionToken<
    ThrowOnError extends boolean = false,
  >(options: Options<IssueIntegrationExtensionTokenData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).post<
      IssueIntegrationExtensionTokenResponse,
      unknown,
      ThrowOnError
    >({
      url: "/integrations/extension/token",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Receive cookies harvested from the user’s own Chrome and stash them in the per-user browser-state store, creating the IntegrationAccount on the fly if it doesn’t exist. Authentication: Bearer <ext-token> minted via /integrations/extension/token.
   */
  public static importIntegrationExtensionState<
    ThrowOnError extends boolean = false,
  >(options: Options<ImportIntegrationExtensionStateData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).post<
      ImportIntegrationExtensionStateResponse,
      unknown,
      ThrowOnError
    >({
      url: "/integrations/extension/import-state",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Download the Ranch Cookies Chrome extension as a zip — load it unpacked in chrome://extensions/. Path source: EXTENSION_DIR env var, falls back to ranch-repo-root/extension/.
   */
  public static downloadIntegrationExtension<
    ThrowOnError extends boolean = false,
  >(options?: Options<DownloadIntegrationExtensionData, ThrowOnError>) {
    return (options?.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/integrations/extension/download",
      ...options,
    });
  }
}

export class IntegrationsInternalService {
  /**
   * Resolve every connected secret-mechanism integration into a flat env map. Called lazily by the runtime per tool invocation — picks up rotated keys without an agent restart. Multiple accounts on one service: most recently updated wins the bare env var; each one is also exposed under a per-accountKey alias.
   */
  public static resolveIntegrationSecrets<ThrowOnError extends boolean = false>(
    options?: Options<ResolveIntegrationSecretsData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      ResolveIntegrationSecretsResponse,
      unknown,
      ThrowOnError
    >({
      url: "/integrations/internal/secrets",
      ...options,
    });
  }

  /**
   * List every integration in the instance. The runtime’s integration_list tool exposes this so an agent passes the exact browser_play profile instead of guessing.
   */
  public static listIntegrationAccountsForRuntime<
    ThrowOnError extends boolean = false,
  >(options?: Options<ListIntegrationAccountsForRuntimeData, ThrowOnError>) {
    return (options?.client ?? _heyApiClient).get<
      ListIntegrationAccountsForRuntimeResponse,
      unknown,
      ThrowOnError
    >({
      url: "/integrations/internal/accounts",
      ...options,
    });
  }

  /**
   * Resolve login instructions for a (service, accountKey) pair. The runtime calls this when an agent tool returns `needsLogin` — replaces the legacy VNC mint flow. Returns the help URL + site URL the agent should forward to the end user.
   */
  public static requestIntegrationLogin<ThrowOnError extends boolean = false>(
    options: Options<RequestIntegrationLoginData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      RequestIntegrationLoginResponse,
      unknown,
      ThrowOnError
    >({
      url: "/integrations/internal/request-login",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Look up the Playwright storageState for a given profile. Runtime hits this when no per-agent state file exists locally. 404 if nothing was imported for this profile.
   */
  public static resolveIntegrationBrowserState<
    ThrowOnError extends boolean = false,
  >(options: Options<ResolveIntegrationBrowserStateData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/integrations/internal/browser-state",
      ...options,
    });
  }
}

export class McpService {
  public static sseControllerSse<ThrowOnError extends boolean = false>(
    options?: Options<SseControllerSseData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/mcp/sse",
      ...options,
    });
  }

  public static sseControllerMessages<ThrowOnError extends boolean = false>(
    options?: Options<SseControllerMessagesData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).post<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/mcp/messages",
      ...options,
    });
  }

  public static sseControllerDebugSessions<
    ThrowOnError extends boolean = false,
  >(options: Options<SseControllerDebugSessionsData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/teams/{teamId}/sessions/debug",
      ...options,
    });
  }
}

export class StreamableHttpService {
  public static streamableHttpControllerHandleDeleteRequest<
    ThrowOnError extends boolean = false,
  >(
    options?: Options<
      StreamableHttpControllerHandleDeleteRequestData,
      ThrowOnError
    >,
  ) {
    return (options?.client ?? _heyApiClient).delete<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/mcp/mcp",
      ...options,
    });
  }

  public static streamableHttpControllerHandleGetRequest<
    ThrowOnError extends boolean = false,
  >(
    options: Options<
      StreamableHttpControllerHandleGetRequestData,
      ThrowOnError
    >,
  ) {
    return (options.client ?? _heyApiClient).get<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/mcp/mcp",
      ...options,
    });
  }

  public static streamableHttpControllerHandlePostRequest<
    ThrowOnError extends boolean = false,
  >(
    options: Options<
      StreamableHttpControllerHandlePostRequestData,
      ThrowOnError
    >,
  ) {
    return (options.client ?? _heyApiClient).post<
      unknown,
      unknown,
      ThrowOnError
    >({
      url: "/mcp/mcp",
      ...options,
    });
  }
}
