// This file is auto-generated by @hey-api/openapi-ts

export type CreateOwnerDto = {
  name: string;
  email: string;
  password: string;
};

export type UpsertSettingDto = {
  valueType: "string" | "json";
  /**
   * String for valueType=string; any JSON for valueType=json
   */
  value: {
    [key: string]: unknown;
  };
};

export type CreateLlmCredentialDto = {
  provider: string;
  model: string;
  apiKey: string;
  fallbackModel?: string;
  label?: string;
  status?: "active" | "disabled";
  supportsChat?: boolean;
  supportsEmbedding?: boolean;
};

export type UpdateLlmCredentialDto = {
  provider?: string;
  model?: string;
  apiKey?: string;
  fallbackModel?: string;
  label?: string;
  status?: "active" | "disabled";
  supportsChat?: boolean;
  supportsEmbedding?: boolean;
};

export type LlmHealthCheckResultDto = {
  ok: boolean;
  latencyMs: number;
  provider: string;
  model: string;
  error?: string;
};

export type CreateTemplateDto = {
  name: string;
  description: string;
  image: string;
  defaultConfig?: {
    [key: string]: unknown;
  };
  defaultResources?: {
    [key: string]: unknown;
  };
  paddockConfig?: {
    [key: string]: unknown;
  };
  defaultKnowledgeIds?: Array<string>;
};

export type UpdateTemplateDto = {
  name?: string;
  description?: string;
  image?: string;
  defaultConfig?: {
    [key: string]: unknown;
  };
  defaultResources?: {
    [key: string]: unknown;
  };
  paddockConfig?: {
    [key: string]: unknown;
  };
  defaultKnowledgeIds?: Array<string>;
};

export type SetTemplateSkillsDto = {
  /**
   * Full list of skill IDs to attach. Replaces any prior set.
   */
  skillIds: Array<string>;
};

export type SetTemplateMcpsDto = {
  /**
   * Full list of MCP server IDs to attach. Replaces any prior set.
   */
  mcpServerIds: Array<string>;
};

export type CreateMcpServerDto = {
  name: string;
  description?: {
    [key: string]: unknown;
  };
  url: string;
  transport?: "streamableHttp" | "sse";
  authType?: "none" | "bearer" | "header";
  authValue?: {
    [key: string]: unknown;
  };
  enabled?: boolean;
};

export type UpdateMcpServerDto = {
  name?: string;
  description?: {
    [key: string]: unknown;
  };
  url?: string;
  transport?: "streamableHttp" | "sse";
  authType?: "none" | "bearer" | "header";
  authValue?: {
    [key: string]: unknown;
  };
  enabled?: boolean;
};

export type LoginDto = {
  email: string;
  password: string;
};

export type RegisterDto = {
  name: string;
  email: string;
  password: string;
};

/**
 * Server filters Owner/Admin out unless the presenting API key carries the embed:mint-admin scope; plain embed keys cannot grant platform-admin to a visitor.
 */
export enum UserRoleTypes {
  OWNER = "Owner",
  ADMIN = "Admin",
  USER = "User",
  AGENT = "Agent",
}

export type EmbedTokenDto = {
  /**
   * Subject — used as clientId for routing inside the bridle hub.
   */
  sub: string;
  email?: string;
  /**
   * Server filters Owner/Admin out unless the presenting API key carries the embed:mint-admin scope; plain embed keys cannot grant platform-admin to a visitor.
   */
  roles?: Array<UserRoleTypes>;
  /**
   * Duration string (s/m/h/d). Defaults to 15m.
   */
  expiresIn?: string;
};

export enum ApiKeyScopeTypes {
  "EMBED:MINT" = "embed:mint",
  "EMBED:MINT_ADMIN" = "embed:mint-admin",
  ADMIN = "admin",
}

export type CreateApiKeyDto = {
  name: string;
  scopes: Array<ApiKeyScopeTypes>;
  /**
   * ISO date string. Omit for a non-expiring key.
   */
  expiresAt?: string;
};

export type GraphNodeDto = {
  id: string;
  label: string;
  entityType: string;
  description: string;
};

export type GraphEdgeDto = {
  id: string;
  source: string;
  target: string;
  weight: number;
  keywords: string;
  description: string;
};

export type GraphDto = {
  nodes: Array<GraphNodeDto>;
  edges: Array<GraphEdgeDto>;
  isTruncated: boolean;
};

export type CreateKnowledgeDto = {
  name: string;
  description?: string;
  entityTypes?: Array<string>;
  relationshipTypes?: Array<string>;
};

export type UpdateKnowledgeDto = {
  name?: string;
  description?: string | null;
  entityTypes?: Array<string>;
  relationshipTypes?: Array<string>;
};

export type QueryKnowledgeDto = {
  query: string;
  mode?: "hybrid" | "local" | "global" | "naive";
  topK?: number;
};

export type KnowledgeQueryReferenceDto = {
  referenceId: string;
  filePath: string;
};

export type KnowledgeQueryResultDto = {
  answer: string;
  references: Array<KnowledgeQueryReferenceDto>;
};

export type CreateSourceDto = {
  type: "file" | "url" | "text";
  name: string;
  url?: string;
  content?: string;
};

export type AddFromSitemapDto = {
  sitemapUrl: string;
  urlPrefix?: string;
};

export type AddFromSitemapResultDto = {
  added: number;
  discovered: number;
};

export type AddFromArchiveResultDto = {
  /**
   * Number of ingestable files detected in the archive. Import runs in the background; refresh the sources list to watch them appear.
   */
  detected: number;
  started: boolean;
};

export type AgentPodStatusDto = {
  agentId: string;
  podName: string;
  phase: "Pending" | "Running" | "Succeeded" | "Failed" | "Unknown";
  ready: boolean;
  restartCount: number;
  startedAt: string | null;
  lastTerminationReason: string | null;
  containerWaitingReason: string | null;
  message: string | null;
  observedAt: string;
};

export type AgentStatusDto = {
  /**
   * Agent DB record (id, name, status, etc.)
   */
  agent: {
    [key: string]: unknown;
  };
  /**
   * Live pod status; null if no pod is currently running for this agent.
   */
  pod: AgentPodStatusDto | null;
};

export type AgentPodMetricsDto = {
  /**
   * Current CPU usage in millicores
   */
  cpuMilli: number;
  /**
   * Current memory usage in bytes
   */
  memBytes: number;
  /**
   * CPU limit in millicores
   */
  cpuLimitMilli: number;
  /**
   * Memory limit in bytes
   */
  memLimitBytes: number;
};

export type AgentNodeMetricsDto = {
  name: string;
  diskAvailBytes: number;
  diskCapacityBytes: number;
};

export type AgentMetricsDto = {
  pod: AgentPodMetricsDto;
  node: AgentNodeMetricsDto;
};

export type AgentEnvVarDto = {
  name: string;
  value: string;
};

export type AgentMcpDto = {
  /**
   * Unique MCP server name (key in the runtime registry).
   */
  name: string;
  /**
   * Transport protocol the runtime should use to connect.
   */
  transport: "streamableHttp" | "sse";
  /**
   * MCP server endpoint URL.
   */
  url: string;
  /**
   * Auth scheme for the connection.
   */
  authType: "none" | "bearer" | "header";
  /**
   * Auth credential. For `bearer`: raw token (runtime adds the `Bearer ` prefix). For `header`: literal `Header-Name: value` line. `null` when authType is `none`.
   */
  authValue: string | null;
  /**
   * Always `true` in this list — disabled servers are filtered server-side. Kept for forward compatibility.
   */
  enabled: boolean;
};

export type AgentResourcesDto = {
  cpu: string;
  memory: string;
};

export type CreateAgentDto = {
  name: string;
  templateId: string;
  llmCredentialId?: string;
  config?: {
    [key: string]: unknown;
  };
  resources?: AgentResourcesDto;
  /**
   * When true, the agent is visible on the public landing page to unauthenticated visitors.
   */
  isPublic?: boolean;
  /**
   * Origins (scheme + host + port) authorized to open browser WebSockets to this bot without a JWT. Only consulted when isPublic=true.
   */
  allowedOrigins?: Array<string>;
  knowledgeIds?: Array<string>;
  /**
   * When true, the agent is created as the Ranch admin on first deploy: any existing admin is demoted (and redeployed without RANCH_ADMIN), and this agent boots with RANCH_ADMIN=true + a service token. Single-admin invariant is enforced.
   */
  isAdmin?: boolean;
};

export type UpdateAgentDto = {
  name?: string;
  templateId?: string;
  llmCredentialId?: string;
  config?: {
    [key: string]: unknown;
  };
  resources?: AgentResourcesDto;
  /**
   * When true, the agent is visible on the public landing page to unauthenticated visitors.
   */
  isPublic?: boolean;
  /**
   * Origins (scheme + host + port) authorized to open browser WebSockets to this bot without a JWT. Only consulted when isPublic=true.
   */
  allowedOrigins?: Array<string>;
  knowledgeIds?: Array<string>;
  /**
   * When true, the agent is created as the Ranch admin on first deploy: any existing admin is demoted (and redeployed without RANCH_ADMIN), and this agent boots with RANCH_ADMIN=true + a service token. Single-admin invariant is enforced.
   */
  isAdmin?: boolean;
  /**
   * Enable debug mode — emits the prompt-debug event stream and verbose pod logs (LOG_LEVEL=debug). The verbose-log half applies on the next agent restart; the prompt-debug stream flips live.
   */
  debugEnabled?: boolean;
};

export type FileChunkDto = {
  path: string;
  /**
   * UTF-8 slice of the file from `offset`.
   */
  content: string;
  /**
   * Byte length of `content`.
   */
  size: number;
  /**
   * Full byte length of the file.
   */
  totalSize: number;
  /**
   * Byte offset of the first byte of `content`.
   */
  offset: number;
  /**
   * Pass as `offset` on the next request. `null` when there is no more data.
   */
  nextOffset: number | null;
  hasMore: boolean;
  updatedAt: string;
};

export type SaveFileDto = {
  /**
   * Full file content as text
   */
  content: string;
};

export type DeleteFilesDto = {
  /**
   * Number of S3 objects deleted by this request.
   */
  deleted: number;
};

export type BridleTextPartDto = {
  type: "text" | "image" | "file";
  text: string;
};

export type BridleImagePartDto = {
  type: "text" | "image" | "file";
  /**
   * Base64-encoded image data
   */
  base64: string;
  /**
   * MIME type
   */
  mediaType: string;
};

export type SendMessageDto = {
  /**
   * Message text (plain-text shorthand)
   */
  text: string;
  /**
   * Rich content parts. If omitted, built from text + images.
   */
  parts?: Array<BridleTextPartDto>;
  /**
   * Attached images (legacy — prefer parts)
   */
  images?: Array<BridleImagePartDto>;
};

export type BridleHealthDto = {
  ok: boolean;
  /**
   * Whether any agent runtime is connected via WebSocket
   */
  agentConnected: boolean;
  /**
   * Number of browser clients connected
   */
  browserClients: number;
};

export type BridleAgentHealthDto = {
  ok: boolean;
  /**
   * Whether this agent is connected via WebSocket
   */
  agentConnected: boolean;
  /**
   * Number of browser clients connected to this agent
   */
  browserClients: number;
  /**
   * Bot identifier
   */
  agentId: string;
};

export type TranscriptMessageDto = {
  id: string;
  role: "user" | "assistant";
  text: string;
  /**
   * Unix epoch milliseconds.
   */
  ts: number;
};

export type TranscriptResponseDto = {
  messages: Array<TranscriptMessageDto>;
  /**
   * Channel the transcript was loaded from.
   */
  channel: string;
  /**
   * Pass back as `cursor` to fetch the previous page. `null` when no older messages.
   */
  nextCursor: string | null;
  hasMore: boolean;
};

export type ImportSkillUrlDto = {
  /**
   * GitHub URL — folder (tree/<sha>/<path>) or file (blob/<sha>/<path>). The folder must contain a SKILL.md or README.md.
   */
  url: string;
  name?: string;
  /**
   * If true and a skill with the same slug already exists, fully replace it instead of returning 409.
   */
  overwrite?: boolean;
};

export type ImportSkillDto = {
  /**
   * GitHub owner/repo as returned by /skills/search
   */
  repo: string;
  /**
   * Path to the SKILL.md file inside the repo
   */
  path: string;
  /**
   * Override the auto-derived slug. Lowercase letters, digits and dashes.
   */
  name?: string;
  /**
   * If true and a skill with the same slug already exists, fully replace it instead of returning 409.
   */
  overwrite?: boolean;
};

export type CreateSkillDto = {
  /**
   * Unique slug — lowercase letters, digits, dashes
   */
  name: string;
  title: string;
  /**
   * Markdown body of the skill
   */
  body: string;
  description?: string;
};

export type UpdateSkillDto = {
  /**
   * Unique slug — lowercase letters, digits, dashes
   */
  name?: string;
  title?: string;
  /**
   * Markdown body of the skill
   */
  body?: string;
  description?: string;
};

export type ChatSessionDto = {
  id: string;
  agentId: string;
  channel: "bridle" | "telegram" | "slack" | "internal";
  externalUserId: string;
  sessionKey: string;
  title?: {
    [key: string]: unknown;
  } | null;
  /**
   * Last message text, truncated
   */
  preview?: {
    [key: string]: unknown;
  } | null;
  lastRole?: "user" | "assistant";
  /**
   * Unix ms via ISO
   */
  lastMessageAt: string;
  /**
   * Monotonic lifetime total
   */
  messageCount: number;
  userMessageCount: number;
  summary?: {
    [key: string]: unknown;
  } | null;
  summaryAt?: {
    [key: string]: unknown;
  } | null;
  /**
   * topics/sentiment/resolved/language
   */
  insights?: {
    [key: string]: unknown;
  } | null;
  archived: boolean;
  createdAt: string;
  updatedAt: string;
};

export type ChatListResponseDto = {
  items: Array<ChatSessionDto>;
  total: number;
  page: number;
  perPage: number;
};

export type ChatMessageDto = {
  id: string;
  role:
    | "user"
    | "assistant"
    | "summary"
    | "tool_call"
    | "tool_result"
    | "system";
  text: string;
  /**
   * Unix epoch ms
   */
  ts: number;
};

export type ChatMessagesResponseDto = {
  messages: Array<ChatMessageDto>;
  /**
   * Pass to fetch the previous (older) page
   */
  nextCursor?: {
    [key: string]: unknown;
  } | null;
  hasMore: boolean;
};

export type SyncChatsDto = {
  /**
   * Reconcile only this agent; omit for all agents
   */
  agentId?: string;
};

export type SyncChatsResponseDto = {
  scannedAgents: number;
  scannedFiles: number;
  upserted: number;
  skipped: number;
};

export type CreateChatFeedbackDto = {
  /**
   * Event.id of the rated assistant message
   */
  messageId: string;
  /**
   * 1 = 👍, -1 = 👎
   */
  rating: 1 | -1;
  comment?: string;
};

export type ChatFeedbackDto = {
  id: string;
  messageId: string;
  rating: 1 | -1;
  comment?: {
    [key: string]: unknown;
  } | null;
  source: string;
  authorId?: {
    [key: string]: unknown;
  } | null;
  createdAt: string;
};

export type TelegramChannelConfigDto = {
  /**
   * Telegram bot HTTP API token (issued by @BotFather).
   */
  botToken: string;
  /**
   * Public bot username without @ — shown on landing pages.
   */
  botName?: string;
  /**
   * Comma-separated Telegram chat IDs treated as bot admins by the runtime.
   */
  adminIds?: string;
};

export type AgentChannelDto = {
  /**
   * Channel type. Discriminator — config shape depends on this. v1 only telegram.
   */
  type: "telegram";
  config: TelegramChannelConfigDto;
};

export type SetAgentChannelsDto = {
  /**
   * Replace the full set of channels. Pass [] to clear all channels.
   */
  channels: Array<AgentChannelDto>;
};

export enum AssignableUserRoleTypes {
  ADMIN = "Admin",
  USER = "User",
}

export type CreateUserDto = {
  name: string;
  email: string;
  password: string;
  role?: AssignableUserRoleTypes;
};

export type UpdateUserDto = {
  name?: string;
  email?: string;
  password?: string;
  status?: "active" | "invited" | "disabled";
};

export type UpdateUserRoleDto = {
  role: AssignableUserRoleTypes;
};

export type SaveTemplateFileDto = {
  /**
   * Full file content as text
   */
  content: string;
};

export type InstallDeclaredSkillDto = {
  id: string;
  resolved: boolean;
};

export type InstallDeclaredMcpDto = {
  id: string;
  resolved: boolean;
};

export type InstallDeclaredSecretDto = {
  name: string;
  required: boolean;
};

export type InstallDeclaredDto = {
  skills: Array<InstallDeclaredSkillDto>;
  mcp: Array<InstallDeclaredMcpDto>;
  secrets: Array<InstallDeclaredSecretDto>;
};

export type InstallFileCountsDto = {
  agentFiles: number;
  scenarioFiles: number;
};

export type InstallPreviewDto = {
  /**
   * The parsed manifest. Returned as raw JSON so the UI can render any field without typed coupling.
   */
  manifest: {
    [key: string]: unknown;
  };
  willCreate: boolean;
  willUpgrade: boolean;
  existingTemplateId?: string;
  declared: InstallDeclaredDto;
  files: InstallFileCountsDto;
  warnings: Array<string>;
};

export type InstallResultDto = {
  templateId: string;
  templateName: string;
  filesUploaded: number;
  scenariosSeeded: number;
  mcpAttached: Array<string>;
  skillsAttached: Array<string>;
  unresolvedMcp: Array<string>;
  unresolvedSkills: Array<string>;
  warnings: Array<string>;
};

export type InstallFromGitDto = {
  /**
   * Git URL — https://, http://, git@host:..., or ssh://host/.../repo.git
   */
  gitUrl: string;
  /**
   * Optional ref — branch, tag, or short SHA. Defaults to the remote default branch.
   */
  gitRef?: string;
  /**
   * Operator-supplied params (e.g. {"language":"ru"}). Validated against the manifest at install time.
   */
  params?: {
    [key: string]: unknown;
  };
  /**
   * Operator-supplied secrets (e.g. {"MCP_RANCH_AUTH":"sk-..."}). Used to resolve $secret:NAME references in the manifest at install time (currently for mcp[].authValue). Never echoed back.
   */
  secrets?: {
    [key: string]: unknown;
  };
};

export type CreatePaddockScenarioMessageDto = {
  text: string;
  from: string;
  delayMs?: number;
};

export type CreatePaddockSuccessCriterionDto = {
  dimension:
    | "correctness"
    | "tool_usage"
    | "soul_compliance"
    | "response_quality"
    | "error_handling";
  description: string;
  weight: number;
};

export type CreatePaddockScenarioSetupDto = {
  files?: {
    [key: string]: string;
  };
  env?: {
    [key: string]: string;
  };
  tools?: Array<string>;
};

export type CreatePaddockScenarioDto = {
  templateId?: string | null;
  agentId?: string | null;
  category:
    | "tool_use"
    | "memory"
    | "conversation"
    | "patching_workflow"
    | "edge_case"
    | "multi_turn"
    | "error_recovery";
  difficulty: "easy" | "medium" | "hard" | "adversarial";
  name: string;
  description: string;
  expectedBehavior: string;
  messages: Array<CreatePaddockScenarioMessageDto>;
  successCriteria: Array<CreatePaddockSuccessCriterionDto>;
  setup?: CreatePaddockScenarioSetupDto | null;
};

export type GeneratePaddockScenarioDto = {
  /**
   * Free-form description of the problem / behavior the user wants to test.
   */
  description: string;
  templateId?: string | null;
  agentId?: string | null;
  category?:
    | "tool_use"
    | "memory"
    | "conversation"
    | "patching_workflow"
    | "edge_case"
    | "multi_turn"
    | "error_recovery";
  difficulty?: "easy" | "medium" | "hard" | "adversarial";
  /**
   * Optional LlmCredential id; if omitted, the first active Anthropic credential is used.
   */
  credentialId?: string;
};

export type UpdatePaddockScenarioDto = {
  category?:
    | "tool_use"
    | "memory"
    | "conversation"
    | "patching_workflow"
    | "edge_case"
    | "multi_turn"
    | "error_recovery";
  difficulty?: "easy" | "medium" | "hard" | "adversarial";
  name?: string;
  description?: string;
  expectedBehavior?: string;
  messages?: Array<CreatePaddockScenarioMessageDto>;
  successCriteria?: Array<CreatePaddockSuccessCriterionDto>;
  setup?: CreatePaddockScenarioSetupDto | null;
};

export type SecretEntryDto = {
  name: string;
  value: string;
  updatedAt: string | null;
};

export type SecretListDto = {
  provider: "aws" | "file";
  secrets: Array<SecretEntryDto>;
};

export type SetSecretDto = {
  /**
   * Secret key. Upsert: an existing key is overwritten, a new key is created.
   */
  key: string;
  /**
   * Secret value to store.
   */
  value: string;
};

export type DeleteSecretDto = {
  /**
   * Secret key to delete. No-op if the key does not exist.
   */
  key: string;
};

export type ReplaceSecretsDto = {
  /**
   * Full secret store for the agent — replaces everything. Pass {} to clear. Mirrors AWS Secrets Manager's plaintext-edit semantics.
   */
  store: {
    [key: string]: string;
  };
};

export type ReportUsageDto = {
  date: string;
  /**
   * Per-model usage. Key is the canonical model name (e.g. claude-sonnet-4-6).
   */
  byModel: {
    [key: string]: unknown;
  };
};

export type RunPaddockJudgeOverrideDto = {
  credentialIds?: Array<string>;
  threshold?: number;
  maxLlmCalls?: number;
  maxTimeMs?: number;
};

export type RunPaddockEvaluationDto = {
  agentId: string;
  /**
   * Optional subset of scenario IDs. If omitted, runs the agent’s template scenarios merged with agent overrides.
   */
  scenarioIds?: Array<string>;
  judgeOverride?: RunPaddockJudgeOverrideDto;
};

export type BrowserSessionDto = {
  id: string;
  userId: string;
  accountKey: string;
  status: "idle" | "active" | "needs_login" | "expired" | "stuck";
  lastUsedAt: string;
  createdAt: string;
  updatedAt: string;
};

export type OpenSessionDto = {
  /**
   * Account identifier scoped to the calling user, e.g. "instagram:miybot" or "paypal:main". Must match /^[a-zA-Z0-9_:\-]+$/ — anything else is rejected before it can touch the profile filesystem path.
   */
  accountKey: string;
  /**
   * Page to navigate to in the pre-warmed Chrome. Drives what the VNC viewer renders when the user opens the returned vncUrl — set this to the service's login page (e.g. "https://www.instagram.com/accounts/login/"). Defaults to about:blank if omitted; the user can still type a URL in the address bar.
   */
  loginUrl?: string;
};

export type BrowserSessionConnectionDto = {
  session: BrowserSessionDto;
  /**
   * CDP WebSocket URL. Carries a single-use launch payload and the pool token — never expose to UI, only to authenticated runtime calls.
   */
  cdpUrl: string;
  /**
   * Live VNC URL (signed JWT, 15 min TTL). Send to the end user when they need to finish a 2FA/CAPTCHA flow manually.
   */
  vncUrl?: {
    [key: string]: unknown;
  } | null;
};

export type SetStatusDto = {
  status: "idle" | "active" | "needs_login" | "expired" | "stuck";
};

export type OpenInternalSessionDto = {
  /**
   * Account identifier scoped to the calling user, e.g. "instagram:miybot" or "paypal:main". Must match /^[a-zA-Z0-9_:\-]+$/ — anything else is rejected before it can touch the profile filesystem path.
   */
  accountKey: string;
  /**
   * Page to navigate to in the pre-warmed Chrome. Drives what the VNC viewer renders when the user opens the returned vncUrl — set this to the service's login page (e.g. "https://www.instagram.com/accounts/login/"). Defaults to about:blank if omitted; the user can still type a URL in the address bar.
   */
  loginUrl?: string;
  /**
   * Owning user. Trusted only because the bridle key gates this endpoint — the runtime forwards ctx.from from the authenticated chat session.
   */
  userId: string;
};

export type InternalSetStatusDto = {
  status: "idle" | "active" | "needs_login" | "expired" | "stuck";
  userId: string;
};

export type InternalSessionRefDto = {
  userId: string;
};

export type IssueExtensionTokenDto = {
  /**
   * Agent the extension token will be scoped to. The token only allows writing state files under this agent's S3 prefix.
   */
  agentId: string;
  /**
   * User ID (within the agent context — typically the Telegram user ID for chat-driven agents, or "admin" for the admin agent). Used as the filename prefix so multiple humans can keep separate cookies inside one agent.
   */
  userId: string;
  /**
   * Token lifetime in days. Defaults to 30; max 365.
   */
  ttlDays?: number;
};

export type IssueExtensionTokenResponseDto = {
  token: string;
  /**
   * Unix seconds
   */
  exp: number;
};

export type StorageStateCookieDto = {
  name: string;
  value: string;
  domain: string;
  path: string;
  /**
   * Unix seconds, or -1 for session cookie
   */
  expires: number;
  httpOnly: boolean;
  secure: boolean;
  sameSite: "Strict" | "Lax" | "None";
};

export type ImportStateDto = {
  /**
   * Profile name. Must match the value the agent will pass as `profile` to browser_play. Sanitized server-side before being used as a filename.
   */
  profile: string;
  /**
   * Cookies in Playwright storageState shape. Re-used 1:1 by the agent runtime when launching Chromium with { storageState: <file> }.
   */
  cookies: Array<StorageStateCookieDto>;
  /**
   * Per-origin localStorage entries. The extension does not collect these today (would need a per-origin content script), but we accept them so future versions can fill them in without an API bump.
   */
  origins?: Array<string>;
  /**
   * User-Agent string of the browser the cookies were exported from. The agent runtime applies this to its Playwright context so Instagram/Facebook/banks see the SAME browser fingerprint as the one that issued the session — a mismatch (Mac Chrome → Linux HeadlessChrome) is the main reason replayed cookies still hit the login page.
   */
  userAgent?: string;
};

export type ImportStateResponseDto = {
  ok: boolean;
  /**
   * Relative path under the agent S3 prefix where the storageState was saved. The runtime sees this as `<agentDir>/<path>` after the next S3 sync tick.
   */
  path: string;
  cookies: number;
};

export type CatalogueItemDto = {
  /**
   * Stable service key. Use this in POST /integrations/accounts.
   */
  service: string;
  title: string;
  description: string;
  iconUrl: string;
  mechanism: "browser" | "secret";
  /**
   * Browser-mechanism: URL the pool Chrome navigates to before the user opens the VNC view.
   */
  loginUrl?: string;
  /**
   * Browser-mechanism: hint text the UI shows under the accountKey input.
   */
  accountKeyHint?: string;
  /**
   * Browser-mechanism: domains the Chrome extension auto-matches the current tab against (suffix match).
   */
  domains?: Array<string>;
  /**
   * Secret-mechanism: env var name the runtime exposes to agents.
   */
  secretEnvKey?: string;
  /**
   * Secret-mechanism: short help string the UI shows under the secret input.
   */
  secretHelp?: string;
};

export type IntegrationAccountDto = {
  id: string;
  userId: string;
  service: string;
  /**
   * Account label scoped to (userId, service). For browser-mechanism this is also the BrowserSession.accountKey suffix.
   */
  accountKey: string;
  mechanism: "browser" | "secret";
  label?: {
    [key: string]: unknown;
  };
  /**
   * pending: row exists but underlying credential not yet stored. connected: credential ready. needs_login: cookies expired or session lost. revoked: user disconnected.
   */
  status: "pending" | "connected" | "needs_login" | "revoked";
  createdAt: string;
  updatedAt: string;
};

export type ConnectIntegrationDto = {
  /**
   * Catalogue key (see GET /integrations/catalogue).
   */
  service: string;
  /**
   * User-chosen label for this account. Becomes part of BrowserSession.accountKey for browser-mechanism services. Same charset rules as browser sessions.
   */
  accountKey: string;
  /**
   * Human-friendly label shown in the admin UI list.
   */
  label?: string;
};

export type LoginInstructionDto = {
  /**
   * IntegrationAccount.id these instructions are for.
   */
  accountId: string;
  /**
   * Direct link to the service login page (catalogue.loginUrl) — the user opens this in their normal browser.
   */
  siteUrl: string;
  /**
   * Admin-UI route that walks the user through the connect flow (install extension if needed, log in on siteUrl, send cookies).
   */
  helpUrl: string;
  /**
   * Plain-text instructions the agent can paraphrase for chat channels where helpUrl is not directly clickable. Three short lines.
   */
  instructions: string;
};

export type ImportCookiesCookieDto = {
  name: string;
  value: string;
  domain: string;
  path: string;
  /**
   * Unix seconds, or -1 for session cookie
   */
  expires: number;
  httpOnly: boolean;
  secure: boolean;
  sameSite: "Strict" | "Lax" | "None";
};

export type ImportCookiesDto = {
  /**
   * Cookies in Playwright storageState shape. Either harvested by the Ranch extension or pasted from any third-party cookie-exporter (Cookie-Editor, EditThisCookie, etc.).
   */
  cookies: Array<ImportCookiesCookieDto>;
  /**
   * Per-origin localStorage entries. Most extensions do not collect these — accepted optionally for future-proofing.
   */
  origins?: Array<string>;
  /**
   * User-Agent of the browser that issued the cookies. CRITICAL — Instagram/Meta invalidate sessions whose UA shifts between captures and replays. The runtime applies this verbatim to its Playwright context.
   */
  userAgent?: string;
};

export type SaveSecretDto = {
  /**
   * Raw credential value (API key, token, etc.). Stored in the per-user secret store under a key derived from (service, accountKey). Never echoed back through the API once written.
   */
  value: string;
};

export type ResolvedSecretsDto = {
  /**
   * Map of env-var name → secret value, ready for the runtime to merge into an agent process env. Empty object if the user has no matching secret-mechanism integrations.
   */
  env: {
    [key: string]: string;
  };
};

export type RuntimeAccountDto = {
  service: string;
  accountKey: string;
  /**
   * Exact value to pass as `profile` to browser_play (browser-mechanism only).
   */
  profile: string;
  mechanism: "browser" | "secret";
  status: "pending" | "connected" | "needs_login" | "revoked";
};

export type ListAccountsResponseDto = {
  accounts: Array<RuntimeAccountDto>;
};

export type RequestLoginBodyDto = {
  /**
   * Catalogue service key the agent wants login instructions for.
   */
  service: string;
  /**
   * AccountKey on this integration. Runtime derives it from the `<service>:<accountKey>` profile string the tool was called with.
   */
  accountKey: string;
};

export type IssueIntegrationExtensionTokenDto = {
  /**
   * Token lifetime in days. Defaults to 30; max 365.
   */
  ttlDays?: number;
};

export type IssueIntegrationExtensionTokenResponseDto = {
  token: string;
  /**
   * Unix seconds
   */
  exp: number;
};

export type ExtensionImportStateDto = {
  /**
   * Cookies in Playwright storageState shape. Either harvested by the Ranch extension or pasted from any third-party cookie-exporter (Cookie-Editor, EditThisCookie, etc.).
   */
  cookies: Array<ImportCookiesCookieDto>;
  /**
   * Per-origin localStorage entries. Most extensions do not collect these — accepted optionally for future-proofing.
   */
  origins?: Array<string>;
  /**
   * User-Agent of the browser that issued the cookies. CRITICAL — Instagram/Meta invalidate sessions whose UA shifts between captures and replays. The runtime applies this verbatim to its Playwright context.
   */
  userAgent?: string;
  /**
   * Catalogue service key (auto-detected by the extension from the current tab URL via catalogue.domains).
   */
  service: string;
  /**
   * User-chosen accountKey for this integration. Same charset as POST /integrations/accounts.
   */
  accountKey: string;
};

export type ExtensionImportStateResponseDto = {
  ok: boolean;
  /**
   * IntegrationAccount id (created or reused).
   */
  accountId: string;
  service: string;
  accountKey: string;
  cookies: number;
};

export type HealthControllerCheckData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/health";
};

export type HealthControllerCheckResponses = {
  200: unknown;
};

export type InitControllerStatusData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/setup/status";
};

export type InitControllerStatusResponses = {
  200: unknown;
};

export type InitControllerInitData = {
  body: CreateOwnerDto;
  path?: never;
  query?: never;
  url: "/setup/init";
};

export type InitControllerInitResponses = {
  201: unknown;
};

export type SettingControllerFindAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/settings";
};

export type SettingControllerFindAllResponses = {
  200: unknown;
};

export type SettingControllerFindByGroupData = {
  body?: never;
  path: {
    group: string;
  };
  query?: never;
  url: "/settings/{group}";
};

export type SettingControllerFindByGroupResponses = {
  200: unknown;
};

export type SettingControllerRemoveData = {
  body?: never;
  path: {
    group: string;
    name: string;
  };
  query?: never;
  url: "/settings/{group}/{name}";
};

export type SettingControllerRemoveResponses = {
  200: unknown;
};

export type SettingControllerFindByKeyData = {
  body?: never;
  path: {
    group: string;
    name: string;
  };
  query?: never;
  url: "/settings/{group}/{name}";
};

export type SettingControllerFindByKeyResponses = {
  200: unknown;
};

export type SettingControllerUpsertData = {
  body: UpsertSettingDto;
  path: {
    group: string;
    name: string;
  };
  query?: never;
  url: "/settings/{group}/{name}";
};

export type SettingControllerUpsertResponses = {
  200: unknown;
};

export type LlmControllerFindAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/llms";
};

export type LlmControllerFindAllResponses = {
  200: unknown;
};

export type LlmControllerCreateData = {
  body: CreateLlmCredentialDto;
  path?: never;
  query?: never;
  url: "/llms";
};

export type LlmControllerCreateResponses = {
  201: unknown;
};

export type LlmControllerRemoveData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/llms/{id}";
};

export type LlmControllerRemoveResponses = {
  200: unknown;
};

export type LlmControllerFindByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/llms/{id}";
};

export type LlmControllerFindByIdResponses = {
  200: unknown;
};

export type LlmControllerUpdateData = {
  body: UpdateLlmCredentialDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/llms/{id}";
};

export type LlmControllerUpdateResponses = {
  200: unknown;
};

export type HealthCheckLlmCredentialData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/llms/{id}/health-check";
};

export type HealthCheckLlmCredentialResponses = {
  200: LlmHealthCheckResultDto;
};

export type HealthCheckLlmCredentialResponse =
  HealthCheckLlmCredentialResponses[keyof HealthCheckLlmCredentialResponses];

export type TemplateControllerFindAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/templates";
};

export type TemplateControllerFindAllResponses = {
  200: unknown;
};

export type TemplateControllerCreateData = {
  body: CreateTemplateDto;
  path?: never;
  query?: never;
  url: "/templates";
};

export type TemplateControllerCreateResponses = {
  201: unknown;
};

export type TemplateControllerRemoveData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/templates/{id}";
};

export type TemplateControllerRemoveResponses = {
  200: unknown;
};

export type TemplateControllerFindByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/templates/{id}";
};

export type TemplateControllerFindByIdResponses = {
  200: unknown;
};

export type TemplateControllerUpdateData = {
  body: UpdateTemplateDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/templates/{id}";
};

export type TemplateControllerUpdateResponses = {
  200: unknown;
};

export type TemplateControllerSetSkillsData = {
  body: SetTemplateSkillsDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/templates/{id}/skills";
};

export type TemplateControllerSetSkillsResponses = {
  200: unknown;
};

export type TemplateControllerSetMcpsData = {
  body: SetTemplateMcpsDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/templates/{id}/mcps";
};

export type TemplateControllerSetMcpsResponses = {
  200: unknown;
};

export type McpServerControllerFindAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/mcp-servers";
};

export type McpServerControllerFindAllResponses = {
  200: unknown;
};

export type McpServerControllerCreateData = {
  body: CreateMcpServerDto;
  path?: never;
  query?: never;
  url: "/mcp-servers";
};

export type McpServerControllerCreateResponses = {
  201: unknown;
};

export type McpServerControllerRemoveData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/mcp-servers/{id}";
};

export type McpServerControllerRemoveResponses = {
  200: unknown;
};

export type McpServerControllerFindByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/mcp-servers/{id}";
};

export type McpServerControllerFindByIdResponses = {
  200: unknown;
};

export type McpServerControllerUpdateData = {
  body: UpdateMcpServerDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/mcp-servers/{id}";
};

export type McpServerControllerUpdateResponses = {
  200: unknown;
};

export type AuthControllerLoginData = {
  body: LoginDto;
  path?: never;
  query?: never;
  url: "/auth/login";
};

export type AuthControllerLoginResponses = {
  200: unknown;
};

export type AuthControllerRegisterData = {
  body: RegisterDto;
  path?: never;
  query?: never;
  url: "/auth/register";
};

export type AuthControllerRegisterResponses = {
  200: unknown;
};

export type AuthControllerMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/auth/me";
};

export type AuthControllerMeResponses = {
  200: unknown;
};

export type AuthControllerEmbedTokenData = {
  body: EmbedTokenDto;
  path?: never;
  query?: never;
  url: "/auth/embed/token";
};

export type AuthControllerEmbedTokenResponses = {
  200: unknown;
};

export type ApiKeyControllerFindAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api-keys";
};

export type ApiKeyControllerFindAllResponses = {
  200: unknown;
};

export type ApiKeyControllerCreateData = {
  body: CreateApiKeyDto;
  path?: never;
  query?: never;
  url: "/api-keys";
};

export type ApiKeyControllerCreateResponses = {
  201: unknown;
};

export type ApiKeyControllerRemoveData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api-keys/{id}";
};

export type ApiKeyControllerRemoveResponses = {
  204: void;
};

export type ApiKeyControllerRemoveResponse =
  ApiKeyControllerRemoveResponses[keyof ApiKeyControllerRemoveResponses];

export type GetKnowledgesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/knowledges";
};

export type GetKnowledgesResponses = {
  200: unknown;
};

export type CreateKnowledgeData = {
  body: CreateKnowledgeDto;
  path?: never;
  query?: never;
  url: "/knowledges";
};

export type CreateKnowledgeResponses = {
  201: unknown;
};

export type GetKnowledgeStatusData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/knowledges/status";
};

export type GetKnowledgeStatusResponses = {
  200: unknown;
};

export type GetGraphLabelsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/knowledges/graph/labels";
};

export type GetGraphLabelsResponses = {
  200: unknown;
};

export type GetGraphData = {
  body?: never;
  path?: never;
  query: {
    label: string;
    maxDepth?: number;
    maxNodes?: number;
  };
  url: "/knowledges/graph";
};

export type GetGraphResponses = {
  200: GraphDto;
};

export type GetGraphResponse = GetGraphResponses[keyof GetGraphResponses];

export type DeleteKnowledgeData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/knowledges/{id}";
};

export type DeleteKnowledgeResponses = {
  204: void;
};

export type DeleteKnowledgeResponse =
  DeleteKnowledgeResponses[keyof DeleteKnowledgeResponses];

export type GetKnowledgeData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/knowledges/{id}";
};

export type GetKnowledgeResponses = {
  200: unknown;
};

export type UpdateKnowledgeData = {
  body: UpdateKnowledgeDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/knowledges/{id}";
};

export type UpdateKnowledgeResponses = {
  200: unknown;
};

export type IndexKnowledgeData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/knowledges/{id}/index";
};

export type IndexKnowledgeResponses = {
  202: unknown;
};

export type QueryKnowledgeData = {
  body: QueryKnowledgeDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/knowledges/{id}/query";
};

export type QueryKnowledgeResponses = {
  200: KnowledgeQueryResultDto;
};

export type QueryKnowledgeResponse =
  QueryKnowledgeResponses[keyof QueryKnowledgeResponses];

export type GetKnowledgeSourcesData = {
  body?: never;
  path: {
    knowledgeId: string;
  };
  query?: never;
  url: "/knowledges/{knowledgeId}/sources";
};

export type GetKnowledgeSourcesResponses = {
  200: unknown;
};

export type AddKnowledgeSourceData = {
  body: CreateSourceDto;
  path: {
    knowledgeId: string;
  };
  query?: never;
  url: "/knowledges/{knowledgeId}/sources";
};

export type AddKnowledgeSourceResponses = {
  201: unknown;
};

export type AddKnowledgeSourcesFromSitemapData = {
  body: AddFromSitemapDto;
  path: {
    knowledgeId: string;
  };
  query?: never;
  url: "/knowledges/{knowledgeId}/sources/from-sitemap";
};

export type AddKnowledgeSourcesFromSitemapResponses = {
  201: AddFromSitemapResultDto;
};

export type AddKnowledgeSourcesFromSitemapResponse =
  AddKnowledgeSourcesFromSitemapResponses[keyof AddKnowledgeSourcesFromSitemapResponses];

export type AddKnowledgeSourcesFromArchiveData = {
  body?: never;
  path: {
    knowledgeId: string;
  };
  query?: never;
  url: "/knowledges/{knowledgeId}/sources/from-archive";
};

export type AddKnowledgeSourcesFromArchiveResponses = {
  201: AddFromArchiveResultDto;
};

export type AddKnowledgeSourcesFromArchiveResponse =
  AddKnowledgeSourcesFromArchiveResponses[keyof AddKnowledgeSourcesFromArchiveResponses];

export type DeleteKnowledgeSourceData = {
  body?: never;
  path: {
    knowledgeId: string;
    sourceId: string;
  };
  query?: never;
  url: "/knowledges/{knowledgeId}/sources/{sourceId}";
};

export type DeleteKnowledgeSourceResponses = {
  204: void;
};

export type DeleteKnowledgeSourceResponse =
  DeleteKnowledgeSourceResponses[keyof DeleteKnowledgeSourceResponses];

export type AgentControllerFindAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/agents";
};

export type AgentControllerFindAllResponses = {
  200: unknown;
};

export type AgentControllerCreateData = {
  body: CreateAgentDto;
  path?: never;
  query?: never;
  url: "/agents";
};

export type AgentControllerCreateResponses = {
  201: unknown;
};

export type AgentControllerFindPublicData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/agents/public";
};

export type AgentControllerFindPublicResponses = {
  200: unknown;
};

export type AgentControllerStatusData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/agents/status";
};

export type AgentControllerStatusResponses = {
  200: Array<AgentStatusDto>;
};

export type AgentControllerStatusResponse =
  AgentControllerStatusResponses[keyof AgentControllerStatusResponses];

export type AgentControllerStatusStreamData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/agents/status/stream";
};

export type AgentControllerStatusStreamResponses = {
  200: unknown;
};

export type AgentControllerRemoveData = {
  body?: never;
  path: {
    id: string;
  };
  query: {
    wipeS3: string;
  };
  url: "/agents/{id}";
};

export type AgentControllerRemoveResponses = {
  200: unknown;
};

export type AgentControllerFindByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/agents/{id}";
};

export type AgentControllerFindByIdResponses = {
  200: unknown;
};

export type AgentControllerUpdateData = {
  body: UpdateAgentDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/agents/{id}";
};

export type AgentControllerUpdateResponses = {
  200: unknown;
};

export type GetAgentMetricsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/agents/{id}/metrics";
};

export type GetAgentMetricsResponses = {
  200: AgentMetricsDto;
};

export type GetAgentMetricsResponse =
  GetAgentMetricsResponses[keyof GetAgentMetricsResponses];

export type GetAgentEnvData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/agents/{id}/env";
};

export type GetAgentEnvResponses = {
  200: Array<AgentEnvVarDto>;
};

export type GetAgentEnvResponse =
  GetAgentEnvResponses[keyof GetAgentEnvResponses];

export type GetAgentMcpsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/agents/{id}/mcps";
};

export type GetAgentMcpsResponses = {
  200: Array<AgentMcpDto>;
};

export type GetAgentMcpsResponse =
  GetAgentMcpsResponses[keyof GetAgentMcpsResponses];

export type AgentControllerFindAdminData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/agents/admin/current";
};

export type AgentControllerFindAdminResponses = {
  200: unknown;
};

export type AgentControllerDemoteAdminData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/agents/{id}/promote-admin";
};

export type AgentControllerDemoteAdminResponses = {
  200: unknown;
};

export type AgentControllerPromoteAdminData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/agents/{id}/promote-admin";
};

export type AgentControllerPromoteAdminResponses = {
  201: unknown;
};

export type AgentControllerRestartData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/agents/{id}/restart";
};

export type AgentControllerRestartResponses = {
  201: unknown;
};

export type AgentControllerStopData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/agents/{id}/stop";
};

export type AgentControllerStopResponses = {
  201: unknown;
};

export type AgentControllerStartData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/agents/{id}/start";
};

export type AgentControllerStartResponses = {
  201: unknown;
};

export type RestartByTemplateData = {
  body?: never;
  path: {
    templateId: string;
  };
  query?: never;
  url: "/agents/restart-by-template/{templateId}";
};

export type RestartByTemplateResponses = {
  201: unknown;
};

export type FileControllerListData = {
  body?: never;
  path: {
    agentId: string;
  };
  query?: never;
  url: "/agents/{agentId}/files";
};

export type FileControllerListResponses = {
  200: unknown;
};

export type FileControllerDeleteData = {
  body?: never;
  path: {
    agentId: string;
  };
  query: {
    path: string;
    /**
     * When true, `path` is treated as a folder and every file under it is deleted.
     */
    recursive?: boolean;
  };
  url: "/agents/{agentId}/files/content";
};

export type FileControllerDeleteResponses = {
  200: DeleteFilesDto;
};

export type FileControllerDeleteResponse =
  FileControllerDeleteResponses[keyof FileControllerDeleteResponses];

export type FileControllerReadData = {
  body?: never;
  path: {
    agentId: string;
  };
  query: {
    path: string;
    /**
     * Byte offset to start reading from.
     */
    offset?: number;
    /**
     * Max bytes to return. Server caps at 512 KB.
     */
    limit?: number;
  };
  url: "/agents/{agentId}/files/content";
};

export type FileControllerReadResponses = {
  200: FileChunkDto;
};

export type FileControllerReadResponse =
  FileControllerReadResponses[keyof FileControllerReadResponses];

export type FileControllerSaveData = {
  body: SaveFileDto;
  path: {
    agentId: string;
  };
  query: {
    path: string;
  };
  url: "/agents/{agentId}/files/content";
};

export type FileControllerSaveResponses = {
  200: unknown;
};

export type FileControllerSyncData = {
  body?: never;
  path: {
    agentId: string;
  };
  query?: never;
  url: "/agents/{agentId}/files/sync";
};

export type FileControllerSyncResponses = {
  200: unknown;
};

export type ExportAgentFilesData = {
  body?: never;
  path: {
    agentId: string;
  };
  query?: never;
  url: "/agents/{agentId}/files/export";
};

export type ExportAgentFilesResponses = {
  200: unknown;
};

export type SendBridleMessageData = {
  body: SendMessageDto;
  path: {
    agentId: string;
  };
  query?: never;
  url: "/api/agent/{agentId}/message";
};

export type SendBridleMessageResponses = {
  200: unknown;
};

export type SendBridleMessageSyncData = {
  body: SendMessageDto;
  path: {
    agentId: string;
  };
  query?: never;
  url: "/api/agent/{agentId}/message/sync";
};

export type SendBridleMessageSyncResponses = {
  200: unknown;
};

export type BridleHealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/agent/health";
};

export type BridleHealthResponses = {
  200: BridleHealthDto;
};

export type BridleHealthResponse =
  BridleHealthResponses[keyof BridleHealthResponses];

export type BridleAgentHealthData = {
  body?: never;
  path: {
    agentId: string;
  };
  query?: never;
  url: "/api/agent/{agentId}/health";
};

export type BridleAgentHealthResponses = {
  200: BridleAgentHealthDto;
};

export type BridleAgentHealthResponse =
  BridleAgentHealthResponses[keyof BridleAgentHealthResponses];

export type ListAgentsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/agent/list";
};

export type ListAgentsResponses = {
  200: unknown;
};

export type ResetBridleTranscriptData = {
  body?: never;
  path: {
    agentId: string;
  };
  query?: {
    /**
     * Session channel — defaults to "admin".
     */
    channel?: string;
  };
  url: "/api/agent/{agentId}/transcript";
};

export type ResetBridleTranscriptResponses = {
  204: void;
};

export type ResetBridleTranscriptResponse =
  ResetBridleTranscriptResponses[keyof ResetBridleTranscriptResponses];

export type GetBridleTranscriptData = {
  body?: never;
  path: {
    agentId: string;
  };
  query?: {
    /**
     * Session channel — defaults to "admin" for the admin app.
     */
    channel?: string;
    /**
     * Max messages to return in this page (newest first by file order).
     */
    limit?: number;
    /**
     * Opaque cursor returned by the previous page. Omit for the latest page.
     */
    cursor?: string;
  };
  url: "/api/agent/{agentId}/transcript";
};

export type GetBridleTranscriptResponses = {
  200: TranscriptResponseDto;
};

export type GetBridleTranscriptResponse =
  GetBridleTranscriptResponses[keyof GetBridleTranscriptResponses];

export type ArchiveBridleTranscriptData = {
  body?: never;
  path: {
    agentId: string;
  };
  query?: {
    /**
     * Session channel — defaults to "admin".
     */
    channel?: string;
  };
  url: "/api/agent/{agentId}/transcript/archive";
};

export type ArchiveBridleTranscriptResponses = {
  200: unknown;
};

export type SkillControllerFindAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/skills";
};

export type SkillControllerFindAllResponses = {
  200: unknown;
};

export type SkillControllerCreateData = {
  body: CreateSkillDto;
  path?: never;
  query?: never;
  url: "/skills";
};

export type SkillControllerCreateResponses = {
  201: unknown;
};

export type SkillControllerListSourcesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/skills/sources";
};

export type SkillControllerListSourcesResponses = {
  200: unknown;
};

export type SkillControllerSearchData = {
  body?: never;
  path?: never;
  query: {
    q: string;
  };
  url: "/skills/search";
};

export type SkillControllerSearchResponses = {
  200: unknown;
};

export type SkillControllerImportFromUrlData = {
  body: ImportSkillUrlDto;
  path?: never;
  query?: never;
  url: "/skills/import-url";
};

export type SkillControllerImportFromUrlResponses = {
  201: unknown;
};

export type SkillControllerImportFromGithubData = {
  body: ImportSkillDto;
  path?: never;
  query?: never;
  url: "/skills/import";
};

export type SkillControllerImportFromGithubResponses = {
  201: unknown;
};

export type SkillControllerRemoveData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/skills/{id}";
};

export type SkillControllerRemoveResponses = {
  200: unknown;
};

export type SkillControllerFindByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/skills/{id}";
};

export type SkillControllerFindByIdResponses = {
  200: unknown;
};

export type SkillControllerUpdateData = {
  body: UpdateSkillDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/skills/{id}";
};

export type SkillControllerUpdateResponses = {
  200: unknown;
};

export type FindDependentAgentsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/skills/{id}/agents";
};

export type FindDependentAgentsResponses = {
  200: unknown;
};

export type GetChatsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Restrict to one agent
     */
    agentId?: string;
    channel?: "bridle" | "telegram" | "slack" | "internal";
    /**
     * Matches title / preview / externalUserId
     */
    search?: string;
    /**
     * Show archived sessions
     */
    archived?: boolean;
    /**
     * Include internal (cron/heartbeat) sessions
     */
    includeInternal?: boolean;
    page?: number;
    perPage?: number;
  };
  url: "/chats";
};

export type GetChatsResponses = {
  200: ChatListResponseDto;
};

export type GetChatsResponse = GetChatsResponses[keyof GetChatsResponses];

export type GetChatData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/chats/{id}";
};

export type GetChatResponses = {
  200: ChatSessionDto;
};

export type GetChatResponse = GetChatResponses[keyof GetChatResponses];

export type GetChatMessagesData = {
  body?: never;
  path: {
    id: string;
  };
  query?: {
    limit?: number;
    /**
     * Opaque cursor from a previous page
     */
    cursor?: string;
    /**
     * Comma-separated event types (debug toggle). Default user,assistant,summary. Admins may add tool_call,tool_result,system.
     */
    types?: string;
  };
  url: "/chats/{id}/messages";
};

export type GetChatMessagesResponses = {
  200: ChatMessagesResponseDto;
};

export type GetChatMessagesResponse =
  GetChatMessagesResponses[keyof GetChatMessagesResponses];

export type SyncChatsData = {
  body: SyncChatsDto;
  path?: never;
  query?: never;
  url: "/chats/sync";
};

export type SyncChatsResponses = {
  200: SyncChatsResponseDto;
};

export type SyncChatsResponse = SyncChatsResponses[keyof SyncChatsResponses];

export type SummarizeChatData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/chats/{id}/summarize";
};

export type SummarizeChatResponses = {
  200: ChatSessionDto;
};

export type SummarizeChatResponse =
  SummarizeChatResponses[keyof SummarizeChatResponses];

export type GetMyChatFeedbackData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/chats/{id}/feedback";
};

export type GetMyChatFeedbackResponses = {
  200: Array<ChatFeedbackDto>;
};

export type GetMyChatFeedbackResponse =
  GetMyChatFeedbackResponses[keyof GetMyChatFeedbackResponses];

export type CreateChatFeedbackData = {
  body: CreateChatFeedbackDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/chats/{id}/feedback";
};

export type CreateChatFeedbackResponses = {
  200: ChatFeedbackDto;
};

export type CreateChatFeedbackResponse =
  CreateChatFeedbackResponses[keyof CreateChatFeedbackResponses];

export type DeleteChatFeedbackData = {
  body?: never;
  path: {
    id: string;
    messageId: string;
  };
  query?: never;
  url: "/chats/{id}/feedback/{messageId}";
};

export type DeleteChatFeedbackResponses = {
  204: void;
};

export type DeleteChatFeedbackResponse =
  DeleteChatFeedbackResponses[keyof DeleteChatFeedbackResponses];

export type ExportChatData = {
  body?: never;
  path: {
    id: string;
  };
  query?: {
    /**
     * Download format. json = raw messages, markdown/csv = transcript.
     */
    format?: "json" | "markdown" | "csv";
  };
  url: "/chats/{id}/export";
};

export type ExportChatResponses = {
  200: unknown;
};

export type GetMyChatsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Include archived chats
     */
    archived?: boolean;
    page?: number;
    perPage?: number;
  };
  url: "/me/chats";
};

export type GetMyChatsResponses = {
  200: ChatListResponseDto;
};

export type GetMyChatsResponse = GetMyChatsResponses[keyof GetMyChatsResponses];

export type GetMyChatData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/me/chats/{id}";
};

export type GetMyChatResponses = {
  200: ChatSessionDto;
};

export type GetMyChatResponse = GetMyChatResponses[keyof GetMyChatResponses];

export type GetMyChatMessagesData = {
  body?: never;
  path: {
    id: string;
  };
  query?: {
    limit?: number;
    /**
     * Opaque cursor from a previous page
     */
    cursor?: string;
    /**
     * Comma-separated event types (debug toggle). Default user,assistant,summary. Admins may add tool_call,tool_result,system.
     */
    types?: string;
  };
  url: "/me/chats/{id}/messages";
};

export type GetMyChatMessagesResponses = {
  200: ChatMessagesResponseDto;
};

export type GetMyChatMessagesResponse =
  GetMyChatMessagesResponses[keyof GetMyChatMessagesResponses];

export type SyncMyChatsData = {
  body: SyncChatsDto;
  path?: never;
  query?: never;
  url: "/me/chats/sync";
};

export type SyncMyChatsResponses = {
  200: SyncChatsResponseDto;
};

export type SyncMyChatsResponse =
  SyncMyChatsResponses[keyof SyncMyChatsResponses];

export type ListMyChatFeedbackData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/me/chats/{id}/feedback";
};

export type ListMyChatFeedbackResponses = {
  200: Array<ChatFeedbackDto>;
};

export type ListMyChatFeedbackResponse =
  ListMyChatFeedbackResponses[keyof ListMyChatFeedbackResponses];

export type CreateMyChatFeedbackData = {
  body: CreateChatFeedbackDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/me/chats/{id}/feedback";
};

export type CreateMyChatFeedbackResponses = {
  200: ChatFeedbackDto;
};

export type CreateMyChatFeedbackResponse =
  CreateMyChatFeedbackResponses[keyof CreateMyChatFeedbackResponses];

export type DeleteMyChatFeedbackData = {
  body?: never;
  path: {
    id: string;
    messageId: string;
  };
  query?: never;
  url: "/me/chats/{id}/feedback/{messageId}";
};

export type DeleteMyChatFeedbackResponses = {
  204: void;
};

export type DeleteMyChatFeedbackResponse =
  DeleteMyChatFeedbackResponses[keyof DeleteMyChatFeedbackResponses];

export type ExportMyChatData = {
  body?: never;
  path: {
    id: string;
  };
  query?: {
    /**
     * Download format. json = raw messages, markdown/csv = transcript.
     */
    format?: "json" | "markdown" | "csv";
  };
  url: "/me/chats/{id}/export";
};

export type ExportMyChatResponses = {
  200: unknown;
};

export type GetAgentChannelsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/agents/{id}/channels";
};

export type GetAgentChannelsResponses = {
  200: Array<AgentChannelDto>;
};

export type GetAgentChannelsResponse =
  GetAgentChannelsResponses[keyof GetAgentChannelsResponses];

export type SetAgentChannelsData = {
  body: SetAgentChannelsDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/agents/{id}/channels";
};

export type SetAgentChannelsResponses = {
  200: Array<AgentChannelDto>;
};

export type SetAgentChannelsResponse =
  SetAgentChannelsResponses[keyof SetAgentChannelsResponses];

export type UserControllerFindAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/users";
};

export type UserControllerFindAllResponses = {
  200: unknown;
};

export type UserControllerCreateData = {
  body: CreateUserDto;
  path?: never;
  query?: never;
  url: "/users";
};

export type UserControllerCreateResponses = {
  201: unknown;
};

export type UserControllerRemoveData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/users/{id}";
};

export type UserControllerRemoveResponses = {
  200: unknown;
};

export type UserControllerFindByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/users/{id}";
};

export type UserControllerFindByIdResponses = {
  200: unknown;
};

export type UserControllerUpdateData = {
  body: UpdateUserDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/users/{id}";
};

export type UserControllerUpdateResponses = {
  200: unknown;
};

export type UserControllerUpdateRoleData = {
  body: UpdateUserRoleDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/users/{id}/role";
};

export type UserControllerUpdateRoleResponses = {
  200: unknown;
};

export type TemplateFileControllerListData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/templates/{id}/files";
};

export type TemplateFileControllerListResponses = {
  200: unknown;
};

export type TemplateFileControllerReadData = {
  body?: never;
  path: {
    id: string;
  };
  query: {
    path: string;
  };
  url: "/templates/{id}/files/content";
};

export type TemplateFileControllerReadResponses = {
  200: unknown;
};

export type TemplateFileControllerSaveData = {
  body: SaveTemplateFileDto;
  path: {
    id: string;
  };
  query: {
    path: string;
  };
  url: "/templates/{id}/files/content";
};

export type TemplateFileControllerSaveResponses = {
  200: unknown;
};

export type TemplateFileControllerUploadData = {
  body: {
    files?: Array<Blob | File>;
    /**
     * Relative paths matching files[] by index, e.g. ".agent/agent.md"
     */
    paths?: Array<string>;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/templates/{id}/files/upload";
};

export type TemplateFileControllerUploadResponses = {
  201: unknown;
};

export type PreviewTemplateInstallData = {
  body: {
    archive: Blob | File;
    /**
     * JSON object of operator-supplied params (e.g. {"language":"ru"}). Empty string or omitted = no params.
     */
    params?: string;
  };
  path?: never;
  query?: never;
  url: "/templates/install/preview";
};

export type PreviewTemplateInstallResponses = {
  200: InstallPreviewDto;
};

export type PreviewTemplateInstallResponse =
  PreviewTemplateInstallResponses[keyof PreviewTemplateInstallResponses];

export type InstallTemplateData = {
  body: {
    archive: Blob | File;
    /**
     * JSON object of operator-supplied params.
     */
    params?: string;
    /**
     * JSON object of operator-supplied secrets used to resolve $secret:NAME references in the manifest (e.g. mcp[].authValue).
     */
    secrets?: string;
  };
  path?: never;
  query?: never;
  url: "/templates/install";
};

export type InstallTemplateResponses = {
  200: InstallResultDto;
};

export type InstallTemplateResponse =
  InstallTemplateResponses[keyof InstallTemplateResponses];

export type PreviewTemplateInstallFromGitData = {
  body: InstallFromGitDto;
  path?: never;
  query?: never;
  url: "/templates/install/from-git/preview";
};

export type PreviewTemplateInstallFromGitResponses = {
  200: InstallPreviewDto;
};

export type PreviewTemplateInstallFromGitResponse =
  PreviewTemplateInstallFromGitResponses[keyof PreviewTemplateInstallFromGitResponses];

export type InstallTemplateFromGitData = {
  body: InstallFromGitDto;
  path?: never;
  query?: never;
  url: "/templates/install/from-git";
};

export type InstallTemplateFromGitResponses = {
  200: InstallResultDto;
};

export type InstallTemplateFromGitResponse =
  InstallTemplateFromGitResponses[keyof InstallTemplateFromGitResponses];

export type DownloadTemplateData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/templates/{id}/download";
};

export type DownloadTemplateResponses = {
  200: unknown;
};

export type PaddockScenarioControllerFindAllData = {
  body?: never;
  path?: never;
  query?: {
    templateId?: string;
    agentId?: string;
  };
  url: "/paddock-scenarios";
};

export type PaddockScenarioControllerFindAllResponses = {
  200: unknown;
};

export type PaddockScenarioControllerCreateData = {
  body: CreatePaddockScenarioDto;
  path?: never;
  query?: never;
  url: "/paddock-scenarios";
};

export type PaddockScenarioControllerCreateResponses = {
  201: unknown;
};

export type PaddockScenarioControllerRemoveData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/paddock-scenarios/{id}";
};

export type PaddockScenarioControllerRemoveResponses = {
  200: unknown;
};

export type PaddockScenarioControllerFindByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/paddock-scenarios/{id}";
};

export type PaddockScenarioControllerFindByIdResponses = {
  200: unknown;
};

export type PaddockScenarioControllerUpdateData = {
  body: UpdatePaddockScenarioDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/paddock-scenarios/{id}";
};

export type PaddockScenarioControllerUpdateResponses = {
  200: unknown;
};

export type PaddockScenarioControllerGenerateData = {
  body: GeneratePaddockScenarioDto;
  path?: never;
  query?: never;
  url: "/paddock-scenarios/generate";
};

export type PaddockScenarioControllerGenerateResponses = {
  201: unknown;
};

export type SecretControllerDeleteData = {
  body: DeleteSecretDto;
  path: {
    agentId: string;
  };
  query?: never;
  url: "/agents/{agentId}/secrets";
};

export type SecretControllerDeleteResponses = {
  200: SecretListDto;
};

export type SecretControllerDeleteResponse =
  SecretControllerDeleteResponses[keyof SecretControllerDeleteResponses];

export type SecretControllerListData = {
  body?: never;
  path: {
    agentId: string;
  };
  query?: never;
  url: "/agents/{agentId}/secrets";
};

export type SecretControllerListResponses = {
  200: SecretListDto;
};

export type SecretControllerListResponse =
  SecretControllerListResponses[keyof SecretControllerListResponses];

export type SecretControllerSetData = {
  body: SetSecretDto;
  path: {
    agentId: string;
  };
  query?: never;
  url: "/agents/{agentId}/secrets";
};

export type SecretControllerSetResponses = {
  200: SecretListDto;
};

export type SecretControllerSetResponse =
  SecretControllerSetResponses[keyof SecretControllerSetResponses];

export type SecretControllerReplaceData = {
  body: ReplaceSecretsDto;
  path: {
    agentId: string;
  };
  query?: never;
  url: "/agents/{agentId}/secrets/replace";
};

export type SecretControllerReplaceResponses = {
  200: SecretListDto;
};

export type SecretControllerReplaceResponse =
  SecretControllerReplaceResponses[keyof SecretControllerReplaceResponses];

export type LogControllerGetLogsData = {
  body?: never;
  path: {
    agentId: string;
  };
  query: {
    tail: string;
  };
  url: "/agents/{agentId}/logs";
};

export type LogControllerGetLogsResponses = {
  200: unknown;
};

export type UsageControllerFindForAgentData = {
  body?: never;
  path: {
    agentId: string;
  };
  query?: never;
  url: "/agents/{agentId}/usage";
};

export type UsageControllerFindForAgentResponses = {
  200: unknown;
};

export type UsageControllerReportData = {
  body: ReportUsageDto;
  headers: {
    "x-bridle-api-key": string;
  };
  path: {
    agentId: string;
  };
  query?: never;
  url: "/agents/{agentId}/usage";
};

export type UsageControllerReportResponses = {
  204: void;
};

export type UsageControllerReportResponse =
  UsageControllerReportResponses[keyof UsageControllerReportResponses];

export type UsageControllerFindForCredentialData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/llms/{id}/usage";
};

export type UsageControllerFindForCredentialResponses = {
  200: unknown;
};

export type RancherControllerStatusData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/rancher/status";
};

export type RancherControllerStatusResponses = {
  200: unknown;
};

export type RancherControllerEnsureTemplateData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/rancher/template";
};

export type RancherControllerEnsureTemplateResponses = {
  201: unknown;
};

export type UpgradeControllerStatusData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/upgrade/status";
};

export type UpgradeControllerStatusResponses = {
  200: unknown;
};

export type UpgradeControllerRunData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/upgrade";
};

export type UpgradeControllerRunResponses = {
  201: unknown;
};

export type PaddockEvaluationControllerListData = {
  body?: never;
  path?: never;
  query?: {
    agentId?: string;
    templateId?: string;
    limit?: string;
  };
  url: "/paddock-evaluations";
};

export type PaddockEvaluationControllerListResponses = {
  200: unknown;
};

export type PaddockEvaluationControllerStartData = {
  body: RunPaddockEvaluationDto;
  path?: never;
  query?: never;
  url: "/paddock-evaluations";
};

export type PaddockEvaluationControllerStartResponses = {
  201: unknown;
};

export type PaddockEvaluationControllerGetData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/paddock-evaluations/{id}";
};

export type PaddockEvaluationControllerGetResponses = {
  200: unknown;
};

export type PaddockEvaluationControllerReportData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/paddock-evaluations/{id}/report";
};

export type PaddockEvaluationControllerReportResponses = {
  200: unknown;
};

export type PaddockEvaluationControllerLogsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/paddock-evaluations/{id}/logs";
};

export type PaddockEvaluationControllerLogsResponses = {
  200: unknown;
};

export type PaddockEvaluationControllerScenarioData = {
  body?: never;
  path: {
    id: string;
    scenarioId: string;
  };
  query?: never;
  url: "/paddock-evaluations/{id}/scenarios/{scenarioId}";
};

export type PaddockEvaluationControllerScenarioResponses = {
  200: unknown;
};

export type PaddockEvaluationControllerTraceData = {
  body?: never;
  path: {
    id: string;
  };
  query: {
    scenarioId: string;
  };
  url: "/paddock-evaluations/{id}/trace";
};

export type PaddockEvaluationControllerTraceResponses = {
  200: unknown;
};

export type PaddockEvaluationControllerAbortData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/paddock-evaluations/{id}/abort";
};

export type PaddockEvaluationControllerAbortResponses = {
  201: unknown;
};

export type PaddockEvaluationControllerRerunData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/paddock-evaluations/{id}/rerun";
};

export type PaddockEvaluationControllerRerunResponses = {
  201: unknown;
};

export type ListBrowserSessionsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/browser/sessions";
};

export type ListBrowserSessionsResponses = {
  200: Array<BrowserSessionDto>;
};

export type ListBrowserSessionsResponse =
  ListBrowserSessionsResponses[keyof ListBrowserSessionsResponses];

export type OpenBrowserSessionData = {
  body: OpenSessionDto;
  path?: never;
  query?: never;
  url: "/browser/sessions";
};

export type OpenBrowserSessionResponses = {
  200: BrowserSessionConnectionDto;
};

export type OpenBrowserSessionResponse =
  OpenBrowserSessionResponses[keyof OpenBrowserSessionResponses];

export type DeleteBrowserSessionData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/browser/sessions/{id}";
};

export type DeleteBrowserSessionResponses = {
  204: void;
};

export type DeleteBrowserSessionResponse =
  DeleteBrowserSessionResponses[keyof DeleteBrowserSessionResponses];

export type GetBrowserSessionData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/browser/sessions/{id}";
};

export type GetBrowserSessionResponses = {
  200: BrowserSessionDto;
};

export type GetBrowserSessionResponse =
  GetBrowserSessionResponses[keyof GetBrowserSessionResponses];

export type ResetBrowserSessionData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/browser/sessions/{id}/reset";
};

export type ResetBrowserSessionResponses = {
  200: BrowserSessionConnectionDto;
};

export type ResetBrowserSessionResponse =
  ResetBrowserSessionResponses[keyof ResetBrowserSessionResponses];

export type SetBrowserSessionStatusData = {
  body: SetStatusDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/browser/sessions/{id}/status";
};

export type SetBrowserSessionStatusResponses = {
  200: BrowserSessionDto;
};

export type SetBrowserSessionStatusResponse =
  SetBrowserSessionStatusResponses[keyof SetBrowserSessionStatusResponses];

export type MintBrowserSessionVncUrlData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/browser/sessions/{id}/vnc-url";
};

export type MintBrowserSessionVncUrlResponses = {
  201: unknown;
};

export type OpenBrowserSessionInternalData = {
  body: OpenInternalSessionDto;
  path?: never;
  query?: never;
  url: "/browser/internal/sessions";
};

export type OpenBrowserSessionInternalResponses = {
  201: unknown;
};

export type SetBrowserSessionStatusInternalData = {
  body: InternalSetStatusDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/browser/internal/sessions/{id}/status";
};

export type SetBrowserSessionStatusInternalResponses = {
  201: unknown;
};

export type ResetBrowserSessionInternalData = {
  body: InternalSessionRefDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/browser/internal/sessions/{id}/reset";
};

export type ResetBrowserSessionInternalResponses = {
  201: unknown;
};

export type HarvestBrowserSessionInternalData = {
  body: InternalSessionRefDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/browser/internal/sessions/{id}/harvest";
};

export type HarvestBrowserSessionInternalResponses = {
  201: unknown;
};

export type CleanupBrowserSessionsInternalData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/browser/internal/sessions/cleanup";
};

export type CleanupBrowserSessionsInternalResponses = {
  201: unknown;
};

export type IssueBrowserExtensionTokenData = {
  body: IssueExtensionTokenDto;
  path?: never;
  query?: never;
  url: "/browser/extension/token";
};

export type IssueBrowserExtensionTokenResponses = {
  200: IssueExtensionTokenResponseDto;
};

export type IssueBrowserExtensionTokenResponse =
  IssueBrowserExtensionTokenResponses[keyof IssueBrowserExtensionTokenResponses];

export type ImportBrowserStorageStateData = {
  body: ImportStateDto;
  headers: {
    authorization: string;
  };
  path?: never;
  query?: never;
  url: "/browser/extension/import-state";
};

export type ImportBrowserStorageStateResponses = {
  200: ImportStateResponseDto;
};

export type ImportBrowserStorageStateResponse =
  ImportBrowserStorageStateResponses[keyof ImportBrowserStorageStateResponses];

export type ListIntegrationCatalogueData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/integrations/catalogue";
};

export type ListIntegrationCatalogueResponses = {
  200: Array<CatalogueItemDto>;
};

export type ListIntegrationCatalogueResponse =
  ListIntegrationCatalogueResponses[keyof ListIntegrationCatalogueResponses];

export type ListIntegrationAccountsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/integrations/accounts";
};

export type ListIntegrationAccountsResponses = {
  200: Array<IntegrationAccountDto>;
};

export type ListIntegrationAccountsResponse =
  ListIntegrationAccountsResponses[keyof ListIntegrationAccountsResponses];

export type ConnectIntegrationData = {
  body: ConnectIntegrationDto;
  path?: never;
  query?: never;
  url: "/integrations/accounts";
};

export type ConnectIntegrationResponses = {
  200: IntegrationAccountDto;
};

export type ConnectIntegrationResponse =
  ConnectIntegrationResponses[keyof ConnectIntegrationResponses];

export type DisconnectIntegrationData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/integrations/accounts/{id}";
};

export type DisconnectIntegrationResponses = {
  204: void;
};

export type DisconnectIntegrationResponse =
  DisconnectIntegrationResponses[keyof DisconnectIntegrationResponses];

export type GetIntegrationAccountData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/integrations/accounts/{id}";
};

export type GetIntegrationAccountResponses = {
  200: IntegrationAccountDto;
};

export type GetIntegrationAccountResponse =
  GetIntegrationAccountResponses[keyof GetIntegrationAccountResponses];

export type OpenIntegrationLoginData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/integrations/accounts/{id}/login";
};

export type OpenIntegrationLoginResponses = {
  200: LoginInstructionDto;
};

export type OpenIntegrationLoginResponse =
  OpenIntegrationLoginResponses[keyof OpenIntegrationLoginResponses];

export type ImportIntegrationCookiesData = {
  body: ImportCookiesDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/integrations/accounts/{id}/import-cookies";
};

export type ImportIntegrationCookiesResponses = {
  200: IntegrationAccountDto;
};

export type ImportIntegrationCookiesResponse =
  ImportIntegrationCookiesResponses[keyof ImportIntegrationCookiesResponses];

export type SaveIntegrationSecretData = {
  body: SaveSecretDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/integrations/accounts/{id}/secret";
};

export type SaveIntegrationSecretResponses = {
  200: IntegrationAccountDto;
};

export type SaveIntegrationSecretResponse =
  SaveIntegrationSecretResponses[keyof SaveIntegrationSecretResponses];

export type ResolveIntegrationSecretsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Restrict to one catalogue service (e.g. "openai"). Omit to resolve every connected secret-mechanism integration.
     */
    service?: string;
  };
  url: "/integrations/internal/secrets";
};

export type ResolveIntegrationSecretsResponses = {
  200: ResolvedSecretsDto;
};

export type ResolveIntegrationSecretsResponse =
  ResolveIntegrationSecretsResponses[keyof ResolveIntegrationSecretsResponses];

export type ListIntegrationAccountsForRuntimeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/integrations/internal/accounts";
};

export type ListIntegrationAccountsForRuntimeResponses = {
  200: ListAccountsResponseDto;
};

export type ListIntegrationAccountsForRuntimeResponse =
  ListIntegrationAccountsForRuntimeResponses[keyof ListIntegrationAccountsForRuntimeResponses];

export type RequestIntegrationLoginData = {
  body: RequestLoginBodyDto;
  path?: never;
  query?: never;
  url: "/integrations/internal/request-login";
};

export type RequestIntegrationLoginResponses = {
  200: LoginInstructionDto;
};

export type RequestIntegrationLoginResponse =
  RequestIntegrationLoginResponses[keyof RequestIntegrationLoginResponses];

export type ResolveIntegrationBrowserStateData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Profile identifier — same value passed to `browser_play`. For integration accounts it is composed as `<service>:<accountKey>` (e.g. `instagram:miybot`).
     */
    profile: string;
  };
  url: "/integrations/internal/browser-state";
};

export type ResolveIntegrationBrowserStateResponses = {
  200: unknown;
};

export type IssueIntegrationExtensionTokenData = {
  body: IssueIntegrationExtensionTokenDto;
  path?: never;
  query?: never;
  url: "/integrations/extension/token";
};

export type IssueIntegrationExtensionTokenResponses = {
  200: IssueIntegrationExtensionTokenResponseDto;
};

export type IssueIntegrationExtensionTokenResponse =
  IssueIntegrationExtensionTokenResponses[keyof IssueIntegrationExtensionTokenResponses];

export type ImportIntegrationExtensionStateData = {
  body: ExtensionImportStateDto;
  headers: {
    authorization: string;
  };
  path?: never;
  query?: never;
  url: "/integrations/extension/import-state";
};

export type ImportIntegrationExtensionStateResponses = {
  200: ExtensionImportStateResponseDto;
};

export type ImportIntegrationExtensionStateResponse =
  ImportIntegrationExtensionStateResponses[keyof ImportIntegrationExtensionStateResponses];

export type DownloadIntegrationExtensionData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/integrations/extension/download";
};

export type DownloadIntegrationExtensionResponses = {
  200: unknown;
};

export type SseControllerSseData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/mcp/sse";
};

export type SseControllerSseResponses = {
  200: unknown;
};

export type SseControllerMessagesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/mcp/messages";
};

export type SseControllerMessagesResponses = {
  201: unknown;
};

export type SseControllerDebugSessionsData = {
  body?: never;
  path: {
    teamId: string;
  };
  query?: never;
  url: "/teams/{teamId}/sessions/debug";
};

export type SseControllerDebugSessionsResponses = {
  200: unknown;
};

export type StreamableHttpControllerHandleDeleteRequestData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/mcp/mcp";
};

export type StreamableHttpControllerHandleDeleteRequestResponses = {
  200: unknown;
};

export type StreamableHttpControllerHandleGetRequestData = {
  body?: never;
  path: {
    teamId: string;
  };
  query?: never;
  url: "/mcp/mcp";
};

export type StreamableHttpControllerHandleGetRequestResponses = {
  200: unknown;
};

export type StreamableHttpControllerHandlePostRequestData = {
  body?: never;
  path: {
    teamId: string;
  };
  query?: never;
  url: "/mcp/mcp";
};

export type StreamableHttpControllerHandlePostRequestResponses = {
  201: unknown;
};

export type ClientOptions = {
  baseURL: string;
};
